---
services:
  bento:
    profiles: [bento]
    image: bentopdfteam/bentopdf-simple:latest
    container_name: bento
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: PDF
      homepage.name: Bento PDF
      homepage.icon: bentopdf.png
      homepage.href: https://bento.chenn.dev
      homepage.description: PDF Editing

      pangolin.public-resources.bento.name: bento
      pangolin.public-resources.bento.full-domain: bento.chenn.dev
      pangolin.public-resources.bento.mode: http
      pangolin.public-resources.bento.targets[0].method: http
      pangolin.public-resources.bento.targets[0].port: 8080
      pangolin.public-resources.bento.policy: member
