---
services:
  kan:
    profiles: [kan]
    image: ghcr.io/kanbn/kan:latest
    container_name: kan
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
      NEXT_PUBLIC_BASE_URL: https://kan.chenn.dev
      BETTER_AUTH_SECRET: ${KAN_SECRET}
      POSTGRES_URL: postgres://kan:kan@kan_db/kan

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASS}
      EMAIL_FROM: ${SMTP_USER}
      SMTP_REJECT_UNAUTHORIZED: true

      NEXT_PUBLIC_DISABLE_EMAIL: false
      NEXT_PUBLIC_WHITE_LABEL_HIDE_POWERED_BY: true
      NEXT_PUBLIC_ALLOW_CREDENTIALS: true
      NEXT_PUBLIC_DISABLE_SIGN_UP: false

      OIDC_CLIENT_ID: ${KAN_OIDC_CLIENT}
      OIDC_CLIENT_SECRET: ${KAN_OIDC_SECRET}
      OIDC_DISCOVERY_URL: ${OIDC_DISCOVERY}
    depends_on:
      kan_migrate:
        condition: service_completed_successfully
    networks: [kan, newt]
    labels:
      homepage.group: Project Management
      homepage.name: Kan
      homepage.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kan.png
      homepage.href: https://kan.chenn.dev
      homepage.description: Kanban

      pangolin.public-resources.kan.name: kan
      pangolin.public-resources.kan.full-domain: kan.chenn.dev
      pangolin.public-resources.kan.mode: http
      pangolin.public-resources.kan.targets[0].method: http
      pangolin.public-resources.kan.targets[0].port: 3000
      pangolin.public-resources.kan.policy: member

  kan_db:
    profiles: [kan]
    image: postgres:18-alpine
    container_name: kan_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kan
      POSTGRES_USER: kan
      POSTGRES_PASSWORD: kan
    volumes:
      - $DATA/kan/db:/var/lib/postgresql
    healthcheck:
      test: pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [kan]

  kan_migrate:
    profiles: [kan]
    image: ghcr.io/kanbn/kan-migrate:latest
    container_name: kan_migrate
    restart: no
    environment:
      POSTGRES_URL: postgres://kan:kan@kan_db/kan
    depends_on:
      kan_db:
        condition: service_healthy
    networks: [kan]

networks:
  kan:
