# very early; mostly does not work
---
x-stoat_env: &stoat_env
  STOAT_DOMAIN:
  HOSTNAME: :80
  REVOLT_PUBLIC_URL: https://stoat.chenn.dev/api
  VITE_API_URL: https://stoat.chenn.dev/api
  VITE_WS_URL: wss://stoat.chenn.dev/ws
  VITE_MEDIA_URL: https://stoat.chenn.dev/autumn
  VITE_PROXY_URL: https://stoat.chenn.dev/january
  VITE_CFG_ENABLE_VIDEO: true

  REVOLT__PUSHD__VAPID__PRIVATE_KEY:
  REVOLT__PUSHD__VAPID__PUBLIC_KEY:
  REVOLT__FILES__ENCRYPTION_KEY:
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET:
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY:

services:
  database:
    image: docker.io/mongo
    container_name: database
    restart: unless-stopped
    volumes:
      - $DATA/stoat/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks: [stoat]

  redis:
    image: docker.io/eqalpha/keydb
    container_name: redis
    restart: unless-stopped
    networks: [stoat]

  rabbit:
    image: docker.io/rabbitmq:4
    container_name: rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    volumes:
      - $DATA/stoat/rabbit:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks: [stoat]

  minio:
    image: docker.io/minio/minio
    container_name: minio
    command: server /data
    volumes:
      - $DATA/stoat/minio:/data
    environment:
      MINIO_ROOT_USER: minioautumn
      MINIO_ROOT_PASSWORD: minioautumn
      MINIO_DOMAIN: minio
    restart: unless-stopped
    networks:
      stoat:
        aliases:
          - revolt-uploads.minio

  caddy:
    image: docker.io/caddy
    container_name: caddy
    restart: unless-stopped
    environment:
      <<: *stoat_env
    volumes:
      - ./stoat/Caddyfile:/etc/caddy/Caddyfile
      - $DATA/stoat/caddy-data:/data
      - $DATA/stoat/caddy-config:/config
    networks:
      newt:
      stoat:
        aliases:
          - caddy
    labels:
      pangolin.public-resources.stoat.name: stoat
      pangolin.public-resources.stoat.full-domain: stoat.chenn.dev
      pangolin.public-resources.stoat.protocol: http
      pangolin.public-resources.stoat.ssl: true
      pangolin.public-resources.stoat.targets[0].method: http
      pangolin.public-resources.stoat.targets[0].port: 80

  api:
    image: ghcr.io/stoatchat/api:v0.12.0
    container_name: api
    environment:
      <<: *stoat_env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbit:
        condition: service_healthy
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  events:
    image: ghcr.io/stoatchat/events:v0.12.0
    container_name: events
    environment:
      <<: *stoat_env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  autumn:
    image: ghcr.io/stoatchat/file-server:v0.12.0
    container_name: autumn
    environment:
      <<: *stoat_env
    depends_on:
      database:
        condition: service_healthy
      createbuckets:
        condition: service_started
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  january:
    image: ghcr.io/stoatchat/proxy:v0.12.0
    container_name: january
    environment:
      <<: *stoat_env
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  gifbox:
    image: ghcr.io/stoatchat/gifbox:v0.12.0
    container_name: gifbox
    environment:
      <<: *stoat_env
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  crond:
    image: ghcr.io/stoatchat/crond:v0.12.0
    container_name: crond
    environment:
      <<: *stoat_env
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  pushd:
    image: ghcr.io/stoatchat/pushd:v0.12.0
    container_name: pushd
    environment:
      <<: *stoat_env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbit:
        condition: service_healthy
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    restart: unless-stopped
    networks: [stoat]

  voice-ingress:
    image: ghcr.io/stoatchat/voice-ingress:v0.12.0
    container_name: voice
    environment:
      <<: *stoat_env
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    volumes:
      - ./stoat/Revolt.toml:/Revolt.toml
    networks: [stoat]

  livekit:
    image: ghcr.io/stoatchat/livekit-server:v1.9.13
    container_name: livekit
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    command: --config /etc/livekit.yml
    volumes:
      - ./stoat/livekit.yml:/etc/livekit.yml
    networks: [stoat, newt]
    labels:
      pangolin.public-resources.tcp-7881.name: tcp-7881
      pangolin.public-resources.tcp-7881.protocol: tcp
      pangolin.public-resources.tcp-7881.proxy-port: 7881
      pangolin.public-resources.tcp-7881.targets[0].port: 7881

      pangolin.public-resources.udp-50000.name: udp-50000
      pangolin.public-resources.udp-50000.protocol: udp
      pangolin.public-resources.udp-50000.proxy-port: 50000
      pangolin.public-resources.udp-50000.targets[0].port: 50000
      pangolin.public-resources.udp-50001.name: udp-50001
      pangolin.public-resources.udp-50001.protocol: udp
      pangolin.public-resources.udp-50001.proxy-port: 50001
      pangolin.public-resources.udp-50001.targets[0].port: 50001
      pangolin.public-resources.udp-50002.name: udp-50002
      pangolin.public-resources.udp-50002.protocol: udp
      pangolin.public-resources.udp-50002.proxy-port: 50002
      pangolin.public-resources.udp-50002.targets[0].port: 50002
      pangolin.public-resources.udp-50003.name: udp-50003
      pangolin.public-resources.udp-50003.protocol: udp
      pangolin.public-resources.udp-50003.proxy-port: 50003
      pangolin.public-resources.udp-50003.targets[0].port: 50003
      pangolin.public-resources.udp-50004.name: udp-50004
      pangolin.public-resources.udp-50004.protocol: udp
      pangolin.public-resources.udp-50004.proxy-port: 50004
      pangolin.public-resources.udp-50004.targets[0].port: 50004
      pangolin.public-resources.udp-50005.name: udp-50005
      pangolin.public-resources.udp-50005.protocol: udp
      pangolin.public-resources.udp-50005.proxy-port: 50005
      pangolin.public-resources.udp-50005.targets[0].port: 50005
      pangolin.public-resources.udp-50006.name: udp-50006
      pangolin.public-resources.udp-50006.protocol: udp
      pangolin.public-resources.udp-50006.proxy-port: 50006
      pangolin.public-resources.udp-50006.targets[0].port: 50006
      pangolin.public-resources.udp-50007.name: udp-50007
      pangolin.public-resources.udp-50007.protocol: udp
      pangolin.public-resources.udp-50007.proxy-port: 50007
      pangolin.public-resources.udp-50007.targets[0].port: 50007
      pangolin.public-resources.udp-50008.name: udp-50008
      pangolin.public-resources.udp-50008.protocol: udp
      pangolin.public-resources.udp-50008.proxy-port: 50008
      pangolin.public-resources.udp-50008.targets[0].port: 50008
      pangolin.public-resources.udp-50009.name: udp-50009
      pangolin.public-resources.udp-50009.protocol: udp
      pangolin.public-resources.udp-50009.proxy-port: 50009
      pangolin.public-resources.udp-50009.targets[0].port: 50009

  createbuckets:
    image: docker.io/minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc ready minio; do
        /usr/bin/mc alias set minio http://minio:9000 minioautumn minioautumn;
        echo 'Waiting minio...' && sleep 1;
      done;
      /usr/bin/mc mb minio/revolt-uploads;
      exit 0;
      "
    networks: [stoat]

  web:
    image: ghcr.io/stoatchat/for-web:3a83b8c
    container_name: web
    restart: unless-stopped
    environment:
      <<: *stoat_env
    networks: [stoat]

networks:
  stoat:
  newt:
    external: true
