---
services:
  gocron:
    profiles: [gocron]
    image: ghcr.io/flohoss/gocron:latest
    restart: unless-stopped
    container_name: gocron
    hostname: gocron
    user: $PUID:$PGID
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # - NTFY_URL=https://
      # - NTFY_TOPIC=cron
      # - NTFY_TOKEN=<token>
    volumes:
      - ./gocron:/app/config/
    networks: [traefik]
    labels:
      homepage.instance.private.group: Infra
      homepage.instance.private.name: Go Cron
      homepage.instance.private.icon: chronograf.png
      homepage.instance.private.href: https://cron.henn.dev
      homepage.instance.private.description: Go Cron

      traefik.enable: true
      traefik.http.routers.cron.rule: Host(`cron.henn.dev`)
      traefik.http.routers.cron.entrypoints: websecure
      traefik.http.routers.cron.middlewares: hdrs@file
      traefik.http.routers.cron.tls.certresolver: cf
      traefik.http.services.cron.loadbalancer.server.port: 8156
