# admin/admin
---
services:
  gotify:
    profiles: [gotify]
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    volumes:
      - $DATA/gotify/data:/app/data
      - ./gotify/config.yml:/etc/gotify/config.yml
    networks: [newt]
    labels:
      homepage.group: Infra
      homepage.name: Gotify
      homepage.icon: gotify.png
      homepage.href: https://gotify.chenn.dev
      homepage.description: Notification Server

      pangolin.public-resources.gotify.name: gotify
      pangolin.public-resources.gotify.full-domain: gotify.chenn.dev
      pangolin.public-resources.gotify.protocol: http
      pangolin.public-resources.gotify.ssl: true
      pangolin.public-resources.gotify.targets[0].method: http
      pangolin.public-resources.gotify.targets[0].port: 80
      pangolin.public-resources.gotify.auth.sso-enabled: true
      pangolin.public-resources.gotify.auth.sso-roles[0]: Member
      pangolin.public-resources.gotify.rules[0].action: pass
      pangolin.public-resources.gotify.rules[0].match: country
      pangolin.public-resources.gotify.rules[0].value: US
      pangolin.public-resources.gotify.rules[1].action: deny
      pangolin.public-resources.gotify.rules[1].match: country
      pangolin.public-resources.gotify.rules[1].value: ALL
