---
services:
  lancache:
    profiles: [lancache]
    image: ghcr.io/regix1/monolithic:latest
    container_name: lancache
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      USE_GENERIC_CACHE: true
      NOSLICE_FALLBACK: true

      LANCACHE_IP: ${LANCACHE_IP}
      DNS_BIND_IP: ${LANCACHE_DNS}
      UPSTREAM_DNS: 1.1.1.1

      CACHE_DISK_SIZE: 1000g
      CACHE_INDEX_SIZE: 500m
      CACHE_MAX_AGE: 3560d
      CACHE_SLICE_SIZE: 1m
      MIN_FREE_DISK: 10g
    volumes:
      - $DATA/lancache/cache:/data/cache
      - $DATA/lancache/logs:/data/logs
    ports:
      - '${LANCACHE_IP}:80:80/tcp'
      - '${LANCACHE_IP}:443:443/tcp'

  # dc exec lancache_manager cat /data/security/api_key.txt | login api key is also in the docker log
  lancache_manager:
    profiles: [lancache]
    image: ghcr.io/regix1/lancache-manager:latest
    container_name: lancache_manager
    restart: unless-stopped
    volumes:
      - $DATA/lancache_manager/data:/data
      - $DATA/lancache/cache:/cache
      - $DATA/lancache/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 0
      PGID: 0
      TZ: $TZ
      LanCache__LogPath: /logs/access.log
      LanCache__CachePath: /cache/cache
      Optimizations__EnableGarbageCollectionManagement: true

      Prefill__NetworkMode: host
      Prefill__LancacheIp: ${LANCACHE_IP}
      Prefill__LancacheDnsIp: ${LANCACHE_DNS}

      POSTGRES_MODE: embedded
      POSTGRES_USER: lancache
      POSTGRES_PASSWORD: ${LANCACHE_DB}

      Security__EnableAuthentication: true
      Security__RequireAuthForMetrics: false
      Security__GuestSessionDurationHours: 6
      Security__AllowedOrigins: https://lancache.chenn.dev
    networks: [newt]
    labels:
      homepage.group: Infra
      homepage.name: Lancache Manager
      homepage.icon: lancache.png
      homepage.href: https://lancache.chenn.dev
      homepage.description: Lancache Manager GUI

      pangolin.public-resources.lancache.name: lancache
      pangolin.public-resources.lancache.full-domain: lancache.chenn.dev
      pangolin.public-resources.lancache.mode: http
      pangolin.public-resources.lancache.targets[0].method: http
      pangolin.public-resources.lancache.targets[0].port: 80
      pangolin.public-resources.lancache.policy: member
