---
services:
  librespeed:
    profiles: [librespeed]
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DATA/librespeed:/config
    labels:
      homepage.instance.private.group: Tools
      homepage.instance.private.name: librespeed
      homepage.instance.private.icon: librespeed.png
      # bypass traefik and use the ip for performance over 3Gbps
      homepage.instance.private.href: http://$SVC_IP:3040
      homepage.instance.private.description: Internet Speed test
    ports:
      - '$SVC_IP:3040:80'
