---
services:
  newt:
    profiles: [newt]
    image: fosrl/newt:latest
    container_name: newt
    restart: unless-stopped
    environment:
      PANGOLIN_ENDPOINT: ${VPS0_PANGOLIN_ENDPOINT}
      NEWT_ID: ${RACK4_DOCKER_NEWT_ID}
      NEWT_SECRET: ${RACK4_DOCKER_NEWT_SECRET}
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [newt]

networks:
  newt:
    name: newt
    driver: bridge
    ipam:
      config:
        - subnet: ${NEWT_SUBNET}
          gateway: ${NEWT_GATEWAY}
