---
services:
  newt:
    profiles: [newt]
    image: fosrl/newt:latest
    container_name: newt
    restart: unless-stopped
    environment:
      PANGOLIN_ENDPOINT: ${VPS0_PANGOLIN_ENDPOINT}
      NEWT_ID: ${RACK4_DOCKER_NEWT_ID}
      NEWT_SECRET: ${RACK4_DOCKER_NEWT_SECRET}
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [newt]
    labels:
      pangolin.public-policies.test.name: test policy
      pangolin.public-policies.test.sso: false
      pangolin.public-policies.test.auto-login-idp: null
      pangolin.public-policies.test.sso-roles:
      pangolin.public-policies.test.sso-users:
      pangolin.public-policies.test.password: null
      pangolin.public-policies.test.pincode: null
      pangolin.public-policies.test.basic-auth: null
      pangolin.public-policies.test.email-whitelist-enabled: false
      pangolin.public-policies.test.whitelist-users:
      pangolin.public-policies.test.apply-rules: true
      pangolin.public-policies.test.rules:

networks:
  newt:
    name: newt
    driver: bridge
    ipam:
      config:
        - subnet: ${NEWT_SUBNET}
          gateway: ${NEWT_GATEWAY}
