---
services:
  newt:
    profiles: [newt]
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      PANGOLIN_ENDPOINT: ${NEWT_PANGOLIN_ENDPOINT}
      NEWT_ID: ${NEWT_ID}
      NEWT_SECRET: ${NEWT_SECRET}
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [newt]

networks:
  newt:
    name: newt
    driver: bridge
    ipam:
      config:
        - subnet: $NEWT_SUBNET
          gateway: $NEWT_GATEWAY
