[rules]
quoted-strings = "disable"
brackets = "enable"
colons = "enable"
commas = "enable"
comments-indentation = "enable"
hyphens = "enable"
new-line-at-end-of-file = "enable"
trailing-spaces = "enable"

[rules.braces]
min-spaces-inside = 0
max-spaces-inside = 1
min-spaces-inside-empty = 0
max-spaces-inside-empty = 0

[rules.comments]
min-spaces-from-content = 1

[rules.new-lines]
type = "unix"

[rules.empty-lines]
max = 2

[rules.indentation]
spaces = 2
indent-sequences = true

[rules.line-length]
max = 240
