[profiles.local.providers.age]
type = "age"
recipients = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDbuPSH93RCTHG7iTHxg+De/yMWUVB+Q4EFt4llpPDL"]

[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
VPS0_IP = { provider = "onepass", value = "op://homelab/vps0/ip" }
