[settings]
env_shell_expand = true

[tools]
gitleaks = "latest"
just = "latest"
pre-commit = "latest"
ruff = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
pkl = "latest"
shfmt = "latest"
shellcheck = "latest"
eza = "latest"
prettier = "latest"
ty = "latest"
hk = "latest"
trufflehog = "latest"

[hooks.enter]
shell = "bash"
script = "mise i -q"

[tasks.pre-commit]
alias = "pc"
run = "hk run pre-commit"

[env]
# note this is the local repo path; clones of repo may have diff locations on remotes
REPO = "{{ config_root | absolute }}"
REPO_NAME = "{{ config_root | basename }}"
HK_MISE = 1
HK_LIBGIT2 = 0
MISE_NPM_BUN = 1

# registries
REGISTRY = "zot.henn.dev"
BERG_USR = "chris"
BERG_BASE_URL = "forgejo.henn.dev"
BERG_SSH_PORT = 2424

# settings for: {virtual IP, keepalived} {traefik, blocky}
DNS_VIP = "192.168.1.3"
DNS_VIP_CIDR = "192.168.1.3/24"
TRAEFIK_VIP = "192.168.1.4"
TRAEFIK_VIP_CIDR = "192.168.1.4/24"
KEEPALIVE_MASTER = "192.168.1.142"
KEEPALIVE_BACKUP = "192.168.1.70"
KEEPALIVE_PASS = "E@!#3f$%"
RACK0_NIC = "nic0"
RACK4_NIC = "enp47s0np0"

# lancache dns
LANCACHE_IP = "192.168.1.143"
LANCACHE_DNS = "192.168.1.143"
