server:
  externalUrl: https://filesq.chenn.dev
  internalUrl: http://filesq:80

  sources:
    - path: /mnt/h
      name: h
      config:
        denyByDefault: false              # deny access unless an "allow" access rule was specifically created.
        private: false                    # designate as source as private -- currently just means no sharing permitted.
        disabled: false                   # disable the source, this is useful so you don't need to remove it from the config file
        rules: # list of item rules to apply to specific paths
          - neverWatchPath: ""            # index the folder in the first pass to get included in search, but never re-indexed.
            includeRootItem: ""           # include only these items at root folder level
            fileStartsWith: ""            # (global) exclude files that start with these prefixes. Eg. "archive-" or "backup-"
            folderStartsWith: ""          # (global) exclude folders that start with these prefixes. Eg. "archive-" or "backup-"
            fileEndsWith: ""              # (global) exclude files that end with these suffixes. Eg. ".jpg" or ".txt"
            folderEndsWith: ""            # (global) exclude folders that end with these suffixes. Eg. ".thumbnails" or ".git"
            folderPath: ""                # (global) exclude folders that match this path. Eg. "/path/to/folder" or "/path/to/folder/subfolder"
            filePath: ""                  # (global) exclude files that match this path. Eg. "/path/to/file.txt" or "/path/to/file.txt/subfile.txt"
            fileName: ""                  # (global) exclude files that match these names. Eg. "file.txt" or "test.csv"
            folderName: ""                # (global) exclude folders that match these names. Eg. "folder" or "subfolder"
            viewable: false               # Enable viewing in UI but exclude from indexing
            ignoreHidden: false           # Excludes only hidden files and folders
            ignoreZeroSizeFolders: false  # Excludes only folders with 0 size
            ignoreSymlinks: false         # Excludes symbolic links
        defaultUserScope: "/"             # defaults to root of index "/" should match folders under path
        defaultEnabled: true              # should be added as a default source for new users?
        useLogicalSize: false

integrations:
  office:
    url: https://office.chenn.dev
    internalUrl: http://filesq_onlyoffice:80

auth:
  methods:
    oidc:
      enabled: true
      issuerUrl: https://pocketid.chenn.dev
      scopes: email openid profile groups
      userIdentifier: preferred_username