frontend:
  name: "FileBrowser Quantum: Chicken"
  description: A file server for the Dancing Chicken

server:
  externalUrl: https://filesq.chenn.dev
  internalUrl: http://filesq:80

  sources:
    - path: /mnt/h
      name: h
      config:
        denyByDefault: false
        private: false
        disabled: false
        rules:
          - neverWatchPath: ""
            includeRootItem: ""
            fileStartsWith: ""
            folderStartsWith: ""
            fileEndsWith: ""
            folderEndsWith: ""
            folderPath: ""
            filePath: ""
            fileName: ""
            folderName: ""
            viewable: false
            ignoreHidden: false
            ignoreZeroSizeFolders: false
            ignoreSymlinks: false
        defaultUserScope: "/"
        defaultEnabled: true
        useLogicalSize: false

integrations:
  office:
    url: https://office.chenn.dev
    internalUrl: http://filesq_onlyoffice:80

auth:
  adminUsername: chris
  methods:
    oidc:
      enabled: true
      issuerUrl: https://pocketid.chenn.dev
      scopes: email openid profile groups
      userIdentifier: preferred_username
      groupsClaim: groups
      adminGroup: admin
    password:
      enabled: true
      minLength: 5
      signup: true

userDefaults:
  loginMethod: password, oidc
