frontend:
  name: 'Quantum Chicken'
  description: A file server for the Dancing Chicken

server:
  externalUrl: https://files.chenn.dev
  internalUrl: http://files:80

  sources:
    - path: /mnt/q/
      name: q
      config:
        defaultEnabled: true
    - path: /mnt/f/
      name: f
      config:
        defaultEnabled: true
    - path: /mnt/k/
      name: k
      config:
        defaultEnabled: true
    - path: /mnt/h/
      name: h
      config:
        defaultEnabled: true

integrations:
  office:
    url: https://office.chenn.dev
    internalUrl: http://office:80

auth:
  adminUsername: chris
  methods:
    password:
      enabled: false
      minLength: 5
      signup: true
    oidc:
      enabled: true
      issuerUrl: https://pocketid.chenn.dev
      scopes: email openid profile groups
      userIdentifier: preferred_username
      groupsClaim: groups
      adminGroup: admin
      createUser: true

userDefaults:
  loginMethod: oidc
  permissions:
    api: false
    admin: false
    modify: true
    share: true
    realtime: true
    delete: true
    create: true
    download: true
