# sudo chmod -R 777 $DATA/backrest/config/config.json
# pycharm $DATA/backrest/config/config.json
---
services:
  backrest:
    profiles: [backrest]
    image: garethgeorge/backrest:latest
    container_name: backrest
    restart: unless-stopped
    environment:
      # hooks run in the container env; only restic/S3 creds must be passed thru to restic via the UI/cfg file
      TZ: $TZ
      OP_SERVICE_ACCOUNT_TOKEN: ${OP_SERVICE_ACCOUNT_TOKEN}
      AWS_ACCESS_KEY_ID: ${WASABI_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${WASABI_SECRET_KEY}
      RESTIC_PASSWORD: ${WASABI_RESTIC_PASSWORD}
      SCRIPT_GITHUB: |
        . /scripts/deps.sh
        && /scripts/gclone.sh 'chrishenn' 'github.com' "/mnt/h/github/github.com/chrishenn" "$$HOME/.ssh/id_ed25519"
        && chown -R 1000:1000 /mnt/h/github

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA/backrest/data:/data
      - $DATA/backrest/cache:/cache
      - $DATA/backrest/config:/config
      - ./backrest/scripts:/scripts
      - /mnt/k:/mnt/k
      - /mnt/h:/mnt/h
    healthcheck:
      test: ['CMD', 'curl', '-ILfSs', 'http://localhost:9898/']
    networks: [newt]
    labels:
      homepage.group: Backup
      homepage.name: Backrest
      homepage.icon: backrest.png
      homepage.href: https://backrest.chenn.dev
      homepage.description: Backup Automation

      pangolin.public-resources.backrest.name: backrest
      pangolin.public-resources.backrest.full-domain: backrest.chenn.dev
      pangolin.public-resources.backrest.mode: http
      pangolin.public-resources.backrest.targets[0].method: http
      pangolin.public-resources.backrest.targets[0].port: 9898
      pangolin.public-resources.backrest.policy: chris
