---
services:
  rsync:
    profiles: [rsync]
    image: ${REGISTRY}/rsync:latest
    build: ./rsync
    container_name: rsync
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - ~/.docker/config.json:/config.json
      - ./rsync/rsync.sh:/run.sh
      - /mnt/f:/mnt/f
      - /mnt/h:/mnt/h
      - /mnt/k:/mnt/k
      - /mnt/q:/mnt/q
    environment:
      TZ: $TZ
      CRON_SCHEDULE: '0 5 * * *'
      CRON_CMD: '/run.sh'
      RUN_NOW: 1
