[secrets]
CLOUDFLARE_API_TOKEN = { provider = "op", value = "op://homelab/cloudflare/token" }
ZONEID = { provider = "op", value = "op://homelab/cloudflare/zoneid/henndev" }
DOMAIN = { provider = "op", value = "op://homelab/rack4/domain" }
LOCALIP = { provider = "op", value = "op://homelab/rack4/host" }
