# seems amateurish to have a one-time migration container, but the project looks legit otherwise
---
x-affine_env: &affine_env
  REDIS_SERVER_HOST: affine_redis
  DATABASE_URL: postgresql://affine:affine@affine_db:5432/affine
  AFFINE_INDEXER_ENABLED: false
  PORT: 3010
  AFFINE_SERVER_EXTERNAL_URL: https://affine.chenn.dev

  DB_USERNAME: affine
  DB_PASSWORD: affine
  DB_DATABASE: affine

  POSTGRES_USER: affine
  POSTGRES_PASSWORD: affine
  POSTGRES_DB: affine
  POSTGRES_INITDB_ARGS: '--data-checksums'
  POSTGRES_HOST_AUTH_METHOD: trust

  MAILER_HOST: ${SMTP_HOST}
  MAILER_PORT: 465
  MAILER_USER: ${SMTP_USER}
  MAILER_PASSWORD: ${SMTP_TOKEN}
  MAILER_SENDER: ${SMTP_USER}
  MAILER_IGNORE_TLS: false

services:
  affine:
    profiles: [affine]
    image: ghcr.io/toeverything/affine:stable
    container_name: affine
    restart: unless-stopped
    volumes:
      - $DATA/affine/storage:/root/.affine/storage
      - $DATA/affine/config:/root/.affine/config
    environment:
      <<: *affine_env
    networks: [affine, newt]
    labels:
      homepage.group: Project Management
      homepage.name: Affine
      homepage.icon: affine.png
      homepage.href: https://affine.chenn.dev
      homepage.description: Private Wiki

      pangolin.public-resources.affine.name: affine
      pangolin.public-resources.affine.full-domain: affine.chenn.dev
      pangolin.public-resources.affine.mode: http
      pangolin.public-resources.affine.targets[0].method: http
      pangolin.public-resources.affine.targets[0].port: 3010
      pangolin.public-resources.affine.policy: member

  affine_redis:
    profiles: [affine]
    image: valkey/valkey:alpine
    container_name: affine_redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [affine]

  affine_db:
    profiles: [affine]
    image: pgvector/pgvector:pg18
    container_name: affine_db
    restart: unless-stopped
    volumes:
      - $DATA/affine/db:/var/lib/postgresql
    environment:
      <<: *affine_env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [affine]

  affine_migration:
    profiles: [affine]
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_migration
    restart: no
    volumes:
      - $DATA/affine/storage:/root/.affine/storage
      - $DATA/affine/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      <<: *affine_env
    networks: [affine]

networks:
  affine:
