---
x-kaneo_env: &kaneo_env
  KANEO_CLIENT_URL: https://kaneo.chenn.dev
  KANEO_API_URL: https://kaneo-api.chenn.dev
  BETTER_AUTH_SECRET: ${KANEO_SECRET}

  DATABASE_URL: postgresql://kaneo:kaneo@kaneo_db/kaneo
  POSTGRES_DB: kaneo
  POSTGRES_USER: kaneo
  POSTGRES_PASSWORD: kaneo

  DISABLE_REGISTRATION: false
  DISABLE_PASSWORD_REGISTRATION: true
  CUSTOM_OAUTH_AUTO_LOGIN: true
  CUSTOM_OAUTH_DISCOVERY_URL: https://pocketid.chenn.dev/.well-known/openid-configuration
  CUSTOM_OAUTH_CLIENT_ID: ${KANEO_OIDC_CLIENT}
  CUSTOM_OAUTH_CLIENT_SECRET: ${KANEO_OIDC_SECRET}
  CUSTOM_OAUTH_SCOPES: openid,email,profile,groups
  CUSTOM_AUTH_PKCE: true

  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: 465
  SMTP_USER: ${SMTP_USER}
  SMTP_PASSWORD: ${SMTP_TOKEN}
  SMTP_FROM: ${SMTP_USER}
  SMTP_SECURE: true
  SMTP_REQUIRE_TLS: true
  SMTP_IGNORE_TLS: false

services:
  kaneo:
    profiles: [kaneo]
    image: ghcr.io/usekaneo/web:latest
    container_name: kaneo
    restart: unless-stopped
    environment:
      <<: *kaneo_env
    networks: [kaneo, newt]
    labels:
      homepage.group: Project Management
      homepage.name: Kaneo
      homepage.icon: https://raw.githubusercontent.com/usekaneo/kaneo/refs/heads/main/apps/docs/favicon.svg
      homepage.href: https://kaneo.chenn.dev
      homepage.description: Project Coordination

      pangolin.public-resources.kaneo.name: kaneo
      pangolin.public-resources.kaneo.full-domain: kaneo.chenn.dev
      pangolin.public-resources.kaneo.mode: http
      pangolin.public-resources.kaneo.targets[0].method: http
      pangolin.public-resources.kaneo.targets[0].port: 5173
      pangolin.public-resources.kaneo.policy: member

  kaneo_api:
    profiles: [kaneo]
    image: ghcr.io/usekaneo/api:latest
    container_name: kaneo_api
    restart: unless-stopped
    environment:
      <<: *kaneo_env
    networks: [kaneo, newt]
    labels:
      pangolin.public-resources.kaneo_api.name: kaneo_api
      pangolin.public-resources.kaneo_api.full-domain: kaneo-api.chenn.dev
      pangolin.public-resources.kaneo_api.mode: http
      pangolin.public-resources.kaneo_api.targets[0].method: http
      pangolin.public-resources.kaneo_api.targets[0].port: 1337
      pangolin.public-resources.kaneo_api.policy: us

  kaneo_db:
    profiles: [kaneo]
    image: postgres:18-alpine
    container_name: kaneo_db
    restart: unless-stopped
    environment:
      <<: *kaneo_env
    volumes:
      - $DATA/kaneo/db:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaneo -d kaneo']
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [kaneo]

networks:
  kaneo:
