---
services:
  notediscovery:
    profiles: [notediscovery]
    image: ghcr.io/gamosoft/notediscovery:latest
    container_name: notediscovery
    restart: unless-stopped
    volumes:
      - $DATA/notediscovery/data:/app/data
    networks: [newt]
    labels:
      homepage.group: Project Management
      homepage.name: notediscovery
      homepage.icon: notediscovery.png
      homepage.href: https://notediscovery.chenn.dev
      homepage.description: Note Server

      pangolin.public-resources.notediscovery.name: notediscovery
      pangolin.public-resources.notediscovery.full-domain: notediscovery.chenn.dev
      pangolin.public-resources.notediscovery.mode: http
      pangolin.public-resources.notediscovery.targets[0].method: http
      pangolin.public-resources.notediscovery.targets[0].port: 8000
      pangolin.public-resources.notediscovery.policy: member
