# curl -X POST -d '{"urls":"mailto://<gmail-username>:<app password>@gmail.com","body":"test body","title":"test title"}' \
#   -H "Content-Type: application/json" "https://apprise.henn.dev/notify/"
---
services:
  apprise:
    profiles: [apprise]
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # in Mb
      APPRISE_ATTACH_SIZE: 2000000
    volumes:
      - $DATA/apprise/config:/config
      - $DATA/apprise/attachments:/attachments
    networks: [newt]
    labels:
      homepage.group: Notify
      homepage.name: Apprise
      homepage.icon: apprise.png
      homepage.href: https://apprise.chenn.dev
      homepage.description: Notification Server

      pangolin.public-resources.apprise.name: apprise
      pangolin.public-resources.apprise.full-domain: apprise.chenn.dev
      pangolin.public-resources.apprise.protocol: http
      pangolin.public-resources.apprise.ssl: true
      pangolin.public-resources.apprise.targets[0].method: http
      pangolin.public-resources.apprise.targets[0].port: 8000
      pangolin.public-resources.apprise.auth.sso-enabled: true
      pangolin.public-resources.apprise.auth.sso-roles[0]: Member
      pangolin.public-resources.apprise.rules[0].action: pass
      pangolin.public-resources.apprise.rules[0].match: country
      pangolin.public-resources.apprise.rules[0].value: US
      pangolin.public-resources.apprise.rules[1].action: deny
      pangolin.public-resources.apprise.rules[1].match: country
      pangolin.public-resources.apprise.rules[1].value: ALL
