---
configs:
  ntfy:
    content: |
      base-url: https://ntfy.chenn.dev
      listen-http: ':80'
      behind-proxy: true
      proxy-forwarded-header: 'X-Forwarded-For'
      proxy-trusted-hosts: '192.168.100.0/24'
      attachment-cache-dir: /attachments
      attachment-total-size-limit: '1000G'
      attachment-file-size-limit: '10G'
      attachment-expiry-duration: '48h'
      visitor-attachment-total-size-limit: '1000G'
      visitor-attachment-daily-bandwidth-limit: '1000G'
services:
  ntfy:
    profiles: [ntfy]
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    command: serve
    volumes:
      - $DATA/ntfy/data:/var/cache/ntfy
      - $DATA/ntfy/attachments:/attachments
    configs:
      - source: ntfy
        target: /etc/ntfy/server.yml
    environment:
      TZ: $TZ
    healthcheck:
      test: ['CMD-SHELL', "wget -q --tries=1 http://ntfy:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
    networks: [newt]
    labels:
      homepage.group: Notify
      homepage.name: Ntfy
      homepage.icon: ntfy.png
      homepage.href: https://ntfy.chenn.dev
      homepage.description: Notifications Server

      pangolin.public-resources.ntfy.name: ntfy
      pangolin.public-resources.ntfy.full-domain: ntfy.chenn.dev
      pangolin.public-resources.ntfy.protocol: http
      pangolin.public-resources.ntfy.ssl: true
      pangolin.public-resources.ntfy.targets[0].method: http
      pangolin.public-resources.ntfy.targets[0].port: 80
      pangolin.public-resources.ntfy.auth.sso-enabled: true
      pangolin.public-resources.ntfy.auth.sso-roles[0]: Member
      pangolin.public-resources.ntfy.rules[0].action: pass
      pangolin.public-resources.ntfy.rules[0].match: country
      pangolin.public-resources.ntfy.rules[0].value: US
      pangolin.public-resources.ntfy.rules[1].action: deny
      pangolin.public-resources.ntfy.rules[1].match: country
      pangolin.public-resources.ntfy.rules[1].value: ALL
