include:
  - apps/ai/comfy.yml
  - apps/ai/kestra.yml
  - apps/ai/ldr.yml
  - apps/ai/n8n.yml
  - apps/ai/ollama.yml
  - apps/ai/openwebui.yml
  - apps/ai/perplexica.yml
  - apps/ai/searx.yml
  - apps/ai/speach.yml

  - apps/backup/backrest.yml
  - apps/backup/rsync.yml
  - apps/backup/pluton.yml
  - apps/backup/repliqate.yml
  - apps/backup/zerobyte.yml

  - apps/converters/convertx.yml
  - apps/converters/omni.yml
  - apps/converters/transmute.yml
  - apps/converters/vert.yml
  - apps/converters/handbrake.yml
  - apps/converters/simg.yml
  - apps/converters/8mb.yml

  - apps/dev/bytestash.yml
  - apps/dev/chartdb.yml
  - apps/dev/code.yml
  - apps/dev/cyberchef.yml
  - apps/dev/dumb.yml
  - apps/dev/excalidraw.yml
  - apps/dev/focalboard.yml
  - apps/dev/forgejo.yml
  - apps/dev/gist.yml
  - apps/dev/gitlab.yml
  - apps/dev/ittools.yml
  - apps/dev/pgadmin.yml
  - apps/dev/databasus.yml
  - apps/dev/onedev.yml
  - apps/dev/portabase.yml
  - apps/dev/penpot.yml
  - apps/dev/scanopy.yml

  - apps/document/docmost.yml
  - apps/document/documenso.yml
  - apps/document/filebrowser.yml
  - apps/document/hedge.yml
  - apps/document/openresume.yml
  - apps/document/pairdrop.yml
  - apps/document/paperless.yml
  - apps/document/resume.yml
  - apps/document/stirling.yml
  - apps/document/cloudreve.yml
  - apps/document/oxicloud.yml
  - apps/document/bento.yml
  - apps/document/etherpad.yml

  - apps/games/wordle.yml

  - apps/infra/apprise.yml
  - apps/infra/aptcache.yml
  - apps/infra/arcane.yml
  - apps/infra/beszel.yml
  - apps/infra/blocky.yml
  - apps/infra/blocky_k.yml
  - apps/infra/dozzle.yml
  - apps/infra/gocron.yml
  - apps/infra/gotify.yml
  - apps/infra/homepage.yml
  - apps/infra/kuma.yml
  - apps/infra/lancache.yml
  - apps/infra/librespeed.yml
  - apps/infra/netboot.yml
  - apps/infra/newt.yml
  - apps/infra/nexterm.yml
  - apps/infra/ntfy.yml
  - apps/infra/openspeedtest.yml
  - apps/infra/pocketid.yml
  - apps/infra/termix.yml
  - apps/infra/traefik.yml
  - apps/infra/traefik_k.yml
  - apps/infra/warden.yml
  - apps/infra/registry.yml
  - apps/infra/dockscope.yml

  - apps/media/arr.yml
  - apps/media/audiobookshelf.yml
  - apps/media/calibre.yml
  - apps/media/dawarich.yml
  - apps/media/immich.yml
  - apps/media/jellyfin.yml
  - apps/media/metube.yml
  - apps/media/navidrome.yml
  - apps/media/download.yml
  - apps/media/tracearr.yml
  - apps/media/foldergram.yml
  - apps/media/cinephage.yml
  - apps/media/readmeabook.yml

  - apps/tools/actual.yml
  - apps/tools/airtrail.yml
  - apps/tools/fileflow.yml
  - apps/tools/karakeep.yml
  - apps/tools/linkding.yml
  - apps/tools/linkstack.yml
  - apps/tools/littlelink.yml
  - apps/tools/matrix.yml
  - apps/tools/memos.yml
  - apps/tools/miro.yml
  - apps/tools/owncast.yml
  - apps/tools/planka.yml
  - apps/tools/rally.yml
  - apps/tools/tududi.yml
  - apps/tools/vikunja.yml
  - apps/tools/zulip.yml
  - apps/tools/omnisearch.yml
  - apps/tools/ops.yml
  - apps/tools/affine.yml
  - apps/tools/ideon.yml
  - apps/tools/keeper.yml
  - apps/tools/notediscovery.yml
  - apps/tools/moocup.yml
  - apps/tools/sure.yml
  - apps/tools/opencut.yml
