include:
  - apps/ai/comfy.yml
  - apps/ai/ollama.yml
  - apps/ai/openwebui.yml
  - apps/ai/speach.yml

  - apps/arr/arr.yml
  - apps/arr/cinephage.yml
  - apps/arr/doplarr.yml
  - apps/arr/muxarr.yml
  - apps/arr/recyclarr.yml
  - apps/arr/seerr.yml
  - apps/arr/solverr.yml
  - apps/arr/tracearr.yml
  - apps/arr/transcodarr.yml

  - apps/backup/backrest.yml
  - apps/backup/databasus.yml
  - apps/backup/pluton.yml
  - apps/backup/portabase.yml
  - apps/backup/repliqate.yml
  - apps/backup/rsync.yml
  - apps/backup/zerobyte.yml
  - apps/backup/duplicati.yml

  - apps/books/audiobookshelf.yml
  - apps/books/calibre.yml
  - apps/books/grimmory.yml
  - apps/books/kavita.yml
  - apps/books/listenarr.yml
  - apps/books/readmeabook.yml

  - apps/converters/8mb.yml
  - apps/converters/convertx.yml
  - apps/converters/handbrake.yml
  - apps/converters/mazanoke.yml
  - apps/converters/omni.yml
  - apps/converters/snapotter.yml
  - apps/converters/transmute.yml
  - apps/converters/vert.yml

  - apps/dev/chartdb.yml
  - apps/dev/cyberchef.yml
  - apps/dev/excalidraw.yml
  - apps/dev/ittools.yml
  - apps/dev/pgadmin.yml
  - apps/dev/scanopy.yml
  - apps/dev/bytestash.yml

  - apps/doc_server/docmost.yml
  - apps/doc_server/files.yml
  - apps/doc_server/hedge.yml
  - apps/doc_server/paperless.yml
  - apps/doc_server/papra.yml
  - apps/doc_server/syncin.yml
  - apps/doc_server/syncthing.yml
  - apps/doc_server/zipline.yml

  - apps/download/qbit.yml
  - apps/download/sab.yml

  #  - apps/games/cs2.yml
  #  - apps/games/csgo.yml
  - apps/games/wordle.yml

  - apps/infra/autoheal.yml
  - apps/infra/blocky.yml
  - apps/infra/blocky_k.yml
  - apps/infra/homepage.yml
  - apps/infra/lancache.yml
  - apps/infra/netboot.yml
  - apps/infra/newt.yml
  - apps/infra/pocketid.yml
  - apps/infra/traefik.yml
  - apps/infra/traefik_k.yml
  - apps/infra/stalwart.yml

  - apps/job/openresume.yml
  - apps/job/resume.yml
  - apps/job/ops.yml

  - apps/media/archive.yml
  - apps/media/jellyfin.yml
  - apps/media/metube.yml
  - apps/media/nodebb.yml
  - apps/media/yamtrack.yml
  - apps/media/ytp.yml
  - apps/media/opencut.yml
  - apps/media/ties.yml

  - apps/monitoring/arcane.yml
  - apps/monitoring/beszel.yml
  - apps/monitoring/dozzle.yml
  - apps/monitoring/kuma.yml
  - apps/monitoring/peekaping.yml
  - apps/monitoring/termix.yml
  - apps/monitoring/dockscope.yml

  - apps/music/aurral.yml
  - apps/music/lidarr.yml
  - apps/music/mdrm.yml
  - apps/music/mseerr.yml
  - apps/music/navidrome.yml

  - apps/notify/apprise.yml
  - apps/notify/gotify.yml
  - apps/notify/ntfy.yml

  - apps/pdf/bento.yml
  - apps/pdf/documenso.yml
  - apps/pdf/overleaf.yml
  - apps/pdf/pdfding.yml
  - apps/pdf/stirling.yml

  - apps/photos/dawarich.yml
  - apps/photos/foldergram.yml
  - apps/photos/immich.yml

  - apps/project/affine.yml
  - apps/project/ideon.yml
  - apps/project/kaneo.yml
  - apps/project/karakeep.yml
  - apps/project/keeper.yml
  - apps/project/memos.yml
  - apps/project/notediscovery.yml
  - apps/project/planka.yml
  - apps/project/tududi.yml
  - apps/project/vikunja.yml
  - apps/project/wikigo.yml
  - apps/project/wikijs.yml
  - apps/project/penpot.yml
  - apps/project/plane.yml

  # code forge, artifact registry, artifact cache
  - apps/registry/aptcache.yml
  #  - apps/registry/gitlab.yml
  - apps/registry/forgejo.yml
  - apps/registry/mirrors.yml
  #  - apps/registry/onedev.yml
  - apps/registry/zot.yml

  - apps/search/omnisearch.yml
  - apps/search/searx.yml

  - apps/tools/airtrail.yml
  - apps/tools/dumb.yml
  - apps/tools/fileflow.yml
  - apps/tools/gocron.yml
  - apps/tools/linkding.yml
  - apps/tools/matrix.yml
  - apps/tools/miro.yml
  - apps/tools/moocup.yml
  - apps/tools/n8n.yml
  - apps/tools/openspeedtest.yml
  - apps/tools/owncast.yml
  - apps/tools/rally.yml
  - apps/tools/sure.yml
  - apps/tools/warden.yml
  - apps/tools/kestra.yml
  - apps/tools/shlink.yml
