include:
  - apps/ai/comfy.yml
  - apps/ai/ollama.yml
  - apps/ai/openwebui.yml
  - apps/ai/speach.yml
  - apps/ai/translate.yml

  - apps/backup/backrest.yml
  - apps/backup/borg.yml
  - apps/backup/borgui.yml
  - apps/backup/databasus.yml
  - apps/backup/duplicati.yml
  - apps/backup/pluton.yml
  - apps/backup/portabase.yml
  - apps/backup/rsync.yml
  - apps/backup/zerobyte.yml
  #  - apps/backup/repliqate.yml

  - apps/book/audiobookshelf.yml
  - apps/book/bookorbit.yml
  - apps/book/calibre.yml
  - apps/book/grimmory.yml
  - apps/book/kavita.yml
  - apps/book/listenarr.yml
  - apps/book/readmeabook.yml

  - apps/converter/8mb.yml
  - apps/converter/convertx.yml
  - apps/converter/handbrake.yml
  - apps/converter/mazanoke.yml
  - apps/converter/omni.yml
  - apps/converter/snapotter.yml
  - apps/converter/transmute.yml
  - apps/converter/vert.yml

  - apps/dev/bytestash.yml
  - apps/dev/chartdb.yml
  - apps/dev/cyberchef.yml
  - apps/dev/dagu.yml
  - apps/dev/excalidraw.yml
  - apps/dev/gocron.yml
  - apps/dev/infisical.yml
  - apps/dev/ittools.yml
  - apps/dev/pgadmin.yml
  - apps/dev/scanopy.yml
  - apps/dev/ghstat.yml

  - apps/dev_project/affine.yml
  - apps/dev_project/appflowy.yml
  - apps/dev_project/colanode.yml
  - apps/dev_project/ideon.yml
  - apps/dev_project/kan.yml
  - apps/dev_project/kaneo.yml
  - apps/dev_project/karakeep.yml
  - apps/dev_project/keeper.yml
  - apps/dev_project/memos.yml
  - apps/dev_project/notediscovery.yml
  - apps/dev_project/outline.yml
  - apps/dev_project/plane.yml
  - apps/dev_project/planka.yml
  - apps/dev_project/tududi.yml
  - apps/dev_project/vikunja.yml
  - apps/dev_project/wikigo.yml
  - apps/dev_project/wikijs.yml
  #  - apps/dev_project/penpot.yml

  - apps/dev_slack/mattermost.yml
  #  - apps/dev_slack/campfire.yml
  #  - apps/dev_slack/zulip.yml

  - apps/discord/chatto.yml
  - apps/discord/miro.yml
  - apps/discord/owncast.yml
  #  - apps/discord/fluxer.yml
  #  - apps/discord/stoat.yml
  #  - apps/discord/vocechat.yml

  - apps/doc_server/docmost.yml
  - apps/doc_server/files.yml
  - apps/doc_server/hoodik.yml
  - apps/doc_server/oxicloud.yml
  - apps/doc_server/paperless.yml
  - apps/doc_server/papra.yml
  - apps/doc_server/syncin.yml
  - apps/doc_server/syncthing.yml
  - apps/doc_server/zipline.yml

  - apps/download/byparr.yml
  - apps/download/qbit.yml
  - apps/download/sab.yml
  - apps/download/solverr.yml

  - apps/email/mailflow.yml
  - apps/email/stalwart.yml

  - apps/game/wordle.yml
  #  - apps/game/cs2.yml
  #  - apps/game/csgo.yml

  - apps/infra/blocky.yml
  - apps/infra/blocky_k.yml
  - apps/infra/homepage.yml
  - apps/infra/lancache.yml
  - apps/infra/netboot.yml
  - apps/infra/newt.yml
  - apps/infra/pocketid.yml
  - apps/infra/traefik.yml
  - apps/infra/traefik_k.yml
  #  - apps/infra/watchtower.yml

  - apps/job/openresume.yml
  - apps/job/ops.yml
  - apps/job/resume.yml

  - apps/media/archive.yml
  - apps/media/ghost.yml
  - apps/media/metube.yml
  - apps/media/minuspod.yml
  - apps/media/nodebb.yml
  - apps/media/opencut.yml
  - apps/media/reitti.yml
  - apps/media/ties.yml
  - apps/media/ytp.yml

  - apps/monitor/arcane.yml
  - apps/monitor/beszel.yml
  - apps/monitor/dockscope.yml
  - apps/monitor/dozzle.yml
  - apps/monitor/kuma.yml
  - apps/monitor/peekaping.yml
  - apps/monitor/termix.yml

  - apps/movie/arr.yml
  - apps/movie/cinephage.yml
  - apps/movie/doplarr.yml
  - apps/movie/jellyfin.yml
  - apps/movie/jellyglance.yml
  - apps/movie/muxarr.yml
  - apps/movie/mydia.yml
  - apps/movie/recyclarr.yml
  - apps/movie/seerr.yml
  - apps/movie/tracearr.yml
  - apps/movie/transcodarr.yml
  - apps/movie/yamtrack.yml

  - apps/music/aurral.yml
  - apps/music/feishin.yml
  - apps/music/lidarr.yml
  - apps/music/mdrm.yml
  - apps/music/meelo.yml
  - apps/music/mseerr.yml
  - apps/music/navidrome.yml

  - apps/notify/apprise.yml
  - apps/notify/gotify.yml
  - apps/notify/ntfy.yml

  - apps/pdf/bento.yml
  - apps/pdf/documenso.yml
  - apps/pdf/overleaf.yml
  - apps/pdf/pdfding.yml
  - apps/pdf/stirling.yml

  - apps/photo/dawarich.yml
  - apps/photo/foldergram.yml
  - apps/photo/immich.yml
  - apps/photo/moocup.yml

  - apps/registry/aptcache.yml
  - apps/registry/forgejo.yml
  - apps/registry/mirrors.yml
  - apps/registry/zot.yml
  #  - apps/registry/gitlab.yml
  #  - apps/registry/onedev.yml

  - apps/search/omnisearch.yml
  - apps/search/searx.yml

  - apps/tool/airtrail.yml
  - apps/tool/dumb.yml
  - apps/tool/fileflow.yml
  - apps/tool/linkbreeze.yml
  - apps/tool/linkding.yml
  - apps/tool/n8n.yml
  - apps/tool/openspeedtest.yml
  - apps/tool/13foot.yml
  - apps/tool/netbox.yml
  - apps/tool/rally.yml
  - apps/tool/sure.yml
  - apps/tool/warden.yml
#  - apps/tool/kestra.yml
#  - apps/tool/shlink.yml
