set fallback
alias a := attach
alias b := bounce
alias f := follow
alias s := sync
alias p := ps
alias u := up
alias d := down
profile := "'*'"

# machine-specific

# 'repo' is the repo location on the remote host
repo := "/var/home/chris/Projects/homelab"

[arg("pty", long="pty", short="p")]
ssh cmd='' pty='true':
    just rack4 {{ if cmd != '' {f'"{{cmd}}"'} else {''} }} -p={{pty}}

# compose operations over {profiles, svcs}

up profile=profile *svcs:
    docker compose --profile {{ profile }} up -d --remove-orphans {{ svcs }}

pullup profile=profile *svcs:
    docker compose --profile {{ profile }} up -d --remove-orphans --force-recreate --pull always {{ svcs }}

down profile=profile *svcs:
    docker compose --profile {{ profile }} down {{ svcs }}

bounce profile=profile *svcs:
    #!/bin/bash
    docker compose --profile {{ profile }} down {{ svcs }} && \
    docker compose --profile {{ profile }} up -d --remove-orphans {{ svcs }}

pb profile=profile *svcs:
    #!/bin/bash
    docker compose --profile {{ profile }} down {{ svcs }} && \
    docker compose --profile {{ profile }} up -d --remove-orphans --force-recreate --pull always {{ svcs }}

build *svcs:
    docker compose build --push {{ svcs }}

run *svcs:
    docker compose run --rm -it {{ svcs }}

log *args:
    docker compose logs {{ args }}

follow *args:
    just log -f {{ args }}

attach svc cmd="/bin/sh":
    docker compose exec -it {{ svc }} {{ cmd }}

ps *svcs:
    docker compose ps {{ svcs }}

watch:
    watch -n 1 "docker compose ps"

bbounce *svcs:
    #!/bin/bash
    docker compose down {{ svcs }} \
    && docker compose build --push {{ svcs }} \
    && docker compose up -d --remove-orphans --pull always {{ svcs }}

pbounce profile=profile *svcs:
    #!/bin/bash
    docker compose pull && \
    just bounce "{{ profile }}" {{ svcs }}

# logins, keys, helpers

keys:
    echo "$(op read 'op://homelab/dkey/public key')" | just ssh 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys' -p=false

login_docker:
    echo $DOCKERHUB_PASS | docker login docker.io -u $DOCKERHUB_USER --password-stdin

login_registry:
    echo $PASS | docker login ${REGISTRY} -u $USER --password-stdin

rlogin:
    #!/bin/bash
    just ssh 'echo $PASS | docker login ${REGISTRY} -u $USER --password-stdin'
    just ssh 'echo $DOCKERHUB_PASS | docker login docker.io -u $DOCKERHUB_USER --password-stdin'

sync message="sync":
    git commit -a -m '{{ message }}' || true && git pull && git push
    just ssh 'cd {{ repo }} && git commit -a -m '{{ message }}' || true && git pull && git push'

rsync message="sync":
    just ssh 'cd {{ repo }} && git commit -a -m '{{ message }}' || true && git pull && git push'
    git commit -a -m "{{ message }}" || true && git pull && git push

# sync secrets from fnox.toml (1password provider) to fnox.local.toml (age provider)
ssync:
    fnox sync --provider age --config fnox.local.toml -f

reset:
    just ssh 'cd {{repo}} && git fetch origin && git reset --hard origin/main'

# service-specific recipes

sync_dns:
    just sync
    just bounce core blocky

sync_traefik:
    just sync
    just bounce core traefik

sync_recyclarr:
    just sync
    just bounce media recyclarr
    docker compose exec recyclarr recyclarr sync

now_backups *svcs:
    #!/bin/bash
    SYNC_MODE=now just bbounce bkp {{ svcs }}

now_rebuild:
    #!/bin/bash
    SYNC_MODE=now just bbounce core rebuild

# for reference. unused right now
git_sync:
    git remote set-head origin -a
    branch="$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')"
    git fetch origin $branch && git reset --hard FETCH_HEAD

wasabi_add:
    mc alias set wasabi $WASABI_URL $WASABI_ACCESS_KEY $WASABI_SECRET_KEY

wasabi:
    mc du wasabi

stoat_invite:
    #!/bin/bash
    export invite=$(openssl rand -hex 32)
    docker compose exec -it stoat_db mongosh revolt --eval "db.invites.insertOne({ _id: \"$invite\" })"
