# restrictive oidc setup means only one url for now
---
services:
  kavita:
    profiles: [kavita]
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DATA/kavita/config:/config
      - $DATA/kavita/data:/data
      - $MEDIA/Books:/media
    networks: [newt]
    labels:
      homepage.group: Books
      homepage.name: Kavita
      homepage.icon: kavita.png
      homepage.href: https://kavita.chenn.dev
      homepage.description: Book Server

      pangolin.public-resources.kavita.name: kavita
      pangolin.public-resources.kavita.full-domain: kavita.chenn.dev
      pangolin.public-resources.kavita.mode: http
      pangolin.public-resources.kavita.targets[0].method: http
      pangolin.public-resources.kavita.targets[0].port: 5000
      pangolin.public-resources.kavita.policy: member
