---
services:
  openresume:
    profiles: [openresume]
    image: ${REGISTRY}/openresume:latest
    build: https://github.com/xitanggg/open-resume.git
    container_name: openresume
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Job
      homepage.name: openresume
      homepage.icon: open-resume.png
      homepage.href: https://openresume.chenn.dev
      homepage.description: Resume Generator

      pangolin.public-resources.openresume.name: openresume
      pangolin.public-resources.openresume.full-domain: openresume.chenn.dev
      pangolin.public-resources.openresume.mode: http
      pangolin.public-resources.openresume.targets[0].method: http
      pangolin.public-resources.openresume.targets[0].port: 3000
      pangolin.public-resources.openresume.policy: member
