[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
pass = { provider = "onepass", value = "op://homelab/vps0/chris_pass_env" }

CLOUDFLARE_API_TOKEN = { provider = "onepass", value = "op://homelab/cloudflare/token" }

SERVER_SECRET = { provider = "onepass", value = "op://homelab/vps0/pangolin_server_secret" }
EMAIL_SMTP_PASS = { provider = "onepass", value = "op://homelab/proton/SMTP/smtp_token" }

VPS0_BESZEL_KEY = { provider = "onepass", value = "op://homelab/vps0/beszel_key" }
VPS0_BESZEL_TOKEN = { provider = "onepass", value = "op://homelab/vps0/beszel_token" }
VPS0_BESZEL_HUB_URL = { provider = "onepass", value = "op://homelab/vps0/beszel_hub_url" }
