[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
VPS0_IP = { provider = "onepass", value = "op://homelab/vps0/ip" }

CLOUDFLARE_API_TOKEN = { provider = "onepass", value = "op://homelab/cloudflare/token" }
ZONEID = { provider = "onepass", value = "op://homelab/cloudflare/zoneid/chenndev" }

VPS0_BESZEL_KEY = { provider = "onepass", value = "op://homelab/vps0/beszel_key" }
VPS0_BESZEL_TOKEN = { provider = "onepass", value = "op://homelab/vps0/beszel_token" }
VPS0_BESZEL_HUB_URL = { provider = "onepass", value = "op://homelab/vps0/beszel_hub_url" }
