newtInstances:
  - name: rack3
    enabled: true
    #    auth:
    #      existingSecretName: newt-cred
    #      keys:
    #        endpointKey: PANGOLIN_ENDPOINT
    #        idKey: NEWT_ID
    #        secretKey: NEWT_SECRET
    dockerSocket:
      enabled: true
      path: '/var/run/containerd/containerd.sock'
    configPersistence:
      enabled: true
      mountPath: '/var/lib/newt'
      fileName: 'config.json'
      type: persistentVolumeClaim
