---
services:
  radarr:
    profiles: [arr]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      RADARR__AUTH__METHOD: External
    volumes:
      - $DATA/radarr:/config
      - $DATA/sab/downloads:/sab/downloads
      - $DATA/qbit/downloads:/qbit/downloads
      - $MEDIA:/media_library
    networks: [arr, newt]
    labels:
      homepage.group: Media
      homepage.name: Radarr
      homepage.icon: radarr.png
      homepage.href: https://radarr.chenn.dev
      homepage.description: Movies

      pangolin.public-resources.radarr.name: radarr
      pangolin.public-resources.radarr.full-domain: radarr.chenn.dev
      pangolin.public-resources.radarr.protocol: http
      pangolin.public-resources.radarr.ssl: true
      pangolin.public-resources.radarr.targets[0].method: http
      pangolin.public-resources.radarr.targets[0].port: 7878
      pangolin.public-resources.radarr.auth.sso-enabled: true
      pangolin.public-resources.radarr.auth.sso-roles[0]: Member
      pangolin.public-resources.radarr.auth.basic-auth.user: ${ARR_PANGOLIN_AUTH_USER}
      pangolin.public-resources.radarr.auth.basic-auth.password: ${ARR_PANGOLIN_AUTH_PASS}
      pangolin.public-resources.radarr.rules[0].action: allow
      pangolin.public-resources.radarr.rules[0].match: path
      pangolin.public-resources.radarr.rules[0].value: /api/*
      pangolin.public-resources.radarr.rules[1].action: pass
      pangolin.public-resources.radarr.rules[1].match: country
      pangolin.public-resources.radarr.rules[1].value: US
      pangolin.public-resources.radarr.rules[2].action: deny
      pangolin.public-resources.radarr.rules[2].match: country
      pangolin.public-resources.radarr.rules[2].value: ALL

  sonarr:
    # ghost redownloads of failed dl's I think were a retry from sab. Try purging sab's dl history, including faileds
    # they then became 'orphaned jobs' which sab prompted me to delete
    profiles: [arr]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SONARR__AUTH__METHOD: External
    volumes:
      - $DATA/sonarr:/config
      - $DATA/sab/downloads:/sab/downloads
      - $DATA/qbit/downloads:/qbit/downloads
      - $MEDIA:/media_library
    networks: [arr, newt]
    labels:
      homepage.group: Media
      homepage.name: Sonarr
      homepage.icon: sonarr.png
      homepage.href: https://sonarr.chenn.dev
      homepage.description: TV

      pangolin.public-resources.sonarr.name: sonarr
      pangolin.public-resources.sonarr.full-domain: sonarr.chenn.dev
      pangolin.public-resources.sonarr.protocol: http
      pangolin.public-resources.sonarr.ssl: true
      pangolin.public-resources.sonarr.targets[0].method: http
      pangolin.public-resources.sonarr.targets[0].port: 8989
      pangolin.public-resources.sonarr.auth.sso-enabled: true
      pangolin.public-resources.sonarr.auth.sso-roles[0]: Member
      pangolin.public-resources.sonarr.auth.basic-auth.user: ${ARR_PANGOLIN_AUTH_USER}
      pangolin.public-resources.sonarr.auth.basic-auth.password: ${ARR_PANGOLIN_AUTH_PASS}
      pangolin.public-resources.sonarr.rules[0].action: allow
      pangolin.public-resources.sonarr.rules[0].match: path
      pangolin.public-resources.sonarr.rules[0].value: /api/*
      pangolin.public-resources.sonarr.rules[1].action: pass
      pangolin.public-resources.sonarr.rules[1].match: country
      pangolin.public-resources.sonarr.rules[1].value: US
      pangolin.public-resources.sonarr.rules[2].action: deny
      pangolin.public-resources.sonarr.rules[2].match: country
      pangolin.public-resources.sonarr.rules[2].value: ALL

  lidarr:
    profiles: [arr]
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LIDARR__AUTH__METHOD: External
    volumes:
      - $DATA/lidarr:/config
      - $DATA/sab/downloads:/sab/downloads
      - $DATA/qbit/downloads:/qbit/downloads
      - $MEDIA:/media_library
    networks: [arr, newt]
    labels:
      homepage.group: Media
      homepage.name: Lidarr
      homepage.icon: lidarr.png
      homepage.href: https://lidarr.chenn.dev
      homepage.description: Music Manager

      pangolin.public-resources.lidarr.name: lidarr
      pangolin.public-resources.lidarr.full-domain: lidarr.chenn.dev
      pangolin.public-resources.lidarr.protocol: http
      pangolin.public-resources.lidarr.ssl: true
      pangolin.public-resources.lidarr.targets[0].method: http
      pangolin.public-resources.lidarr.targets[0].port: 8686
      pangolin.public-resources.lidarr.auth.sso-enabled: true
      pangolin.public-resources.lidarr.auth.sso-roles[0]: Member
      pangolin.public-resources.lidarr.auth.basic-auth.user: ${ARR_PANGOLIN_AUTH_USER}
      pangolin.public-resources.lidarr.auth.basic-auth.password: ${ARR_PANGOLIN_AUTH_PASS}
      pangolin.public-resources.lidarr.rules[0].action: allow
      pangolin.public-resources.lidarr.rules[0].match: path
      pangolin.public-resources.lidarr.rules[0].value: /api/*
      pangolin.public-resources.lidarr.rules[1].action: pass
      pangolin.public-resources.lidarr.rules[1].match: country
      pangolin.public-resources.lidarr.rules[1].value: US
      pangolin.public-resources.lidarr.rules[2].action: deny
      pangolin.public-resources.lidarr.rules[2].match: country
      pangolin.public-resources.lidarr.rules[2].value: ALL

  prowlarr:
    profiles: [arr]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - $DATA/prowlarr:/config
    networks: [arr, newt, traefik]
    labels:
      homepage.group: Media
      homepage.name: Prowlarr
      homepage.icon: prowlarr.png
      homepage.href: https://prowlarr.chenn.dev
      homepage.description: Indexer Manager

      # NZB360 apparently can't handle basic auth headers, even though they're in the settings
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.henn.dev`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.middlewares: hdrs@file
      traefik.http.routers.prowlarr.tls.certresolver: cf
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696

      pangolin.public-resources.prowlarr.name: prowlarr
      pangolin.public-resources.prowlarr.full-domain: prowlarr.chenn.dev
      pangolin.public-resources.prowlarr.protocol: http
      pangolin.public-resources.prowlarr.ssl: true
      pangolin.public-resources.prowlarr.targets[0].method: http
      pangolin.public-resources.prowlarr.targets[0].port: 9696
      pangolin.public-resources.prowlarr.auth.sso-enabled: true
      pangolin.public-resources.prowlarr.auth.sso-roles[0]: Member
      pangolin.public-resources.prowlarr.auth.basic-auth.user: ${ARR_PANGOLIN_AUTH_USER}
      pangolin.public-resources.prowlarr.auth.basic-auth.password: ${ARR_PANGOLIN_AUTH_PASS}
      pangolin.public-resources.prowlarr.rules[0].action: allow
      pangolin.public-resources.prowlarr.rules[0].match: path
      pangolin.public-resources.prowlarr.rules[0].value: /api/*
      pangolin.public-resources.prowlarr.rules[1].action: pass
      pangolin.public-resources.prowlarr.rules[1].match: country
      pangolin.public-resources.prowlarr.rules[1].value: US
      pangolin.public-resources.prowlarr.rules[2].action: deny
      pangolin.public-resources.prowlarr.rules[2].match: country
      pangolin.public-resources.prowlarr.rules[2].value: ALL

  bazarr:
    profiles: [arr]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DATA/bazarr:/config
      - $MEDIA:/media_library
    networks: [arr, newt]
    labels:
      homepage.group: Media
      homepage.name: Bazarr
      homepage.icon: bazarr.png
      homepage.href: https://bazarr.chenn.dev
      homepage.description: Subtitle Manager

      pangolin.public-resources.bazarr.name: bazarr
      pangolin.public-resources.bazarr.full-domain: bazarr.chenn.dev
      pangolin.public-resources.bazarr.protocol: http
      pangolin.public-resources.bazarr.ssl: true
      pangolin.public-resources.bazarr.targets[0].method: http
      pangolin.public-resources.bazarr.targets[0].port: 6767
      pangolin.public-resources.bazarr.auth.sso-enabled: true
      pangolin.public-resources.bazarr.auth.sso-roles[0]: Member
      pangolin.public-resources.bazarr.auth.basic-auth.user: ${ARR_PANGOLIN_AUTH_USER}
      pangolin.public-resources.bazarr.auth.basic-auth.password: ${ARR_PANGOLIN_AUTH_PASS}
      pangolin.public-resources.bazarr.rules[0].action: allow
      pangolin.public-resources.bazarr.rules[0].match: path
      pangolin.public-resources.bazarr.rules[0].value: /api/*
      pangolin.public-resources.bazarr.rules[1].action: pass
      pangolin.public-resources.bazarr.rules[1].match: country
      pangolin.public-resources.bazarr.rules[1].value: US
      pangolin.public-resources.bazarr.rules[2].action: deny
      pangolin.public-resources.bazarr.rules[2].match: country
      pangolin.public-resources.bazarr.rules[2].value: ALL



networks:
  arr:
