# mkdir -p $DATA/recyclarr
# sudo chown -R 1000:1000 $DATA/recyclarr

# docker compose run --rm recyclarr sync
# docker compose run --rm recyclarr state repair --adopt
---
configs:
  recyclarr:
    content: |
      radarr:
        radarr_main:
          base_url: !env_var RADARR_URL
          api_key: !env_var RADARR_KEY
          delete_old_custom_formats: true

          quality_definition:
            type: movie

          quality_profiles:
            - trash_id: d1d310673359205736b4b84acd5ea8c8  # Remux 2160p (Combined)
              reset_unmatched_scores:
                enabled: true
            - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
              reset_unmatched_scores:
                enabled: true
            - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
              reset_unmatched_scores:
                enabled: true

          custom_format_groups:
            add:
              - trash_id: ff204bbcecdd487d1cefcefdbf0c278d # [Optional] Golden Rule UHD
              - trash_id: f8bf8eab4617f12dfdbd16303d8da245 # [Optional] Golden Rule HD
              - trash_id: a3ac6af01d78e4f21fcb75f601ac96df # [Unwanted] Unwanted Formats
                select:
                  - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
                  - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
                  - f537cf427b64c38c8e36298f657e4828 # Scene
              - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)
              - trash_id: 1616617ab3a14397a2b2321bcbda44d1 # [HDR Formats] DV Boost
              - trash_id: b29413a7487478fe98228ce79e5689e4 # [HDR Formats] HDR10+ Boost
              - trash_id: f993ad37540147e4d00e66503545d81b # [Streaming Services] Anime
              - trash_id: b22449f789b16a4163b59f1b70cbc580 # [Streaming Services] Asian

      sonarr:
        sonarr_main:
          base_url: !env_var SONARR_URL
          api_key: !env_var SONARR_KEY
          delete_old_custom_formats: true

          quality_definition:
            type: series

          quality_profiles:
            - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
              reset_unmatched_scores:
                enabled: true
            - trash_id: c4cadd6b35b95f62c3d47a408e53e2f7  # WEB-2160p (Combined)
              reset_unmatched_scores:
                enabled: true
            - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
              reset_unmatched_scores:
                enabled: true

          custom_format_groups:
            add:
              - trash_id: e3f37512790f00d0e89e54fe5e790d1c # [Optional] Golden Rule UHD
              - trash_id: 158188097a58d7687dee647e04af0da3 # [Optional] Golden Rule HD
              - trash_id: 85fae4a2294965b75710ef2989c850eb # [Streaming Services] HD/UHD boost
              - trash_id: 59c3af66780d08332fdc64e68297098f # [Unwanted] Unwanted Formats
                select:
                  - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
                  - 06d66ab109d4d2eddb2794d21526d140 # Retags
                  - 1b3994c551cbb92a2c781af061f4ab44 # Scene
              - trash_id: d920fd959d220306888f40b6f38e1578 # [Optional] Season Packs
              - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian

services:
  recyclarr:
    profiles: [recyclarr]
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    user: $PUID:$PGID
    configs:
      - source: recyclarr
        target: /config/recyclarr.yml
    volumes:
      - $DATA/recyclarr:/config
    environment:
      TZ: $TZ
      RECYCLARR_CREATE_CONFIG: true
      RADARR_URL: ${RADARR_URL}
      RADARR_KEY: ${RADARR_KEY}
      SONARR_URL: ${SONARR_URL}
      SONARR_KEY: ${SONARR_KEY}
    networks: [arr]
