# sonarr/radarr media requests
---
services:
  seerr:
    profiles: [arr]
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    environment:
      TZ: $TZ
      LOG_LEVEL: debug
    volumes:
      - $DATA/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
    networks: [arr, newt]
    labels:
      homepage.group: Arr
      homepage.name: Seerr
      homepage.icon: jellyseerr.png
      homepage.href: https://seerr.chenn.dev
      homepage.description: Media Requests

      pangolin.public-resources.seerr.name: seerr
      pangolin.public-resources.seerr.full-domain: seerr.chenn.dev
      pangolin.public-resources.seerr.mode: http
      pangolin.public-resources.seerr.targets[0].method: http
      pangolin.public-resources.seerr.targets[0].port: 5055
      pangolin.public-resources.seerr.policy: arr
