# can't get db permissions to work
---
services:
  netalert:
    profiles: [netalert]
    image: ghcr.io/jokob-sk/netalertx:latest
    container_name: netalert
    restart: unless-stopped
    read_only: true
    cap_drop: [ALL]
    cap_add: [NET_RAW, NET_ADMIN, NET_BIND_SERVICE]
    network_mode: host
    environment:
      PORT: 20211
      GRAPHQL_PORT: 20212
      LISTEN_ADDR: ${SVC_IP}
      TZ: $TZ
    tmpfs:
      - "/tmp:uid=20211,gid=20211,mode=1700,rw,noexec,nosuid,nodev,async,noatime,nodiratime"
    volumes:
      - $DATA/netalert/data:/data
    labels:
      homepage.group: Tools
      homepage.name: NetalertX
      homepage.icon: netalertx.png
      homepage.href: https://netalert.henn.dev
      homepage.description: Network Scanner
