#!/bin/bash

pm uninstall --user 0 android.autoinstalls.config.samsung
pm uninstall --user 0 com.sec.android.app.samsungapps
pm uninstall --user 0 com.osp.app.signin
pm uninstall --user 0 com.samsung.android.app.appsedge
pm uninstall --user 0 com.android.role.notes.enabled
pm uninstall --user 0 com.google.android.apps.accessibility.voiceaccess
pm uninstall --user 0 com.hiya.star
pm uninstall --user 0 com.knox.vpn.proxyhandler
pm uninstall --user 0 com.monotype.android.font.samsungone
pm uninstall --user 0 com.samsung.aasaservice
pm uninstall --user 0 com.samsung.android.accessibility.talkback
pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
pm uninstall --user 0 com.samsung.android.app.clipboardedge
pm uninstall --user 0 com.samsung.android.app.cocktailbarservice
pm uninstall --user 0 com.samsung.android.app.kfa
pm uninstall --user 0 com.samsung.android.app.omcagent
pm uninstall --user 0 com.samsung.android.app.parentalcare
pm uninstall --user 0 com.samsung.android.app.settings.bixby
pm uninstall --user 0 com.samsung.android.app.sharelive
pm uninstall --user 0 com.samsung.android.app.taskedge
pm uninstall --user 0 com.samsung.android.app.updatecenter
pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall --user 0 com.samsung.android.authfw
pm uninstall --user 0 com.samsung.android.bbc.bbcagent
pm uninstall --user 0 com.samsung.android.beaconmanager
pm uninstall --user 0 com.samsung.android.bixby.agent
pm uninstall --user 0 com.samsung.android.bixby.wakeup
pm uninstall --user 0 com.samsung.android.bixbyvision.framework
pm uninstall --user 0 com.samsung.android.cameraxservice
pm uninstall --user 0 com.samsung.android.carkey
pm uninstall --user 0 com.samsung.android.coldwalletservice
pm uninstall --user 0 com.samsung.android.dbsc
pm uninstall --user 0 com.samsung.android.dkey
pm uninstall --user 0 com.samsung.android.dsms
pm uninstall --user 0 com.samsung.android.easysetup
pm uninstall --user 0 com.samsung.android.fmm
pm uninstall --user 0 com.samsung.android.forest
pm uninstall --user 0 com.samsung.android.game.gametools
pm uninstall --user 0 com.samsung.android.game.gos
pm uninstall --user 0 com.samsung.android.hdmapp
pm uninstall --user 0 com.samsung.android.inputshare
pm uninstall --user 0 com.samsung.android.ipsgeofence
pm uninstall --user 0 com.samsung.android.keycustomizationinfobackupservice
pm uninstall --user 0 com.samsung.android.kidsinstaller
pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
pm uninstall --user 0 com.samsung.android.knox.attestation
pm uninstall --user 0 com.samsung.android.knox.containercore
pm uninstall --user 0 com.samsung.android.knox.kpecore
pm uninstall --user 0 com.samsung.android.knox.pushmanager
pm uninstall --user 0 com.samsung.android.mcfds
pm uninstall --user 0 com.samsung.android.mdecservice
pm uninstall --user 0 com.samsung.android.mdm
pm uninstall --user 0 com.samsung.android.mdx
pm uninstall --user 0 com.samsung.android.mdx.kit
pm uninstall --user 0 com.samsung.android.mocca
pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
pm uninstall --user 0 com.samsung.android.networkdiagnostic
pm uninstall --user 0 com.samsung.android.providers.factory
pm uninstall --user 0 com.samsung.android.rampart
pm uninstall --user 0 com.samsung.android.rubin.app
pm uninstall --user 0 com.samsung.android.samsungpass
pm uninstall --user 0 com.samsung.android.samsungpassautofill
pm uninstall --user 0 com.samsung.android.samsungpositioning
pm uninstall --user 0 com.samsung.android.scloud
pm uninstall --user 0 com.samsung.android.scpm
pm uninstall --user 0 com.samsung.android.sdm.config
pm uninstall --user 0 com.samsung.android.server.wifi.mobilewips
pm uninstall --user 0 com.samsung.android.service.peoplestripe
pm uninstall --user 0 com.samsung.android.service.stplatform
pm uninstall --user 0 com.samsung.android.shortcutbackupservice
pm uninstall --user 0 com.samsung.android.smartcallprovider
pm uninstall --user 0 com.samsung.android.smartface.overlay
pm uninstall --user 0 com.samsung.android.smartsuggestions
pm uninstall --user 0 com.samsung.android.smartswitchassistant
pm uninstall --user 0 com.samsung.android.spayfw
pm uninstall --user 0 com.samsung.android.stickercenter
pm uninstall --user 0 com.samsung.android.svcagent
pm uninstall --user 0 com.samsung.android.uwb
pm uninstall --user 0 com.samsung.android.visionintelligence
pm uninstall --user 0 com.samsung.android.visualars
pm uninstall --user 0 com.samsung.android.vtcamerasettings
pm uninstall --user 0 com.samsung.faceservice
pm uninstall --user 0 com.samsung.gpuwatchapp
pm uninstall --user 0 com.samsung.InputEventApp
pm uninstall --user 0 com.samsung.ipservice
pm uninstall --user 0 com.samsung.klmsagent
pm uninstall --user 0 com.samsung.knox.securefolder
pm uninstall --user 0 com.samsung.oda.service
pm uninstall --user 0 com.samsung.safetyinformation
pm uninstall --user 0 com.samsung.sait.sohservice
pm uninstall --user 0 com.samsung.storyservice
pm uninstall --user 0 com.samsung.ucs.agent.ese
pm uninstall --user 0 com.sec.android.app.billing
pm uninstall --user 0 com.sec.android.app.bluetoothagent
pm uninstall --user 0 com.sec.android.app.chromecustomizations
pm uninstall --user 0 com.sec.android.app.DataCreate
pm uninstall --user 0 com.sec.android.app.factorykeystring
pm uninstall --user 0 com.sec.android.app.hwmoduletest
pm uninstall --user 0 com.sec.android.app.magnifier
pm uninstall --user 0 com.sec.android.app.parser
pm uninstall --user 0 com.sec.android.app.quicktool
pm uninstall --user 0 com.sec.android.app.sbrowser
pm uninstall --user 0 com.sec.android.app.servicemodeapp
pm uninstall --user 0 com.sec.android.app.setupwizard
pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
pm uninstall --user 0 com.sec.android.app.uwbtest
pm uninstall --user 0 com.sec.android.app.ve.vebgm
pm uninstall --user 0 com.sec.android.app.wlantest
pm uninstall --user 0 com.sec.android.CcInfo
pm uninstall --user 0 com.sec.android.easyMover
pm uninstall --user 0 com.sec.android.easyMover.Agent
pm uninstall --user 0 com.sec.android.easyonehand
pm uninstall --user 0 com.sec.android.iaft
pm uninstall --user 0 com.sec.android.mimage.avatarstickers
pm uninstall --user 0 com.sec.android.RilServiceModeApp
pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall --user 0 com.sec.app.RilErrorNotifier
pm uninstall --user 0 com.sec.bcservice
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin
pm uninstall --user 0 com.sec.epdgtestapp
pm uninstall --user 0 com.sec.facatfunction
pm uninstall --user 0 com.sec.factory.camera
pm uninstall --user 0 com.sec.hiddenmenu
pm uninstall --user 0 com.sec.imslogger
pm uninstall --user 0 com.sec.location.nsflp2
pm uninstall --user 0 com.sec.modem.settings
pm uninstall --user 0 com.sec.spp.push
pm uninstall --user 0 com.skms.android.agent
pm uninstall --user 0 com.android.bluetoothmidiservice
pm uninstall --user 0 com.android.calllogbackup
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
pm uninstall --user 0 com.android.providers.partnerbookmarks
pm uninstall --user 0 com.android.rkpdapp
pm uninstall --user 0 com.android.systemui.accessibility.accessibilitymenu
pm uninstall --user 0 com.android.theme.font.notoserifsource
pm uninstall --user 0 com.android.traceur
pm uninstall --user 0 com.android.virtualmachine.res
pm uninstall --user 0 com.google.android.adservices.api
pm uninstall --user 0 com.google.android.federatedcompute
pm uninstall --user 0 com.google.android.ondevicepersonalization.services
pm uninstall --user 0 com.google.android.overlay.modules.captiveportallogin.forframework
pm uninstall --user 0 com.google.android.overlay.modules.documentsui
pm uninstall --user 0 com.google.android.overlay.modules.permissioncontroller
pm uninstall --user 0 com.google.android.safetycenter.resources
pm uninstall --user 0 com.google.mainline.adservices
pm uninstall --user 0 com.diotek.sec.lookup.dictionary
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.apps.turbo
pm uninstall --user 0 com.google.android.feedback
pm uninstall --user 0 com.google.android.gm
pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
pm uninstall --user 0 com.google.android.youtube
pm uninstall --user 0 com.microsoft.appmanager
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.sem.factoryapp
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.apps.turbo
pm uninstall --user 0 com.google.android.feedback
pm uninstall --user 0 com.google.android.gm
pm uninstall --user 0 com.google.android.overlay.gmsconfig.photos
pm uninstall --user 0 com.google.android.youtube
