---
services:
  beszel_server:
    profiles: [beszel]
    image: henrygd/beszel
    container_name: beszel_server
    restart: unless-stopped
    environment:
      AUTO_LOGIN: true
      USER_EMAIL: ${EMAIL}
      USER_PASSWORD: ${PASS}
    volumes:
      - $DATA/beszel/beszel_server/data:/beszel_data
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.beszel.rule: Host(`beszel.henn.dev`)
      traefik.http.routers.beszel.entrypoints: websecure
      traefik.http.routers.beszel.tls.certresolver: cf
      traefik.http.services.beszel.loadbalancer.server.port: 8090
      homepage.group: Infra
      homepage.name: Beszel
      homepage.icon: beszel.png
      homepage.href: https://beszel.henn.dev
      homepage.description: Server Stats

  beszel_rack4:
    profiles: [beszel]
    image: henrygd/beszel-agent-nvidia
    container_name: beszel_rack4
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [utility]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA/beszel/beszel_rack4:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: https://beszel.henn.dev
    network_mode: host
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
