---
services:
  bytestash:
    profiles: [bytestash]
    image: ghcr.io/jordan-dalby/bytestash:latest
    container_name: bytestash
    restart: unless-stopped
    volumes:
      - $DATA/bytestash:/data/snippets
    environment:
      BASE_PATH: ""
      JWT_SECRET: your-secret
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: true
      DEBUG: false
      DISABLE_ACCOUNTS: true
      DISABLE_INTERNAL_ACCOUNTS: false
      OIDC_ENABLED: false
      OIDC_DISPLAY_NAME: ""
      OIDC_ISSUER_URL: ""
      OIDC_CLIENT_ID: ""
      OIDC_CLIENT_SECRET: ""
      OIDC_SCOPES: ""
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.stash.rule: Host(`stash.henn.dev`)
      traefik.http.routers.stash.entrypoints: websecure
      traefik.http.routers.stash.tls.certresolver: cf
      traefik.http.services.stash.loadbalancer.server.port: 5000
      homepage.group: Code
      homepage.name: ByteStash
      homepage.icon: bytestash.png
      homepage.href: https://stash.henn.dev
      homepage.description: Code Snippets
