---
services:
  code:
    profiles: [code]
    image: lscr.io/linuxserver/code-server
    container_name: code
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD:
      HASHED_PASSWORD:
      SUDO_PASSWORD:
      SUDO_PASSWORD_HASH:
      PROXY_DOMAIN: code.henn.dev
      DEFAULT_WORKSPACE: /config/workspace
    volumes:
      - $DATA/code:/config
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.code.rule: Host(`code.henn.dev`)
      traefik.http.routers.code.entrypoints: websecure
      traefik.http.routers.code.tls.certresolver: cf
      traefik.http.services.code.loadbalancer.server.port: 8443
      homepage.group: Code
      homepage.name: Code
      homepage.icon: code.png
      homepage.href: https://code.henn.dev
      homepage.description: Vs Code
