---
services:
  comfy:
    profiles: [comfy]
    image: yanwk/comfyui-boot:cu130-slim
    container_name: comfy
    restart: unless-stopped
    stdin_open: true
    tty: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - $DATA/comfy:/root
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.comfy.rule: Host(`comfy.henn.dev`)
      traefik.http.routers.comfy.entrypoints: websecure
      traefik.http.routers.comfy.tls.certresolver: cf
      traefik.http.services.comfy.loadbalancer.server.port: 8188
      homepage.group: AI
      homepage.name: ComfyUI
      homepage.icon: comfy-ui.png
      homepage.href: https://comfy.henn.dev
      homepage.description: Image Gen
