---
services:
  focalboard:
    profiles: [focalboard]
    image: mattermost/focalboard
    container_name: focalboard
    restart: unless-stopped
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.focalboard.rule: Host(`focalboard.henn.dev`)
      traefik.http.routers.focalboard.entrypoints: websecure
      traefik.http.routers.focalboard.tls.certresolver: cf
      traefik.http.services.focalboard.loadbalancer.server.port: 8000
      homepage.group: Tools
      homepage.name: Focalboard
      homepage.icon: focalboard.png
      homepage.href: https://focalboard.henn.dev
      homepage.description: Private Trello
