# initial user/pass: root/output from running gitlab_pass service
# - docker compose run --rm -it gitlab_pass
# - sign in as root using password from gitlab_pass
# - create user 'chris' as 'validated'
# - edit user 'chris' to add password
---
services:
  gitlab:
    profiles: [gitlab]
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    shm_size: 2g
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # global config
        external_url 'https://gitlab.henn.dev'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['lfs_enabled'] = true

        # nginx
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = true
        letsencrypt['enable'] = false

        # container registry
        registry['enable'] = true
        registry_external_url 'https://registry.gitlab.henn.dev'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = 'registry.gitlab.henn.dev'
        gitlab_rails['registry_port'] = 5050
        gitlab_rails['registry_api_url'] = 'http://localhost:5000'
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false

        # postgres
        # postgresql['enable'] = false
        # gitlab_rails['db_host'] = "gitlab_pg"
        # gitlab_rails['db_adapter'] = "postgresql"
        # gitlab_rails['db_encoding'] = "unicode"
        # gitlab_rails['db_database'] = "gitlab"
        # gitlab_rails['db_username'] = "gitlab"
        # gitlab_rails['db_password'] = "gitlab"

        # redis
        # redis['enable'] = false
        # gitlab_rails['redis_host'] = 'gitlab_redis'
        # gitlab_rails['redis_port'] = 6379

        # monitoring
        prometheus_monitoring['enable'] = false
        sidekiq['metrics_enabled'] = false
        puma['exporter_enabled'] = false

        # resource limiting
        postgresql['shared_buffers'] = "256MB"
        sidekiq['max_concurrency'] = 4
        sidekiq['concurrency'] = 1
        puma['worker_timeout'] = 120
        puma['worker_processes'] = 1

        gitaly['configuration'] = {
          concurrency: [
            {
              'rpc' => "/gitaly.SmartHTTPService/PostReceivePack",
              'max_per_repo' => 3,
            }, {
              'rpc' => "/gitaly.SSHService/SSHUploadPack",
              'max_per_repo' => 3,
            },
          ],
        }
        gitaly['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000',
          'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2',
        }
        gitlab_rails['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000',
        }

    volumes:
      - $DATA/gitlab/data:/var/opt/gitlab
      - $DATA/gitlab/logs:/var/log/gitlab
      - $DATA/gitlab/config:/etc/gitlab
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 240s
    networks: [traefik]
    labels:
      docker-volume-backup.stop-during-backup: gitlab

      traefik.enable: true
      traefik.http.routers.gitlab.rule: Host(`gitlab.henn.dev`)
      traefik.http.routers.gitlab.entrypoints: websecure
      traefik.http.routers.gitlab.middlewares: hdrs@file
      traefik.http.routers.gitlab.tls.certresolver: cf
      traefik.http.routers.gitlab.service: gitlab
      traefik.http.services.gitlab.loadbalancer.server.port: 80

      traefik.http.routers.gitlab_registry.rule: Host(`registry.gitlab.henn.dev`)
      traefik.http.routers.gitlab_registry.entrypoints: websecure
      traefik.http.routers.gitlab_registry.middlewares: hdrs@file
      traefik.http.routers.gitlab_registry.tls.certresolver: cf
      traefik.http.routers.gitlab_registry.service: gitlab_registry
      traefik.http.services.gitlab_registry.loadbalancer.server.port: 5050

      traefik.tcp.routers.gitlab_ssh.rule: HostSNI(`*`)
      traefik.tcp.routers.gitlab_ssh.entrypoints: tcp2424
      traefik.tcp.routers.gitlab_ssh.service: gitlab_ssh
      traefik.tcp.services.gitlab_ssh.loadbalancer.server.port: 22

      homepage.group: Code
      homepage.name: Gitlab
      homepage.icon: gitlab.png
      homepage.href: https://gitlab.henn.dev
      homepage.description: Gitlab
#  gitlab_pg:
#    profiles: [gitlab]
#    image: postgres:16
#    container_name: gitlab_pg
#    restart: unless-stopped
#    volumes:
#      - $DATA/gitlab/gitlab_pg:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: gitlab
#      POSTGRES_USER: gitlab
#      POSTGRES_PASSWORD: gitlab
#    healthcheck:
#      test: ["CMD", "pg_isready", "-q", "-d", "gitlab", "-U", "gitlab"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 60s
#    networks: [traefik]
#
#  gitlab_redis:
#    profiles: [gitlab]
#    image: redis:7
#    container_name: gitlab_redis
#    restart: unless-stopped
#    volumes:
#      - $DATA/gitlab/gitlab_redis:/data
#    networks: [traefik]

# docker compose run --rm -it gitlab_perm
#  gitlab_perm:
#    profiles: [gitlab_help]
#    image: gitlab/gitlab-ce:latest
#    container_name: gitlab_perm
#    restart: no
#    command: /bin/sh -c "update-permissions"
#    volumes:
#      - $DATA/gitlab/config:/etc/gitlab
#      - $DATA/gitlab/logs:/var/log/gitlab
#      - $DATA/gitlab/data:/var/opt/gitlab

# docker compose run --rm -it gitlab_pass
#  gitlab_pass:
#    profiles: [gitlab_help]
#    image: alpine
#    container_name: gitlab_pass
#    restart: no
#    command: /bin/sh -c "grep 'Password:' /etc/gitlab/initial_root_password"
#    volumes:
#      - $DATA/gitlab/config:/etc/gitlab

#  gitlab_backup:
#    profiles: [gitlab_help]
#    image: offen/docker-volume-backup:latest
#    container_name: gitlab_backup
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /etc/localtime:/etc/localtime:ro
#      # source data to backup
#      - $DATA/gitlab:/backup/gitlab:ro
#      # backup destination
#      - $BACKUP/gitlab:/archive
#    environment:
#      BACKUP_STOP_DURING_BACKUP_LABEL: gitlab
#      BACKUP_CRON_EXPRESSION: "@daily"
#      BACKUP_FILENAME: "gitlab-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
#      BACKUP_PRUNING_PREFIX: "gitlab-"
#      BACKUP_RETENTION_DAYS: 2
#    networks: [traefik, docker]
