---
services:
  gluetun:
    profiles: [gluetun]
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      Timezone: $TZ
      UPDATER_PERIOD: 24h
      VPN_TYPE: wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: "United States,Canada"
      PORT_FORWARD_ONLY: on
    volumes:
      - $DATA/gluetun:/gluetun
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.gluetun.rule: Host(`gluetun.henn.dev`)
      traefik.http.routers.gluetun.entrypoints: websecure
      traefik.http.routers.gluetun.tls.certresolver: cf
      traefik.http.routers.gluetun.service: gluetun
      traefik.http.services.gluetun.loadbalancer.server.port: 8000

      traefik.http.routers.qbit.rule: Host(`vpn.qbit.henn.dev`)
      traefik.http.routers.qbit.entrypoints: websecure
      traefik.http.routers.qbit.tls.certresolver: cf
      traefik.http.routers.qbit.service: qbit
      traefik.http.services.qbit.loadbalancer.server.port: 8080

      homepage.group: Infra
      homepage.name: Gluetun
      homepage.icon: gluetun.png
      homepage.href: https://gluetun.henn.dev
      homepage.description: Qbittorrent VPN Tunnel
      homepage.widget.type: gluetun
      homepage.widget.url: https://gluetun.henn.dev
    ports:
      - "6888:6888/tcp"
      - "6888:6888/udp"
      - "8388:8388/tcp"
      - "8388:8388/udp"
      - "8888:8888/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"

  # docker compose run --rm -it gluetun_test
#  gluetun_test:
#    profiles: [gluetun]
#    image: alpine
#    container_name: gluetun_test
#    restart: no
#    command: sh -c "wget -O- https://ipinfo.io"
#    #    command: sh -c "wget -O- ip.me"
#    network_mode: container:gluetun
