# first time login: https://jellyfin.henn.dev/web/index.html#!/wizardstart.html
---
services:
  jellyfin:
    profiles: [jellyfin]
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $PUID:$PGID
    restart: unless-stopped
    hostname: jellyfin
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, video, compute]
              count: 1
    volumes:
      - $DATA/jellyfin/config:/config
      - $DATA/jellyfin/cache:/cache
      - type: bind
        source: $MEDIA
        target: /media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      JELLYFIN_PublishedServerUrl: 'https://jellyfin.henn.dev'
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.henn.dev`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.middlewares: hdrs@file
      traefik.http.routers.jellyfin.tls.certresolver: cf
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      homepage.group: Media
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.henn.dev
      homepage.description: Media Server
    ports:
      - '1900:1900/udp'
  #      - "7359:7359/udp" # jellyfin-discovery uses 7359

  jellyfin-discovery:
    profiles: [jellyfin]
    image: jpkribs/jellyfin-discovery-proxy:latest
    container_name: jellyfin-discovery
    restart: unless-stopped
    network_mode: host
    environment:
      JELLYFIN_SERVER_URL: https://jellyfin.henn.dev
      CACHE_DURATION: 12
      HTTP_PORT: 7359
