# using 30GB of memory at idle
---
x-karakeep_env: &karakeep_env
  NEXTAUTH_URL: https://karakeep.chenn.dev
  NEXTAUTH_SECRET: $KARAKEEP_NEXTAUTH_SECRET
  MEILI_MASTER_KEY: $KARAKEEP_MEILI_MASTER_KEY

  MEILI_ADDR: http://karakeep_meili:7700
  BROWSER_WEB_URL: http://karakeep_chrome:9222
  OLLAMA_BASE_URL: http://ollama:11434

  DISABLE_SIGNUPS: false
  DISABLE_PASSWORD_AUTH: false
  EMAIL_VERIFICATION_REQUIRED: false
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: false
  OAUTH_WELLKNOWN_URL: https://pocketid.chenn.dev/.well-known/openid-configuration
  OAUTH_CLIENT_ID: $KARAKEEP_OIDC_CLIENT
  OAUTH_CLIENT_SECRET: $KARAKEEP_OIDC_SECRET
  OAUTH_PROVIDER_NAME: PocketID

  MEILI_NO_ANALYTICS: true
  DATA_DIR: /data

  SMTP_HOST: $SMTP_HOST
  SMTP_PORT: 465
  SMTP_SECURE: true
  SMTP_USER: $SMTP_USER
  SMTP_PASSWORD: $SMTP_TOKEN
  SMTP_FROM: $SMTP_USER

services:
  karakeep:
    profiles: [karakeep]
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      <<: *karakeep_env
    volumes:
      - $DATA/karakeep/data:/data
    networks: [traefik, karakeep]
    labels:
      homepage.group: Tools
      homepage.name: Karakeep
      homepage.icon: karakeep.png
      homepage.href: https://karakeep.chenn.dev
      homepage.description: Notes with AI tagging

      pangolin.public-resources.karakeep.name: karakeep
      pangolin.public-resources.karakeep.protocol: http
      pangolin.public-resources.karakeep.full-domain: karakeep.chenn.dev
      pangolin.public-resources.karakeep.ssl: true
      pangolin.public-resources.karakeep.targets[0].method: http
      pangolin.public-resources.karakeep.targets[0].port: 3000

      pangolin.public-resources.karakeep.auth.sso-enabled: true
      pangolin.public-resources.karakeep.auth.sso-roles[0]: Member
      pangolin.public-resources.karakeep.rules[0].action: pass
      pangolin.public-resources.karakeep.rules[0].match: country
      pangolin.public-resources.karakeep.rules[0].value: US
      pangolin.public-resources.karakeep.rules[0].priority: 0
      pangolin.public-resources.karakeep.rules[1].action: deny
      pangolin.public-resources.karakeep.rules[1].match: country
      pangolin.public-resources.karakeep.rules[1].value: ALL
      pangolin.public-resources.karakeep.rules[1].priority: 10

  karakeep_meili:
    profiles: [karakeep]
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep_meili
    restart: unless-stopped
    environment:
      <<: *karakeep_env
    volumes:
      - $DATA/karakeep/meili:/meili_data
    networks: [karakeep]

  karakeep_chrome:
    profiles: [karakeep]
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: karakeep_chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks: [karakeep]

networks:
  karakeep:
