---
services:
  metube:
    profiles: [metube]
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    volumes:
      - $DATA/metube:/downloads
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.metube.rule: Host(`metube.henn.dev`)
      traefik.http.routers.metube.entrypoints: websecure
      traefik.http.routers.metube.tls.certresolver: cf
      traefik.http.services.metube.loadbalancer.server.port: 8081
      homepage.group: Media
      homepage.name: Metube
      homepage.icon: metube.png
      homepage.href: https://metube.henn.dev
      homepage.description: Youtube Downloader
