---
x-shared: &shared
  image: docker.n8n.io/n8nio/n8n
  restart: unless-stopped
  environment:
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: n8n_postgres
    DB_POSTGRESDB_PORT: 5432
    DB_POSTGRESDB_USER: root
    DB_POSTGRESDB_PASSWORD: 1234
    DB_POSTGRESDB_DATABASE: n8n
    EXECUTIONS_MODE: queue
    QUEUE_BULL_REDIS_HOST: n8n_redis
    QUEUE_HEALTH_CHECK_ACTIVE: true
    N8N_RUNNERS_ENABLED: true
    OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: true
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
  volumes:
    - $DATA/n8n/n8n_storage:/home/node/.n8n
  depends_on:
    n8n_redis:
      condition: service_healthy
    n8n_postgres:
      condition: service_healthy
  networks: [traefik]

services:
  n8n:
    profiles: [n8n]
    container_name: n8n
    <<: *shared
    environment:
      N8N_HOST: n8n.henn.dev
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8n.henn.dev/
      GENERIC_TIMEZONE: $TZ
    networks: [traefik]
    labels:
      homepage.group: AI
      homepage.name: N8n
      homepage.icon: n8n.png
      homepage.href: https://n8n.chenn.dev
      homepage.description: GUI Data Flow

      traefik.enable: true
      traefik.http.routers.n8n.rule: Host(`n8n.henn.dev`)
      traefik.http.routers.n8n.entrypoints: websecure
      traefik.http.routers.n8n.middlewares: hdrs@file
      traefik.http.routers.n8n.tls.certresolver: cf
      traefik.http.services.n8n.loadbalancer.server.port: 5678

      pangolin.public-resources.n8n.name: n8n
      pangolin.public-resources.n8n.protocol: http
      pangolin.public-resources.n8n.full-domain: n8n.chenn.dev
      pangolin.public-resources.n8n.ssl: true
      pangolin.public-resources.n8n.targets[0].method: http
      pangolin.public-resources.n8n.targets[0].port: 5678
      pangolin.public-resources.n8n.targets[0].healthcheck.enabled: true
      pangolin.public-resources.n8n.targets[0].healthcheck.hostname: n8n
      pangolin.public-resources.n8n.targets[0].healthcheck.port: 5678
      pangolin.public-resources.n8n.targets[0].healthcheck.interval: 3
      pangolin.public-resources.n8n.targets[0].healthcheck.path: /
      pangolin.public-resources.n8n.auth.sso-enabled: true
      pangolin.public-resources.n8n.auth.sso-roles[0]: Member
      pangolin.public-resources.n8n.auth.sso-users[0]: ${EMAIL}
      pangolin.public-resources.n8n.rules[0].action: pass
      pangolin.public-resources.n8n.rules[0].match: country
      pangolin.public-resources.n8n.rules[0].value: US
      pangolin.public-resources.n8n.rules[0].priority: 0
      pangolin.public-resources.n8n.rules[1].action: deny
      pangolin.public-resources.n8n.rules[1].match: country
      pangolin.public-resources.n8n.rules[1].value: ALL
      pangolin.public-resources.n8n.rules[1].priority: 10

  n8n_worker:
    profiles: [n8n]
    container_name: n8n_worker
    <<: *shared
    command: worker
    networks: [traefik]
    depends_on:
      - n8n

  n8n_postgres:
    profiles: [n8n]
    image: postgres:16
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: n8n
      POSTGRES_NON_ROOT_USER: postgres
      POSTGRES_NON_ROOT_PASSWORD: postgres
    volumes:
      - $DATA/n8n/n8n_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U root -d n8n']
    networks: [traefik]

  n8n_redis:
    profiles: [n8n]
    image: redis:6-alpine
    container_name: n8n_redis
    restart: unless-stopped
    volumes:
      - $DATA/n8n/n8n_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    networks: [traefik]
