---
services:
  pairdrop:
    profiles: [pairdrop]
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      RATE_LIMIT: false
      WS_FALLBACK: false
      RTC_CONFIG:
      DEBUG_MODE: false
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.pairdrop.rule: Host(`pairdrop.henn.dev`)
      traefik.http.routers.pairdrop.entrypoints: websecure
      traefik.http.routers.pairdrop.middlewares: hdrs@file
      traefik.http.routers.pairdrop.tls.certresolver: cf
      traefik.http.services.pairdrop.loadbalancer.server.port: 3000
      homepage.group: Tools
      homepage.name: Pairdrop
      homepage.icon: pairdrop.png
      homepage.href: https://pairdrop.henn.dev
      homepage.description: Universal Airdrop
