services:
  planka:
    profiles: [planka]
    image: ghcr.io/plankanban/planka:2.0.0-rc.4
    container_name: planka
    restart: unless-stopped
    volumes:
      - $DATA/planka/favicons:/app/public/favicons
      - $DATA/planka/user-avatars:/app/public/user-avatars
      - $DATA/planka/background-images:/app/public/background-images
      - $DATA/planka/attachments:/app/private/attachments
    environment:
      BASE_URL: https://planka.chenn.dev
      DATABASE_URL: postgresql://postgres@planka_db/planka
      SECRET_KEY: notsecretkey
      TRUST_PROXY: true
      MAX_UPLOAD_FILE_SIZE: 10G
      DEFAULT_LANGUAGE: en-US

      DEFAULT_ADMIN_USERNAME: ${USER}
      DEFAULT_ADMIN_PASSWORD: ${PASS}
      DEFAULT_ADMIN_EMAIL: ${EMAIL}
      DEFAULT_ADMIN_NAME: ${USER}

      OIDC_ISSUER: $OIDC
      OIDC_CLIENT_ID: $PLANKA_OIDC_CLIENT
      OIDC_CLIENT_SECRET: $PLANKA_OIDC_SECRET
      OIDC_SCOPES: openid profile email groups
      OIDC_ROLES_ATTRIBUTE: groups
      OIDC_ADMIN_ROLES: admin
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO --no-verbose http://127.0.0.1:1337']
    networks: [traefik]
    labels:
      homepage.group: Tools
      homepage.name: Planka
      homepage.icon: planka.png
      homepage.href: https://planka.chenn.dev
      homepage.description: Private Trello

      pangolin.public-resources.planka.name: planka
      pangolin.public-resources.planka.protocol: http
      pangolin.public-resources.planka.full-domain: planka.chenn.dev
      pangolin.public-resources.planka.ssl: true
      pangolin.public-resources.planka.targets[0].method: http
      pangolin.public-resources.planka.targets[0].port: 1337

      pangolin.public-resources.planka.auth.sso-enabled: true
      pangolin.public-resources.planka.auth.sso-roles[0]: Member
      pangolin.public-resources.planka.rules[0].action: pass
      pangolin.public-resources.planka.rules[0].match: country
      pangolin.public-resources.planka.rules[0].value: US
      pangolin.public-resources.planka.rules[0].priority: 0
      pangolin.public-resources.planka.rules[1].action: deny
      pangolin.public-resources.planka.rules[1].match: country
      pangolin.public-resources.planka.rules[1].value: ALL
      pangolin.public-resources.planka.rules[1].priority: 10

  planka_db:
    profiles: [planka]
    image: postgres:16-alpine
    container_name: planka_db
    restart: unless-stopped
    volumes:
      - $DATA/planka/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d planka']
    networks: [traefik]
