---
services:
  redlib:
    profiles: [redlib]
    image: quay.io/redlib/redlib:latest
    container_name: redlib
    restart: unless-stopped
    #    env_file: ./redlib/.env
    environment:
      # Instance-specific settings
      # Enable SFW-only mode for the instance
      REDLIB_SFW_ONLY: off
      # Set a banner message for the instance
      REDLIB_BANNER:
      # Disable search engine indexing
      REDLIB_ROBOTS_DISABLE_INDEXING: off
      # Set the Pushshift frontend for "removed" links
      REDLIB_PUSHSHIFT_FRONTEND: undelete.pullpush.io
      # Default user settings
      # Set the default theme (options: system, light, dark, black, dracula, nord, laserwave, violet, gold, rosebox, gruvboxdark, gruvboxlight)
      REDLIB_DEFAULT_THEME: dark
      # Set the default front page (options: default, popular, all)
      REDLIB_DEFAULT_FRONT_PAGE: default
      # Set the default layout (options: card, clean, compact)
      REDLIB_DEFAULT_LAYOUT: card
      # Enable wide mode by default
      REDLIB_DEFAULT_WIDE: on
      # Set the default post sort method (options: hot, new, top, rising, controversial)
      REDLIB_DEFAULT_POST_SORT: hot
      # Set the default comment sort method (options: confidence, top, new, controversial, old)
      REDLIB_DEFAULT_COMMENT_SORT: confidence
      # Enable blurring Spoiler content by default
      REDLIB_DEFAULT_BLUR_SPOILER: off
      # Enable showing NSFW content by default
      REDLIB_DEFAULT_SHOW_NSFW: on
      # Enable blurring NSFW content by default
      REDLIB_DEFAULT_BLUR_NSFW: off
      # Enable HLS video format by default
      REDLIB_DEFAULT_USE_HLS: on
      # Hide HLS notification by default
      REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: on
      # Disable autoplay videos by default
      REDLIB_DEFAULT_AUTOPLAY_VIDEOS: off
      # Define a default list of subreddit subscriptions (format: sub1+sub2+sub3)
      REDLIB_DEFAULT_SUBSCRIPTIONS:
      # Define a default list of subreddit filters (format: sub1+sub2+sub3)
      REDLIB_DEFAULT_FILTERS:
      # Hide awards by default
      REDLIB_DEFAULT_HIDE_AWARDS: on
      # Hide sidebar and summary
      REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY: off
      # Disable the confirmation before visiting Reddit
      REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION: on
      # Hide score by default
      REDLIB_DEFAULT_HIDE_SCORE: off
      # Enable fixed navbar by default
      REDLIB_DEFAULT_FIXED_NAVBAR: on
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.redlib.rule: Host(`reddit.henn.dev`)
      traefik.http.routers.redlib.entrypoints: websecure
      traefik.http.routers.redlib.tls.certresolver: cf
      traefik.http.services.redlib.loadbalancer.server.port: 8080
      homepage.group: Tools
      homepage.name: Redlib
      homepage.icon: redlib.png
      homepage.href: https://reddit.henn.dev
      homepage.description: Private Reddit Frontend
