---
x-seafile_env: &seafile_env
  INIT_SEAFILE_MYSQL_ROOT_PASSWORD: seafile
  SEAFILE_MYSQL_DB_HOST: seafile_db
  SEAFILE_MYSQL_DB_PORT: 3306
  SEAFILE_MYSQL_DB_USER: seafile
  SEAFILE_MYSQL_DB_PASSWORD: seafile
  SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
  SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub_db
  TIME_ZONE: $TZ
  INIT_SEAFILE_ADMIN_EMAIL: ${EMAIL}
  INIT_SEAFILE_ADMIN_PASSWORD: ${PASS}
  SEAFILE_SERVER_HOSTNAME: seafile.henn.dev
  SEAFILE_SERVER_PROTOCOL: https
  SITE_ROOT: /
  NON_ROOT: false
  JWT_PRIVATE_KEY: JWT_PRIVATE_KEY
  SEAFILE_LOG_TO_STDOUT: false
  ENABLE_GO_FILESERVER: true
  ENABLE_SEADOC: true
  SEADOC_SERVER_URL: https://seafile.henn.dev/sdoc-server
  CACHE_PROVIDER: redis
  REDIS_HOST: seafile_redis
  REDIS_PORT: 6379
  REDIS_PASSWORD: REDIS_PASSWORD
  MEMCACHED_HOST: seafile_memcached
  MEMCACHED_PORT: 11211
  SEAF_SERVER_STORAGE_TYPE: disk
  ENABLE_NOTIFICATION_SERVER: true
  INNER_NOTIFICATION_SERVER_URL: http://seafile_notifications:8083
  NOTIFICATION_SERVER_URL: https://seafile.henn.dev/notification
  ENABLE_SEAFILE_AI: false
  SEAFILE_AI_SERVER_URL: http://seafile_ai:8888
  SEAFILE_AI_SECRET_KEY: SEAFILE_AI_SECRET_KEY
  MD_FILE_COUNT_LIMIT: 100000
  EMAIL_HOST_PASSWORD: ${SMTP_TOKEN}

  DB_HOST: seafile_db
  DB_PORT: 3306
  DB_USER: seafile
  DB_PASSWORD: seafile
  DB_NAME: seahub_db

  SEAHUB_SERVICE_URL: http://seafile
  NOTIFICATION_SERVER_LOG_LEVEL: info
  MD_PORT: 8084
  MD_LOG_LEVEL: info
  MD_MAX_CACHE_SIZE: 2GB
  MD_CHECK_UPDATE_INTERVAL: 30m
  MD_STORAGE_TYPE: disk
  
  INNER_SEAHUB_SERVICE_URL: http://seafile
  THUMBNAIL_IMAGE_ORIGINAL_SIZE_LIMIT: 256

  SS_FIRST_ADMIN_USER: ${EMAIL}
  SS_FIRST_ADMIN_PASSWORD: ${PASS}
  SS_MAX_OBJ_CACHE_SIZE: 10GB
  SS_STORAGE_TYPE: disk
  SS_LOG_TO_STDOUT: false
  SS_LOG_DIR: /opt/seasearch/data/log
  SS_LOG_LEVEL: info
  SEATABLE_LOG_TO_STDOUT: false
  SS_SERVER_MODE:
  SS_CLUSTER_ID:
  SS_CLUSTER_PROXY_HOST: 0.0.0.0
  SS_CLUSTER_PROXY_PORT: 4082
  SS_CLUSTER_MANAGER_ADDR: 127.0.0.1:4081
  SS_ETCD_USERNAME:
  SS_ETCD_PASSWORD:
  SS_ETCD_ENDPOINTS: 127.0.0.1:2379
  SS_ETCD_PREFIX: /zinc
  SS_CLUSTER_PROXY_LOG_DIR: /opt/seasearch/data/log
  SS_CLUSTER_MANAGER_HOST: 0.0.0.0
  SS_CLUSTER_MANAGER_PORT: 4081

  MYSQL_ROOT_PASSWORD: seafile
  MYSQL_LOG_CONSOLE: true
  MARIADB_AUTO_UPGRADE: 1

services:

  seafile:
    profiles: [seafile]
    image: seafileltd/seafile-pro-mc:13.0-latest
    container_name: seafile
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seafile:/shared
    environment:
      <<: *seafile_env
    networks: [traefik, seafile]
    labels:
      traefik.enable: true
      traefik.http.routers.seafile.rule: Host(`seafile.henn.dev`) && PathPrefix(`/`)
      traefik.http.routers.seafile.entrypoints: websecure
      traefik.http.routers.seafile.middlewares: hdrs@file
      traefik.http.routers.seafile.tls.certresolver: cf
      traefik.http.routers.seafile.priority: 1
      traefik.http.services.seafile.loadbalancer.server.port: 80

  seadoc:
    profiles: [seafile]
    image: seafileltd/sdoc-server:2.0-latest
    container_name: seadoc
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seadoc:/shared
    environment:
      <<: *seafile_env
    networks: [traefik, seafile]
    labels:
      traefik.enable: true

      traefik.http.middlewares.seadoc_strip.stripprefixregex.regex: '^/sdoc-server/?'
      traefik.http.routers.seadoc.rule: Host(`seafile.henn.dev`) && PathPrefix(`/sdoc-server`)
      traefik.http.routers.seadoc.entrypoints: websecure
      traefik.http.routers.seadoc.middlewares: seadoc_strip
      traefik.http.routers.seadoc.tls.certresolver: cf
      traefik.http.routers.seadoc.service: seadoc
      traefik.http.routers.seadoc.priority: 10

      traefik.http.routers.seadoc_ws.rule: Host(`seafile.henn.dev`) && PathPrefix(`/socket.io`)
      traefik.http.routers.seadoc_ws.entrypoints: websecure
      traefik.http.routers.seadoc_ws.tls.certresolver: cf
      traefik.http.routers.seadoc_ws.service: seadoc
      traefik.http.routers.seadoc_ws.priority: 10

      traefik.http.services.seadoc.loadbalancer.server.port: 80

  seafile_notifications:
    profiles: [seafile]
    image: ${NOTIFICATION_SERVER_IMAGE:-seafileltd/notification-server:13.0-latest}
    container_name: notification-server
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seafile/seafile/logs:/shared/seafile/logs
    environment:
      <<: *seafile_env
    networks: [traefik, seafile]
    labels:
      traefik.enable: true
      traefik.http.routers.seafile_notifications.rule: Host(`seafile.henn.dev`) && PathPrefix(`/notification`)
      traefik.http.routers.seafile_notifications.entrypoints: websecure
      traefik.http.routers.seafile_notifications.tls.certresolver: cf
      traefik.http.routers.seafile_notifications.priority: 10
      traefik.http.services.seafile_notifications.loadbalancer.server.port: 8083

  seafile_md:
    profiles: [seafile]
    image: seafileltd/seafile-md-server:13.0-latest
    container_name: seafile_md
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seafile:/shared
    environment:
      <<: *seafile_env
    networks: [seafile]

  seafile_thumbs:
    profiles: [seafile]
    image: seafileltd/thumbnail-server:13.0-latest
    container_name: seafile_thumbs
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seafile:/shared
    environment:
      <<: *seafile_env
    networks: [traefik, seafile]
    labels:
      traefik.enable: true
      traefik.http.routers.seafile_thumbs.rule: Host(`seafile.henn.dev`) && PathPrefix(`/thumbnail`)
      traefik.http.routers.seafile_thumbs.entrypoints: websecure
      traefik.http.routers.seafile_thumbs.tls.certresolver: cf
      traefik.http.routers.seafile_thumbs.priority: 10
      traefik.http.services.seafile_thumbs.loadbalancer.server.port: 80

  seasearch:
    profiles: [seafile]
    image: seafileltd/seasearch:1.0-latest
    container_name: seasearch
    restart: unless-stopped
    volumes:
      - $DATA/seafile/seasearch:/opt/seasearch/data
    environment:
      <<: *seafile_env
    networks: [seafile]

  seafile_db:
    profiles: [seafile]
    image: mariadb:10.11
    container_name: seafile_db
    restart: unless-stopped
    environment:
      <<: *seafile_env
    volumes:
      - $DATA/seafile/seafile_db:/var/lib/mysql
    networks: [seafile]

  seafile_redis:
    profiles: [seafile]
    image: redis
    container_name: seafile_redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$$REDIS_PASSWORD"
    environment:
      <<: *seafile_env

  seafile_memcached:
    profiles: [seafile]
    image: memcached:1.6.18
    container_name: seafile_memcached
    restart: unless-stopped
    entrypoint: memcached -m 256

networks:
  seafile:
