---
services:
  searx:
    profiles: [searx]
    image: searxng/searxng:latest
    container_name: searx
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add: [CHOWN, SETGID, SETUID, DAC_OVERRIDE]
    environment:
      SEARXNG_BASE_URL: https://searx.henn.dev
      SEARXNG_LIMITER: false
      SEARXNG_IMAGE_PROXY: true
      SEARXNG_PUBLIC_INSTANCE: false
      SEARXNG_VALKEY_URL: valkey://searx_redis:6379/0
      SEARXNG_SECRET: ${SEARXNG_SECRET}
      SEARXNG_PORT: 8080
      SEARXNG_BIND_ADDRESS: ${SVC_IP}
    volumes:
      - $DATA/searx/app:/etc/searxng:rw
      - $DATA/searx/cache:/var/cache/searxng:rw
    networks: [traefik]
    labels:
      homepage.group: AI
      homepage.name: Searx
      homepage.icon: searxng.png
      homepage.href: https://searx.chenn.dev
      homepage.description: Private Google

      traefik.enable: true
      traefik.http.routers.sear.rule: Host(`searx.henn.dev`)
      traefik.http.routers.sear.entrypoints: websecure
      traefik.http.routers.sear.middlewares: hdrs@file
      traefik.http.routers.sear.tls.certresolver: cf
      traefik.http.services.sear.loadbalancer.server.port: 8080

      pangolin.public-resources.searx.name: searx
      pangolin.public-resources.searx.protocol: http
      pangolin.public-resources.searx.full-domain: searx.chenn.dev
      pangolin.public-resources.searx.ssl: true
      pangolin.public-resources.searx.targets[0].method: http
      pangolin.public-resources.searx.targets[0].port: 8080

      pangolin.public-resources.searx.auth.sso-enabled: true
      pangolin.public-resources.searx.auth.sso-roles[0]: Member
      pangolin.public-resources.searx.rules[0].action: pass
      pangolin.public-resources.searx.rules[0].match: country
      pangolin.public-resources.searx.rules[0].value: US
      pangolin.public-resources.searx.rules[0].priority: 0
      pangolin.public-resources.searx.rules[1].action: deny
      pangolin.public-resources.searx.rules[1].match: country
      pangolin.public-resources.searx.rules[1].value: ALL
      pangolin.public-resources.searx.rules[1].priority: 10

  searx_redis:
    profiles: [searx]
    image: valkey/valkey:8-alpine
    container_name: searx_redis
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - $DATA/searx/redis:/data
    networks: [traefik]
