# migrations script currently nonworking (https://github.com/overleaf/overleaf/issues/1441). run manually:

# j u c overleaf_mongo
# j attach overleaf_mongo mongosh
# rs.initiate({ _id: 'overleaf', members: [{ _id: 0, host: 'overleaf_mongo:27017' }] })

# https://overleaf.chenn.dev/launchpad
---
services:
  overleaf:
    profiles: [overleaf]
    image: sharelatex/sharelatex
    container_name: overleaf
    restart: unless-stopped
    environment:
      OVERLEAF_SITE_URL: https://overleaf.chenn.dev
      OVERLEAF_APP_NAME: Chicken Overleaf

      OVERLEAF_MONGO_URL: mongodb://overleaf_mongo/sharelatex
      OVERLEAF_REDIS_HOST: overleaf_redis
      REDIS_HOST: overleaf_redis
      OVERLEAF_REDIS_PORT: 6379
      REDIS_PORT: 6379

      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'

      OVERLEAF_NAV_TITLE: Chicken Overleaf
      OVERLEAF_HEADER_IMAGE_URL: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/overleaf.svg
      OVERLEAF_ADMIN_EMAIL: ${EMAIL}
      OVERLEAF_LEFT_FOOTER: '[{"text": "Left Footer"} ]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": "Right Footer"} ]'
      OVERLEAF_EMAIL_FROM_ADDRESS: $SMTP_USER
      OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
      OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:
      OVERLEAF_EMAIL_SMTP_HOST: $SMTP_HOST
      OVERLEAF_EMAIL_SMTP_PORT: 465
      OVERLEAF_EMAIL_SMTP_SECURE: true
      OVERLEAF_EMAIL_SMTP_USER: $SMTP_USER
      OVERLEAF_EMAIL_SMTP_PASS: $SMTP_TOKEN
      OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
      OVERLEAF_EMAIL_SMTP_NAME: '127.0.0.1'
      OVERLEAF_EMAIL_SMTP_LOGGER: true
      OVERLEAF_CUSTOM_EMAIL_FOOTER: 'Overleaf Email Footer'
      ENABLE_CRON_RESOURCE_DELETION: true

      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/home/user/sharelatex_data/data/compiles'
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/home/user/sharelatex_data/data/output'
      DOCKER_RUNNER: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      OVERLEAF_PROXY_LEARN: 'true'
    volumes:
      - $DATA/overleaf/data:/var/lib/overleaf
    depends_on:
      overleaf_mongo:
        condition: service_healthy
      overleaf_redis:
        condition: service_started
    networks: [overleaf, newt]
    labels:
      homepage.group: File Editors
      homepage.name: Overleaf
      homepage.icon: overleaf.png
      homepage.href: https://overleaf.chenn.dev
      homepage.description: Latex PDF Compiler

      pangolin.public-resources.overleaf.name: overleaf
      pangolin.public-resources.overleaf.full-domain: overleaf.chenn.dev
      pangolin.public-resources.overleaf.protocol: http
      pangolin.public-resources.overleaf.ssl: true
      pangolin.public-resources.overleaf.targets[0].method: http
      pangolin.public-resources.overleaf.targets[0].port: 80
      pangolin.public-resources.overleaf.auth.sso-enabled: true
      pangolin.public-resources.overleaf.auth.sso-roles[0]: Member
      pangolin.public-resources.overleaf.rules[0].action: pass
      pangolin.public-resources.overleaf.rules[0].match: country
      pangolin.public-resources.overleaf.rules[0].value: US
      pangolin.public-resources.overleaf.rules[1].action: deny
      pangolin.public-resources.overleaf.rules[1].match: country
      pangolin.public-resources.overleaf.rules[1].value: ALL

  overleaf_mongo:
    profiles: [overleaf]
    image: mongo:8
    container_name: overleaf_mongo
    restart: unless-stopped
    hostname: overleaf_mongo
    command: '--bind_ip_all --replSet overleaf'
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    volumes:
      - $DATA/overleaf/db:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks: [overleaf]

  overleaf_redis:
    profiles: [overleaf]
    image: redis:8-alpine
    container_name: overleaf_redis
    restart: unless-stopped
    volumes:
      - $DATA/overleaf/redis:/data
    networks: [overleaf]

networks:
  overleaf:
