---
services:
  pdfding:
    profiles: [pdfding]
    image: mrmn/pdfding:latest
    container_name: pdfding
    restart: unless-stopped
    environment:
      HOST_NAME: pdfding.chenn.dev
      DEFAULT_THEME: dark
      DEFAULT_THEME_COLOR: green
      CSRF_COOKIE_SECURE: 'TRUE'
      SESSION_COOKIE_SECURE: 'TRUE'
      SECRET_KEY: ${PDFDING_SECRET}

      DATABASE_TYPE: POSTGRES
      POSTGRES_HOST: pdfding_db
      POSTGRES_NAME: pdfding
      POSTGRES_USER: pdfding
      POSTGRES_PASSWORD: pdfding

      OIDC_ENABLE: 'TRUE'
      OIDC_PROVIDER_NAME: 'Pocket ID'
      OIDC_CLIENT_ID: '${PDFDING_OIDC_CLIENT}'
      OIDC_CLIENT_SECRET: '${PDFDING_OIDC_SECRET}'
      OIDC_AUTH_URL: 'https://pocketid.chenn.dev/.well-known/openid-configuration'
      OIDC_ADMIN_GROUP: 'admin'
      OIDC_EXTRA_SCOPE: 'groups'
      OIDC_ONLY: 'TRUE'
      DISABLE_USER_SIGNUP: 'FALSE'

      EMAIL_BACKEND: SMTP
      EMAIL_ADDRESS: $SMTP_USER
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: 465
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_TOKEN
      SMTP_USE_SSL: 'TRUE'

    volumes:
      - $DATA/pdfding/data:/home/nonroot/pdfding/media
    networks: [pdfding, newt]
    labels:
      homepage.group: File Editors
      homepage.name: PDF Ding
      homepage.icon: pdfding.png
      homepage.href: https://pdfding.chenn.dev
      homepage.description: PDF Editing

      pangolin.public-resources.pdfding.name: pdfding
      pangolin.public-resources.pdfding.full-domain: pdfding.chenn.dev
      pangolin.public-resources.pdfding.protocol: http
      pangolin.public-resources.pdfding.ssl: true
      pangolin.public-resources.pdfding.targets[0].method: http
      pangolin.public-resources.pdfding.targets[0].port: 8000
      pangolin.public-resources.pdfding.auth.sso-enabled: true
      pangolin.public-resources.pdfding.auth.sso-roles[0]: Member
      pangolin.public-resources.pdfding.rules[0].action: pass
      pangolin.public-resources.pdfding.rules[0].match: country
      pangolin.public-resources.pdfding.rules[0].value: US
      pangolin.public-resources.pdfding.rules[1].action: deny
      pangolin.public-resources.pdfding.rules[1].match: country
      pangolin.public-resources.pdfding.rules[1].value: ALL

  pdfding_db:
    profiles: [pdfding]
    image: postgres:18-alpine
    container_name: pdfding_db
    restart: unless-stopped
    volumes:
      - $DATA/pdfding/db:/var/lib/postgresql
    environment:
      POSTGRES_DB: pdfding
      POSTGRES_USER: pdfding
      POSTGRES_PASSWORD: pdfding
      POSTGRES_PORT: 5432
    networks: [pdfding]

networks:
  pdfding:
