[secrets]
INVIDIOUS_VISITOR = { provider = "op", value = "op://homelab/invidious/visitor" }
INVIDIOUS_TOKEN = { provider = "op", value = "op://homelab/invidious/token" }

TWINGATE_NETWORK = { provider = "op", value = "op://homelab/twingate/network" }
TWINGATE_ACCESS_TOKEN = { provider = "op", value = "op://homelab/twingate/access_token_2" }
TWINGATE_REFRESH_TOKEN = { provider = "op", value = "op://homelab/twingate/refresh_token_2" }
TWINGATE_LABEL_HOSTNAME = { provider = "op", value = "op://homelab/twingate/label_hostname" }
TWINGATE_LABEL_DEPLOYED_BY = { provider = "op", value = "op://homelab/twingate/deployed_by" }

OPENSIGN_PFX = { provider = "op", value = "op://homelab/Opensign/pfx"}
OPENSIGN_PFX_PASS = { provider = "op", value = "op://homelab/Opensign/pfx_pass"}

SEAFILE_SECRET = { provider = "op", value = "op://homelab/seafile/secret" }
SEAFILE_SECRET_KEY = { provider = "op", value = "op://homelab/seafile/secret_key" }
SEAFILE_PASS = { provider = "op", value = "op://homelab/seafile/password" }
SEAFILE_OIDC_CLIENT = { provider = "op", value = "op://homelab/seafile/oidc_client" }
SEAFILE_OIDC_SECRET = { provider = "op", value = "op://homelab/seafile/oidc_secret" }

CLOUDREVE_MEILI_MASTER_KEY = { provider = "op", value = "op://homelab/cloudreve/meili_key" }

NEXTCLOUD_HARP_KEY = { provider = "op", value = "op://homelab/Nextcloud/harp_key" }
