[tools]
helm = "latest"
k9s = "latest"
kubectl = "latest"
pulumi = "latest"
talosctl = "latest"
uv = "latest"

[env]
node0 = "192.168.1.29"
node1 = "192.168.1.30"

KUBECONFIG = "{{'./.secrets/dev/kubeconfig' | absolute}}"
TALOSCONFIG = "{{'./.secrets/dev/talosconfig' | absolute}}"
