[tools]
helm = "latest"
k9s = "latest"
kubectl = "latest"
pulumi = "latest"
sd = "latest"
talosctl = "latest"
uv = "latest"

[env]
rack3 = "192.168.1.29"
rack2 = "192.168.1.30"

KUBECONFIG = "{{'./.secrets/dev/kubeconfig' | absolute}}"
TALOSCONFIG = "{{'./.secrets/dev/talosconfig' | absolute}}"

[settings]
python.uv_venv_auto = "create|source"

[tasks.secrets]
description = "render k8s secrets to secrets.yaml"
run = "fnox export --format yaml > secrets.yaml"
