# logout has a known bug right now https://github.com/jordan-dalby/ByteStash/issues/325
---
services:
  bytestash:
    profiles: [bytestash]
    image: ghcr.io/jordan-dalby/bytestash:latest
    container_name: bytestash
    restart: unless-stopped
    volumes:
      - $DATA/bytestash:/data/snippets
    environment:
      ALLOWED_HOSTS: localhost,stash.chenn.dev
      BASE_PATH: ''
      JWT_SECRET: ${BYTESTASH_JWT_SECRET}
      TOKEN_EXPIRY: 24h
      NODE_ENV: production
      DEBUG: false

      ALLOW_NEW_ACCOUNTS: true
      DISABLE_ACCOUNTS: false
      DISABLE_INTERNAL_ACCOUNTS: false

      OIDC_ENABLED: true
      OIDC_DISPLAY_NAME: PocketID
      OIDC_ISSUER_URL: $OIDC
      OIDC_CLIENT_ID: $BYTESTASH_OIDC_CLIENT
      OIDC_CLIENT_SECRET: $BYTESTASH_OIDC_SECRET

    networks: [newt]
    labels:
      homepage.group: Development Tools
      homepage.name: ByteStash
      homepage.icon: bytestash.png
      homepage.href: https://stash.chenn.dev
      homepage.description: Code Snippets

      pangolin.public-resources.stash.name: stash
      pangolin.public-resources.stash.full-domain: stash.chenn.dev
      pangolin.public-resources.stash.mode: http
      pangolin.public-resources.stash.targets[0].method: http
      pangolin.public-resources.stash.targets[0].port: 5000
      pangolin.public-resources.stash.policy: member
