---
services:
  chartdb:
    profiles: [chartdb]
    image: ghcr.io/chartdb/chartdb:latest
    container_name: chartdb
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Development Tools
      homepage.name: Chartdb
      homepage.icon: chart-db.png
      homepage.href: https://chart.chenn.dev
      homepage.description: Database Doodler

      pangolin.public-resources.chartdb.name: chartdb
      pangolin.public-resources.chartdb.full-domain: chart.chenn.dev
      pangolin.public-resources.chartdb.mode: http
      pangolin.public-resources.chartdb.targets[0].method: http
      pangolin.public-resources.chartdb.targets[0].port: 80
      pangolin.public-resources.chartdb.policy: member
