---
services:
  cyberchef:
    profiles: [cyberchef]
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Development Tools
      homepage.name: Cyberchef
      homepage.icon: cyberchef.png
      homepage.href: https://cyberchef.chenn.dev
      homepage.description: Cyber Security Tools

      pangolin.public-resources.cyberchef.name: cyberchef
      pangolin.public-resources.cyberchef.full-domain: cyberchef.chenn.dev
      pangolin.public-resources.cyberchef.mode: http
      pangolin.public-resources.cyberchef.targets[0].method: http
      pangolin.public-resources.cyberchef.targets[0].port: 8080
      pangolin.public-resources.cyberchef.policy: member
