---
services:
  cyberchef:
    profiles: [cyberchef]
    image: ghcr.io/gchq/cyberchef:latest
    container_name: cyberchef
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Development Tools
      homepage.name: Cyberchef
      homepage.icon: cyberchef.png
      homepage.href: https://cyberchef.chenn.dev
      homepage.description: Cyber Security Tools

      pangolin.public-resources.cyberchef.name: cyberchef
      pangolin.public-resources.cyberchef.full-domain: cyberchef.chenn.dev
      pangolin.public-resources.cyberchef.protocol: http
      pangolin.public-resources.cyberchef.ssl: true
      pangolin.public-resources.cyberchef.targets[0].method: http
      pangolin.public-resources.cyberchef.targets[0].port: 8080
      pangolin.public-resources.cyberchef.auth.sso-enabled: true
      pangolin.public-resources.cyberchef.auth.sso-roles[0]: Member
      pangolin.public-resources.cyberchef.rules[0].action: pass
      pangolin.public-resources.cyberchef.rules[0].match: country
      pangolin.public-resources.cyberchef.rules[0].value: US
      pangolin.public-resources.cyberchef.rules[1].action: deny
      pangolin.public-resources.cyberchef.rules[1].match: country
      pangolin.public-resources.cyberchef.rules[1].value: ALL
