---
services:
  databasus:
    profiles: [databasus]
    image: databasus/databasus:latest
    container_name: databasus
    restart: unless-stopped
    volumes:
      - $DATA/databasus/data:/databasus-data
    networks: [newt]
    labels:
      homepage.group: Dev
      homepage.name: Databasus
      homepage.icon: databasus.png
      homepage.href: https://databasus.chenn.dev
      homepage.description: Database Backup GUI
      
      pangolin.public-resources.databasus.name: databasus
      pangolin.public-resources.databasus.full-domain: databasus.chenn.dev
      pangolin.public-resources.databasus.protocol: http
      pangolin.public-resources.databasus.ssl: true
      pangolin.public-resources.databasus.targets[0].method: http
      pangolin.public-resources.databasus.targets[0].port: 4005
      pangolin.public-resources.databasus.auth.sso-enabled: true
      pangolin.public-resources.databasus.auth.sso-users[0]: ${EMAIL}
      pangolin.public-resources.databasus.rules[0].action: pass
      pangolin.public-resources.databasus.rules[0].match: country
      pangolin.public-resources.databasus.rules[0].value: US
      pangolin.public-resources.databasus.rules[0].priority: 0
      pangolin.public-resources.databasus.rules[1].action: deny
      pangolin.public-resources.databasus.rules[1].match: country
      pangolin.public-resources.databasus.rules[1].value: ALL
      pangolin.public-resources.databasus.rules[1].priority: 10
