---
services:
  ittools:
    profiles: [ittools]
    image: corentinth/it-tools:latest
    container_name: ittools
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Development Tools
      homepage.name: IT-Tools
      homepage.icon: it-tools.png
      homepage.href: https://ittools.chenn.dev
      homepage.description: Code Calculators

      pangolin.public-resources.ittools.name: ittools
      pangolin.public-resources.ittools.full-domain: ittools.chenn.dev
      pangolin.public-resources.ittools.mode: http
      pangolin.public-resources.ittools.targets[0].method: http
      pangolin.public-resources.ittools.targets[0].port: 80
      pangolin.public-resources.ittools.policy: member
