---
services:
  scanopy:
    profiles: [scanopy]
    image: ghcr.io/scanopy/scanopy/server:latest
    container_name: scanopy
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SCANOPY_PUBLIC_URL: https://scanopy.chenn.dev
      SCANOPY_LOG_LEVEL: info
      SCANOPY_DATABASE_URL: postgresql://postgres:postgres@scanopy_db:5432/scanopy
      SCANOPY_WEB_EXTERNAL_PATH: /app/static
      SCANOPY_INTEGRATED_DAEMON_URL: http://host.docker.internal:60073
    volumes:
      - $DATA/scanopy/data:/data
    depends_on:
      scanopy_db:
        condition: service_healthy
      scanopy_daemon:
        condition: service_started
    networks: [scanopy, newt]
    labels:
      homepage.group: Dev
      homepage.name: Scanopy
      homepage.icon: scanopy.png
      homepage.href: https://scanopy.chenn.dev
      homepage.description: Network Mapper

      pangolin.public-resources.scanopy.name: scanopy
      pangolin.public-resources.scanopy.full-domain: scanopy.chenn.dev
      pangolin.public-resources.scanopy.protocol: http
      pangolin.public-resources.scanopy.ssl: true
      pangolin.public-resources.scanopy.targets[0].method: http
      pangolin.public-resources.scanopy.targets[0].port: 60072
      pangolin.public-resources.scanopy.auth.sso-enabled: true

      pangolin.public-resources.scanopy.rules[0].action: allow
      pangolin.public-resources.scanopy.rules[0].match: path
      pangolin.public-resources.scanopy.rules[0].value: /api/*
      pangolin.public-resources.scanopy.rules[0].priority: 0

      pangolin.public-resources.scanopy.rules[1].action: pass
      pangolin.public-resources.scanopy.rules[1].match: country
      pangolin.public-resources.scanopy.rules[1].value: US
      pangolin.public-resources.scanopy.rules[1].priority: 10

      pangolin.public-resources.scanopy.rules[2].action: deny
      pangolin.public-resources.scanopy.rules[2].match: country
      pangolin.public-resources.scanopy.rules[2].value: ALL
      pangolin.public-resources.scanopy.rules[2].priority: 20

  scanopy_daemon:
    profiles: [scanopy]
    image: ghcr.io/scanopy/scanopy/daemon:latest
    container_name: scanopy_daemon
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      SCANOPY_SERVER_URL: https://scanopy.chenn.dev
      SCANOPY_NETWORK_ID: 435b1412-8212-4ca4-a6ce-845e6c07aa87
      SCANOPY_DAEMON_API_KEY: scp_d_FHzPgIFreZK7e09dabAn7N1S4RP7Le9u
      SCANOPY_USER_ID: f6f81b1b-e877-4981-95d8-3c8d16757c66
      SCANOPY_NAME: scanopy-daemon-homelab
      SCANOPY_MODE: daemon_poll
      SCANOPY_LOG_FILE: /var/log/scanopy/scanopy-daemon-homelab.log
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:60073/api/health || exit 1']
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA/scanopy/daemon:/root/.config/daemon

  scanopy_db:
    profiles: [scanopy]
    image: postgres:18-alpine
    container_name: scanopy_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: scanopy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - $DATA/scanopy/db:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [scanopy]

networks:
  scanopy:
