additionalArguments:
  - '--log.level=INFO'
  - '--serversTransport.insecureSkipVerify=true'

deployment:
  replicas: 2

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
          topologyKey: kubernetes.io/hostname

#podDisruptionBudget:
#  enabled: true
#  minAvailable: 1

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.200
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    port: 8000
    exposedPort: 80
    expose:
      default: true
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    port: 8443
    exposedPort: 443
    expose:
      default: true
    protocol: TCP
    http3:
      enabled: true
    http:
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedBackSlash: true
        allowEncodedNullCharacter: true
        allowEncodedSemicolon: true
        allowEncodedPercent: true
        allowEncodedQuestionMark: true
        allowEncodedHash: true
      tls:
        enabled: true
    transport:
      respondingTimeouts:
        readTimeout: '30m'
        writeTimeout: '30m'
        idleTimeout: '30m'

#metrics:
#  prometheus:
#  prometheus:
#    entryPoint: traefik
#    service:
#      enabled: true
#    serviceMonitor:
#      enabled: true
#      interval: 30s
#      additionalLabels:
#        release: prometheus
