# seems to work ok. UI's a little crunchy compared with qbit

# sudo chown -R 1000:1001 $DATA/flood

# first login, create user, add rtorrent at socket path:
# /config/.local/share/rtorrent/rtorrent.sock
---
configs:
  rtorrent:
    content: |
      import = /etc/rtorrent/rtorrent.rc
      network.port_range.set = 6881-6881
      system.daemon.set = true

services:
  flood:
    profiles: [flood]
    image: jesec/flood
    container_name: flood
    restart: unless-stopped
    user: 1000:1001
    command: --port 3000 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - $DATA/flood/data:/data
      - $DATA/flood/config:/config
    networks: [flood, newt]
    labels:
      homepage.group: Download
      homepage.name: Flood
      homepage.icon: flood.png
      homepage.href: https://flood.chenn.dev
      homepage.description: Torrent Client

      pangolin.public-resources.flood.name: flood
      pangolin.public-resources.flood.full-domain: flood.chenn.dev
      pangolin.public-resources.flood.protocol: http
      pangolin.public-resources.flood.ssl: true
      pangolin.public-resources.flood.targets[0].method: http
      pangolin.public-resources.flood.targets[0].port: 3000
      pangolin.public-resources.flood.auth.sso-enabled: true
      pangolin.public-resources.flood.auth.sso-roles[0]: Member
      pangolin.public-resources.flood.rules[0].action: pass
      pangolin.public-resources.flood.rules[0].match: country
      pangolin.public-resources.flood.rules[0].value: US
      pangolin.public-resources.flood.rules[1].action: deny
      pangolin.public-resources.flood.rules[1].match: country
      pangolin.public-resources.flood.rules[1].value: ALL

  rtorrent:
    profiles: [flood]
    image: jesec/rtorrent
    container_name: rtorrent
    restart: unless-stopped
    user: 1000:1001
    environment:
      HOME: /config
    configs:
      - source: rtorrent
        target: /config/.rtorrent.rc
    volumes:
      - $DATA/flood/data:/data
      - $DATA/flood/config:/config
    ports:
      - '6881:6881'
    networks: [flood]

networks:
  flood:
