---
services:
  actual:
    profiles: [actual]
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    environment:
      ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: 200
      ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: 500
      ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: 200
    volumes:
      - $DATA/actualbudget:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
    networks: [traefik]
    labels:
      homepage.instance.private.group: Tools
      homepage.instance.private.name: Actual Budget
      homepage.instance.private.icon: actual-budget.png
      homepage.instance.private.href: https://actual.henn.dev
      homepage.instance.private.description: Budgeting

      traefik.enable: true
      traefik.http.routers.actual.rule: Host(`actual.henn.dev`)
      traefik.http.routers.actual.entrypoints: websecure
      traefik.http.routers.actual.middlewares: hdrs@file
      traefik.http.routers.actual.tls.certresolver: cf
      traefik.http.services.actual.loadbalancer.server.port: 5006
