---
services:
  fileflow:
    profiles: [fileflow]
    image: revenz/fileflows
    container_name: fileflow
    restart: unless-stopped
    runtime: nvidia
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NVIDIA_DRIVER_CAPABILITIES: compute, video, utility
      NVIDIA_VISIBLE_DEVICES: all
      FF_EULA_ACCEPTED: Yes

      SmtpServer: $SMTP_HOST
      SmtpPort: 465
      SmtpSecurity: SSL
      SmtpFrom: $SMTP_USER
      SmtpFromAddress: $SMTP_USER
      SmtpUser: $SMTP_USER
      SmtpPassword: $SMTP_TOKEN

      OidcAuthority: $OIDC
      OidcClientId: ${FILEFLOW_OIDC_CLIENT}
      OidcClientSecret: ${FILEFLOW_OIDC_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA/fileflow/data:/app/Data
      - $DATA/fileflow/temp:/temp
    networks: [newt]
    labels:
      homepage.group: Tools
      homepage.name: Fileflow
      homepage.icon: fileflows.png
      homepage.href: https://fileflow.chenn.dev
      homepage.description: Automatic File Flows

      pangolin.public-resources.fileflow.name: fileflow
      pangolin.public-resources.fileflow.full-domain: fileflow.chenn.dev
      pangolin.public-resources.fileflow.protocol: http
      pangolin.public-resources.fileflow.ssl: true
      pangolin.public-resources.fileflow.targets[0].method: http
      pangolin.public-resources.fileflow.targets[0].port: 5000
      pangolin.public-resources.fileflow.auth.sso-enabled: true
      pangolin.public-resources.fileflow.auth.sso-roles[0]: Member
      pangolin.public-resources.fileflow.rules[0].action: pass
      pangolin.public-resources.fileflow.rules[0].match: country
      pangolin.public-resources.fileflow.rules[0].value: US
      pangolin.public-resources.fileflow.rules[1].action: deny
      pangolin.public-resources.fileflow.rules[1].match: country
      pangolin.public-resources.fileflow.rules[1].value: ALL
