# sudo chown -R 1000:1000 $DATA/gocron/config
---
configs:
  gocron:
    content: |
      delete_runs_after_days: 7
      healthcheck:
        type: POST
      jobs: []
      log_level: info
      server:
        address: 0.0.0.0
        port: 8156
      terminal:
        allow_all_commands: true
      time_zone: America/Chicago

services:
  gocron:
    profiles: [gocron]
    image: ghcr.io/flohoss/gocron:latest
    restart: unless-stopped
    container_name: gocron
    hostname: gocron
    user: $PUID:$PGID
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      gocron_URL: https://gocron.chenn.dev
      gocron_TOPIC: cron
      gocron_TOKEN:
    configs:
      - source: gocron
        target: /app/config/config.yaml
    volumes:
      - $DATA/gocron/config:/app/config
    networks: [newt]
    labels:
      homepage.group: General Tools
      homepage.name: Go Cron
      homepage.icon: chronograf.png
      homepage.href: https://cron.henn.dev
      homepage.description: Go Cron

      pangolin.public-resources.gocron.name: gocron
      pangolin.public-resources.gocron.full-domain: gocron.chenn.dev
      pangolin.public-resources.gocron.mode: http
      pangolin.public-resources.gocron.targets[0].method: http
      pangolin.public-resources.gocron.targets[0].port: 8156
      pangolin.public-resources.gocron.policy: member
