---
services:
  homebox:
    profiles: [homebox]
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - $DATA/homebox/data:/data
    networks: [newt]
    labels:
      homepage.group: Tools
      homepage.name: Homebox
      homepage.icon: homebox.png
      homepage.href: https://homebox.chenn.dev
      homepage.description: Home Inventory

      pangolin.public-resources.homebox.name: homebox
      pangolin.public-resources.homebox.full-domain: homebox.chenn.dev
      pangolin.public-resources.homebox.protocol: http
      pangolin.public-resources.homebox.ssl: true
      pangolin.public-resources.homebox.targets[0].method: http
      pangolin.public-resources.homebox.targets[0].port: 7745
      pangolin.public-resources.homebox.auth.sso-enabled: true
      pangolin.public-resources.homebox.auth.sso-roles[0]: Member
      pangolin.public-resources.homebox.rules[0].action: pass
      pangolin.public-resources.homebox.rules[0].match: country
      pangolin.public-resources.homebox.rules[0].value: US
      pangolin.public-resources.homebox.rules[1].action: deny
      pangolin.public-resources.homebox.rules[1].match: country
      pangolin.public-resources.homebox.rules[1].value: ALL
