---
services:
  win-builder:
    image: christianhenn/win-builder:latest
    build: .
    container_name: win-builder
    volumes:
      - C:\project:C:\project
    network_mode: nat
    working_dir: C:\project
    restart: no
    cpus: 12
    hostname: win-builder
    mem_limit: 32g
