services:
  al2023:
    image: test-al2023
    build:
      context: .
      dockerfile: al2023.docker
    container_name: test-al2023
    restart: 'no'
    hostname: test-al2023
    privileged: true

  alma:
    image: test-alma
    build:
      context: .
      dockerfile: alma.docker
    container_name: test-alma
    restart: 'no'
    hostname: test-alma
    privileged: true

  # NOTE: big big danger below. Testing only!
  debian:
    image: test-debian
    build:
      context: .
      dockerfile: debian.docker
    container_name: test-debian
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    restart: 'no'

    cgroup: host
    hostname: test-debian
    privileged: true
    tmpfs:
      - /run
      - /run/lock

  rhel:
    image: test-rhel
    build:
      context: .
      dockerfile: rhel.docker
    container_name: test-rhel
    restart: 'no'
    hostname: test-rhel
    privileged: true
  ubuntu:
    image: test-ubuntu
    build:
      context: .
      dockerfile: ubuntu.docker
    container_name: test-ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    restart: 'no'

    cgroup: host
    hostname: test-ubuntu
    privileged: true
    tmpfs:
      - /run
      - /run/lock
