rtc:
  use_external_ip: true
  port_range_start: 50000
  port_range_end: 50010
  tcp_port: 7881

redis:
  address: redis:6379

turn:
  enabled: false

keys:
  97027397e4b2: a5f4e1585313e567b8e9c552d1c601e275f590904ca39ecc

webhook:
  api_key: 97027397e4b2
  urls:
    - 'http://voice-ingress:8500/worldwide'
