# android app can only view text files, no native editing
# generally less featureful than nextcloud
# web editing autosave is set to 120 seconds. What is this, 2002? no thanks
# default user: "admin"
# mkdir -p $DATA/ocis/config $DATA/ocis/data
---
services:
  ocis:
    profiles: [ocis]
    image: owncloud/ocis:latest
    container_name: ocis
    restart: unless-stopped
    entrypoint:
      - /bin/sh
    command: ['-c', 'ocis init || true; exec ocis server']
    environment:
      OCIS_ADD_RUN_SERVICES: notifications
      OCIS_URL: https://ocis.henn.dev
      OCIS_LOG_LEVEL: info
      OCIS_LOG_COLOR: true
      OCIS_LOG_PRETTY: true
      OCIS_INSECURE: false
      OCIS_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      IDM_ADMIN_PASSWORD: ${PASS}
      IDM_CREATE_DEMO_USERS: false
      NOTIFICATIONS_SMTP_HOST: ${SMTP_HOST}
      NOTIFICATIONS_SMTP_PORT: 587
      NOTIFICATIONS_SMTP_SENDER: ${SMTP_USER}
      NOTIFICATIONS_SMTP_USERNAME: ${SMTP_USER}
      NOTIFICATIONS_SMTP_INSECURE: false
      PROXY_TLS: false
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      PROXY_ENABLE_BASIC_AUTH: false
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      COLLABORA_DOMAIN: collabora.henn.dev

      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://ocis_tika:9998
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: true

      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: com.owncloud.api.collaboration.CollaboraOnline
      GRAPH_AVAILABLE_ROLES: 'b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6'
    volumes:
      - ./ocis/app-registry.yaml:/etc/ocis/app-registry.yaml
      - ./ocis/csp.yaml:/etc/ocis/csp.yaml
      - ./ocis/banned-password-list.txt:/etc/ocis/banned-password-list.txt
      - $DATA/ocis/config:/etc/ocis
      - $DATA/ocis/data:/var/lib/ocis
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.owncloud.rule: Host(`ocis.henn.dev`)
      traefik.http.routers.owncloud.entrypoints: websecure
      traefik.http.routers.owncloud.tls.certresolver: cf
      traefik.http.services.owncloud.loadbalancer.server.port: 9200

  ocis_tika:
    profiles: [ocis]
    image: apache/tika:latest
    container_name: ocis_tika
    restart: unless-stopped
    networks: [traefik]

  ocis_collab:
    profiles: [ocis]
    image: owncloud/ocis:latest
    container_name: ocis_collab
    restart: unless-stopped
    command: ['collaboration', 'server']
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: 'nats-js-kv'
      MICRO_REGISTRY_ADDRESS: 'ocis:9233'
      COLLABORATION_WOPI_SRC: http://ocis_collab:9300
      COLLABORATION_APP_NAME: 'CollaboraOnline'
      COLLABORATION_APP_PRODUCT: 'Collabora'
      COLLABORATION_APP_ADDR: https://collabora.henn.dev
      COLLABORATION_APP_ICON: https://collabora.henn.dev/favicon.ico
      COLLABORATION_APP_INSECURE: true
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: true
      COLLABORATION_LOG_LEVEL: info
      OCIS_URL: https://ocis.henn.dev
    volumes:
      - $DATA/ocis/config:/etc/ocis

    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.collaboration.rule: Host(`collaboration`)
      traefik.http.routers.collaboration.entrypoints: web
      traefik.http.services.collaboration.loadbalancer.server.port: 9300

  ocis_collabora:
    profiles: [ocis]
    image: collabora/code:latest
    container_name: ocis_collabora
    restart: unless-stopped
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    environment:
      DONT_GEN_SSL_CERT: YES
      extra_params: |
        --o:ssl.enable=${COLLABORA_SSL_ENABLE:-true} \
        --o:ssl.ssl_verification=${COLLABORA_SSL_VERIFICATION:-true} \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=ocis.henn.dev
      username: ${USER}
      password: ${PASS}
    cap_add:
      - MKNOD
    healthcheck:
      test: ['CMD', 'bash', '-c', "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"]

    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.collabora.rule: Host(`collabora.henn.dev`)
      traefik.http.routers.collabora.entrypoints: websecure
      traefik.http.routers.collabora.tls.certresolver: cf
      traefik.http.services.collabora.loadbalancer.server.port: 9980
