---
services:
  openresume:
    profiles: [openresume]
    image: ${REGISTRY}/openresume:latest
    build: https://github.com/xitanggg/open-resume.git
    container_name: openresume
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: File Editors
      homepage.name: openresume
      homepage.icon: open-resume.png
      homepage.href: https://openresume.chenn.dev
      homepage.description: Resume Generator

      pangolin.public-resources.openresume.name: openresume
      pangolin.public-resources.openresume.full-domain: openresume.chenn.dev
      pangolin.public-resources.openresume.protocol: http
      pangolin.public-resources.openresume.ssl: true
      pangolin.public-resources.openresume.targets[0].method: http
      pangolin.public-resources.openresume.targets[0].port: 3000
      pangolin.public-resources.openresume.auth.sso-enabled: true
      pangolin.public-resources.openresume.auth.sso-roles[0]: Member

      pangolin.public-resources.openresume.rules[0].action: pass
      pangolin.public-resources.openresume.rules[0].match: country
      pangolin.public-resources.openresume.rules[0].value: US
      pangolin.public-resources.openresume.rules[1].action: deny
      pangolin.public-resources.openresume.rules[1].match: country
      pangolin.public-resources.openresume.rules[1].value: ALL
