---
services:
  windows-11:
    image: dockurr/windows:latest
    container_name: windows-11
    volumes:
      - /home/chris/dockurr/win11:/storage
    environment:
      VERSION: win11x64
      RAM_SIZE: 16G
      CPU_CORES: '8'
    ports:
      - '3389:3389/tcp'
      - '3389:3389/udp'
      - '8006:8006'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m
  windows-7:
    image: chrishenn/dockurr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: windows-7
    volumes:
      - /home/chris/dockurr/win7:/storage
    environment:
      VERSION: win7x64-ultimate
      RAM_SIZE: 16G
      CPU_CORES: '8'
    ports:
      - '3389:3389/tcp'
      - '3389:3389/udp'
      - '8006:8006'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m
  windows-81:
    image: chrishenn/dockurr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: windows-81
    volumes:
      - /home/chris/dockurr/win81:/storage
    environment:
      VERSION: win81x64
      RAM_SIZE: 16G
      CPU_CORES: '8'
    ports:
      - '3389:3389/tcp'
      - '3389:3389/udp'
      - '8006:8006'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m
