[secrets]
CLOUDFLARE_API_TOKEN = { provider = "op", value = "op://homelab/cloudflare/token" }
HOSTINGER_API_TOKEN = { provider = "op", value = "op://homelab/hostinger/token" }
ZONEID = { provider = "op", value = "op://homelab/cloudflare/zoneid/chenndev" }

PANGOLIN_SERVER_SECRET = { provider = "op", value = "op://homelab/vps0/pangolin_server_secret" }

VPS0_BESZEL_KEY = { provider = "op", value = "op://homelab/vps0/beszel_key" }
VPS0_BESZEL_TOKEN = { provider = "op", value = "op://homelab/vps0/beszel_token" }
VPS0_BESZEL_HUB_URL = { provider = "op", value = "op://homelab/vps0/beszel_hub_url" }
VPS0_CHRIS_PASS = { provider = "op", value = "op://homelab/vps0/chris_pass" }
