[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
CLOUDFLARE_API_TOKEN = { provider = "onepass", value = "op://homelab/cloudflare/token" }
ZONEID = { provider = "onepass", value = "op://homelab/cloudflare/zoneid/chenndev" }

PANGOLIN_SERVER_SECRET = { provider = "onepass", value = "op://homelab/vps0/pangolin_server_secret" }

VPS0_BESZEL_KEY = { provider = "onepass", value = "op://homelab/vps0/beszel_key" }
VPS0_BESZEL_TOKEN = { provider = "onepass", value = "op://homelab/vps0/beszel_token" }
VPS0_BESZEL_HUB_URL = { provider = "onepass", value = "op://homelab/vps0/beszel_hub_url" }
