set fallback
alias a := attach
alias b := bounce
alias f := follow
alias s := sync
alias p := ps
alias u := up
alias d := down

# 'repo' is the repo location on the remote host
repo := "/home/chris/Projects/homelab"

[arg("pty", long="pty", short="p")]
ssh cmd='' pty='true':
    just vps0 {{ if cmd != '' {f'"{{cmd}}"'} else {''} }} -p={{pty}}

backup:
    just ssh 'cd $DIR_HOST && sudo rm -rf pangolin_backup && sudo cp -r pangolin pangolin_backup'

# generic

sync message="sync":
    git commit -a -m '{{ message }}' || true && git pull && git push
    just ssh 'cd {{ repo }} && git commit -a -m '{{ message }}' || true && git pull && git push'

ssync:
    fnox sync --provider age --config fnox.local.toml -f

up *svcs:
    docker compose up -d --remove-orphans {{ svcs }}

down *svcs:
    docker compose down {{ svcs }}

bounce *svcs:
    just down {{ svcs }}
    just up {{ svcs }}

pullup *svcs:
    docker compose up -d --remove-orphans --force-recreate --pull always {{ svcs }}

attach svc cmd="/bin/sh":
    docker compose exec -it {{ svc }} {{ cmd }}

ps *svcs:
    docker compose ps {{ svcs }}

log *args:
    docker compose logs {{ args }}

follow *args:
    just log -f {{ args }}
