set fallback
alias a := attach
alias b := bounce
alias f := follow
alias s := sync
alias p := ps
alias u := up
alias d := down
profile := "'*'"

# 'repo' is the repo location on the remote host
repo := "/home/chris/Projects/homelab"

[arg("pty", long="pty", short="p")]
ssh cmd='' pty='true':
    just vps0 {{ if cmd != '' {f'"{{cmd}}"'} else {''} }} -p={{pty}}

backup_cmd := """
sudo rm -rf $DIR_HOST/pangolin_backup && sudo cp -r $DIR_HOST/pangolin $DIR_HOST/pangolin_backup \
&& sudo rm -rf $BACKUP && sudo cp -r $DATA $BACKUP
"""

backup:
    just ssh '{{backup_cmd}}'

# generic

sync message="sync":
    git commit -a -m '{{ message }}' || true && git pull && git push
    just ssh 'cd {{ repo }} && git commit -a -m '{{ message }}' || true && git pull && git push'

up profile=profile *svcs:
    docker compose --profile {{ profile }} up -d --remove-orphans {{ svcs }}

down profile=profile *svcs:
    docker compose --profile {{ profile }} down {{ svcs }}

bounce profile=profile *svcs:
    #!/bin/bash
    docker compose --profile {{ profile }} down {{ svcs }} && \
    docker compose --profile {{ profile }} up -d --remove-orphans {{ svcs }}

pullup profile=profile *svcs:
    docker compose --profile {{ profile }} up -d --remove-orphans --force-recreate --pull always {{ svcs }}

attach svc cmd="/bin/sh":
    docker compose exec -it {{ svc }} {{ cmd }}

ps *svcs:
    docker compose ps {{ svcs }}

log *args:
    docker compose logs {{ args }}

follow *args:
    just log -f {{ args }}

# secret sync
ss:
    fnox sync --provider age --local-file -f
