[settings]
python.uv_venv_auto = "create|source"

[tools]
fnox = "latest"
pulumi = "latest"
uv = "latest"

[env]
DOCKER_HOST = "ssh://chris@${VPS0_IP}:2200"
DIR_HOST = "/home/chris/Projects/homelab/vps0"