---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  replicas: 1

  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma

    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1-alpine
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '250m'
          env:
            - name: UPTIME_KUMA_PORT
              value: '3000'
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-content

      #        securityContext:
      #          allowPrivilegeEscalation: false
      #          capabilities:
      #            drop: [ALL]
      #          runAsNonRoot: true
      #          seccompProfile:
      #            type: RuntimeDefault

      volumes:
        - name: uptime-kuma-content
          persistentVolumeClaim:
            claimName: uptime-kuma-claim

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  selector:
    app: uptime-kuma
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kuma
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kuma.chenn.io`)
      kind: Rule
      services:
        - name: uptime-kuma
          port: 3000
      middlewares:
        - name: shdr
  tls:
    secretName: chennio-cert
