# fork of calibre-web. claims to support OIDC but I don't see the config doc for how
# admin/admin123
autocaliweb:
  profiles: [calibre]
  image: gelbphoenix/autocaliweb:latest
  container_name: autocaliweb
  restart: unless-stopped
  environment:
    TZ: $TZ
    PUID: $PUID
    PGID: $PGID
  volumes:
    - $DATA/autocaliweb/config:/config
    - $DATA/autocaliweb/ingest:/acw-book-ingest
    - $DATA/autocaliweb/library:/calibre-library
  networks: [newt]
  labels:
    homepage.group: Media
    homepage.name: Autocaliweb
    homepage.icon: https://codeberg.org/gelbphoenix/autocaliweb/raw/branch/main/cps/static/favicon.ico
    homepage.href: https://autocaliweb.chenn.dev
    homepage.description: Book Server

    pangolin.public-resources.autocaliweb.name: autocaliweb
    pangolin.public-resources.autocaliweb.full-domain: autocaliweb.chenn.dev
    pangolin.public-resources.autocaliweb.protocol: http
    pangolin.public-resources.autocaliweb.ssl: true
    pangolin.public-resources.autocaliweb.targets[0].method: http
    pangolin.public-resources.autocaliweb.targets[0].port: 8083
    pangolin.public-resources.autocaliweb.auth.sso-enabled: true
    pangolin.public-resources.autocaliweb.auth.sso-roles[0]: Member
    pangolin.public-resources.autocaliweb.rules[0].action: pass
    pangolin.public-resources.autocaliweb.rules[0].match: country
    pangolin.public-resources.autocaliweb.rules[0].value: US
    pangolin.public-resources.autocaliweb.rules[1].action: deny
    pangolin.public-resources.autocaliweb.rules[1].match: country
    pangolin.public-resources.autocaliweb.rules[1].value: ALL
