# very low arbitrary limits (around 3Gb/s) - openspeedtest is a little better
---
services:
  librespeed:
    profiles: [librespeed]
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $DATA/librespeed:/config
    labels:
      homepage.group: General Tools
      homepage.name: librespeed
      homepage.icon: librespeed.png
      homepage.href: http://$SVC_IP:3040
      homepage.description: Internet Speed test
    ports:
      - '$SVC_IP:3040:80'
