---
services:
  files:
    profiles: [files]
    image: gtstef/filebrowser:stable
    container_name: files
    restart: unless-stopped
    environment:
      FILEBROWSER_CONFIG: /config.yaml
      FILEBROWSER_ADMIN_PASSWORD: ${FILES_PASS}

      FILEBROWSER_OIDC_CLIENT_ID: ${FILES_OIDC_CLIENT}
      FILEBROWSER_OIDC_CLIENT_SECRET: ${FILES_OIDC_SECRET}
      FILEBROWSER_ONLYOFFICE_SECRET: ${FILES_SECRET}

    volumes:
      - ./files/config.yaml:/config.yaml
      - $DATA/files/data:/home/filebrowser/data
      - /mnt/k:/mnt/k
      - /mnt/h:/mnt/h
      - /mnt/q:/mnt/q
      - /mnt/f:/mnt/f
    networks: [files, newt]
    labels:
      homepage.group: File Servers
      homepage.name: Filebrowser Quantum
      homepage.icon: filebrowser-quantum.png
      homepage.href: https://files.chenn.dev
      homepage.description: File Server

      pangolin.public-resources.files.name: files
      pangolin.public-resources.files.full-domain: files.chenn.dev
      pangolin.public-resources.files.protocol: http
      pangolin.public-resources.files.ssl: true
      pangolin.public-resources.files.targets[0].method: http
      pangolin.public-resources.files.targets[0].port: 80
      pangolin.public-resources.files.auth.sso-enabled: true
      pangolin.public-resources.files.auth.sso-users[0]: ${EMAIL}
      pangolin.public-resources.files.rules[0].action: pass
      pangolin.public-resources.files.rules[0].match: country
      pangolin.public-resources.files.rules[0].value: US
      pangolin.public-resources.files.rules[0].priority: 0
      pangolin.public-resources.files.rules[1].action: deny
      pangolin.public-resources.files.rules[1].match: country
      pangolin.public-resources.files.rules[1].value: ALL
      pangolin.public-resources.files.rules[1].priority: 10

  office:
    profiles: [files]
    image: onlyoffice/documentserver:latest
    container_name: office
    restart: unless-stopped
    environment:
      JWT_ENABLED: true
      JWT_SECRET: ${FILES_SECRET}
    networks: [files, newt]
    labels:
      pangolin.public-resources.office.name: office
      pangolin.public-resources.office.full-domain: office.chenn.dev
      pangolin.public-resources.office.protocol: http
      pangolin.public-resources.office.ssl: true
      pangolin.public-resources.office.targets[0].method: http
      pangolin.public-resources.office.targets[0].port: 80
      pangolin.public-resources.office.rules[0].action: pass
      pangolin.public-resources.office.rules[0].match: country
      pangolin.public-resources.office.rules[0].value: US
      pangolin.public-resources.office.rules[0].priority: 0
      pangolin.public-resources.office.rules[1].action: deny
      pangolin.public-resources.office.rules[1].match: country
      pangolin.public-resources.office.rules[1].value: ALL
      pangolin.public-resources.office.rules[1].priority: 10

networks:
  files: