---
services:
  filebrowser:
    profiles: [filebrowser]
    image: gtstef/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    environment:
      TZ: $TZ
      FILEBROWSER_CONFIG: 'data/config.yaml'
    volumes:
      - ./filebrowser/config.yaml:/home/filebrowser/data/config.yaml
      - /mnt/k:/mnt/k
      - /mnt/h:/mnt/h
      - /mnt/q:/mnt/q
      - /mnt/f:/mnt/f
    networks: [newt]
    labels:
      homepage.group: Infra
      homepage.name: File Browser
      homepage.icon: filebrowser-quantum.png
      homepage.href: https://files.chenn.dev
      homepage.description: File Browser

      pangolin.public-resources.filebrowser.name: filebrowser
      pangolin.public-resources.filebrowser.full-domain: files.chenn.dev
      pangolin.public-resources.filebrowser.protocol: http
      pangolin.public-resources.filebrowser.ssl: true
      pangolin.public-resources.filebrowser.targets[0].method: http
      pangolin.public-resources.filebrowser.targets[0].port: 80
      pangolin.public-resources.filebrowser.auth.sso-enabled: true
      pangolin.public-resources.filebrowser.auth.sso-users[0]: ${EMAIL}
      pangolin.public-resources.filebrowser.rules[0].action: pass
      pangolin.public-resources.filebrowser.rules[0].match: country
      pangolin.public-resources.filebrowser.rules[0].value: US
      pangolin.public-resources.filebrowser.rules[0].priority: 0
      pangolin.public-resources.filebrowser.rules[1].action: deny
      pangolin.public-resources.filebrowser.rules[1].match: country
      pangolin.public-resources.filebrowser.rules[1].value: ALL
      pangolin.public-resources.filebrowser.rules[1].priority: 10
