---
services:
  syncin:
    profiles: [syncin]
    image: syncin/server:latest
    container_name: syncin
    restart: unless-stopped
    environment:
      SYNCIN_AUTH_ENCRYPTIONKEY: ${SYNCIN_ENCRYPTION_KEY}
      SYNCIN_AUTH_TOKEN_ACCESS_SECRET: ${SYNCIN_TOKEN_ACCESS_SECRET}
      SYNCIN_AUTH_TOKEN_REFRESH_SECRET: ${SYNCIN_TOKEN_REFRESH_SECRET}
      SYNCIN_SERVER_TRUSTPROXY: 1
      PUID: ${PUID}
      PGID: ${PGID}
      FORCE_PERMISSIONS: true
      INIT_ADMIN: false
      INIT_ADMIN_LOGIN: ${SYNCIN_USER}
      INIT_ADMIN_PASSWORD: ${SYNCIN_PASS}
      SYNCIN_MYSQL_URL: mysql://root:syncin@syncin_db:3306/syncin

      SYNCIN_APPLICATIONS_FILES_DATAPATH: /app/data
      SYNCIN_APPLICATIONS_FILES_COLLABORA_ENABLED: true
      SYNCIN_APPLICATIONS_FILES_ONLYOFFICE_ENABLED: false
      SYNCIN_APPLICATIONS_FILES_ONLYOFFICE_SECRET:

      SYNCIN_MAIL_HOST: $SMTP_HOST
      SYNCIN_MAIL_PORT: 465
      SYNCIN_MAIL_SENDER: $SMTP_USER
      SYNCIN_MAIL_AUTH_USER: $SMTP_USER
      SYNCIN_MAIL_AUTH_PASS: $SMTP_TOKEN
      SYNCIN_MAIL_SECURE: true
      SYNCIN_MAIL_REJECT_UNAUTHORIZED: true

      SYNCIN_OIDC_ISSUER_URL: https://pocketid.chenn.dev
      SYNCIN_OIDC_CLIENT_ID: ${SYNCIN_OIDC_CLIENT}
      SYNCIN_OIDC_CLIENT_SECRET: ${SYNCIN_OIDC_SECRET}
      SYNCIN_OIDC_REDIRECT_URI:
      SYNCIN_OIDC_OPTIONS_BUTTON_TEXT: Pocket ID
      SYNCIN_OIDC_OPTIONS_AUTO_CREATE_USER: true
      SYNCIN_OIDC_OPTIONS_AUTO_CREATE_PERMISSIONS: []
      SYNCIN_OIDC_OPTIONS_ADMIN_ROLE_OR_GROUP: admin
      SYNCIN_OIDC_OPTIONS_ENABLE_PASSWORD_AUTH: false
      SYNCIN_OIDC_OPTIONS_AUTO_REDIRECT: true
      SYNCIN_OIDC_SECURITY_SCOPE: openid email profile groups
      SYNCIN_OIDC_SECURITY_SUPPORT_PKCE: true
    volumes:
      - $DATA/syncin/data:/app/data
    networks: [syncin, newt]
    labels:
      pangolin.public-resources.syncin.name: syncin
      pangolin.public-resources.syncin.full-domain: syncin.chenn.dev
      pangolin.public-resources.syncin.protocol: http
      pangolin.public-resources.syncin.ssl: true

      pangolin.public-resources.syncin.targets[0].method: http
      pangolin.public-resources.syncin.targets[0].path-match: prefix
      pangolin.public-resources.syncin.targets[0].path: /
      pangolin.public-resources.syncin.targets[0].port: 8080
      pangolin.public-resources.syncin.targets[0].priority: 100

#      pangolin.public-resources.syncin.auth.sso-enabled: true
#      pangolin.public-resources.syncin.auth.sso-roles[0]: Member

      pangolin.public-resources.syncin.rules[0].action: pass
      pangolin.public-resources.syncin.rules[0].match: country
      pangolin.public-resources.syncin.rules[0].value: US
      pangolin.public-resources.syncin.rules[0].priority: 0
      pangolin.public-resources.syncin.rules[1].action: deny
      pangolin.public-resources.syncin.rules[1].match: country
      pangolin.public-resources.syncin.rules[1].value: ALL
      pangolin.public-resources.syncin.rules[1].priority: 10

  syncin_db:
    profiles: [syncin]
    image: mariadb:11
    container_name: syncin_db
    restart: unless-stopped
    command: --innodb_ft_cache_size=16000000 --max-allowed-packet=1G
    environment:
      MYSQL_ROOT_PASSWORD: syncin
      MYSQL_DATABASE: syncin
    volumes:
      - $DATA/syncin/db:/var/lib/mysql
    networks: [syncin]

  syncin_collabora:
    profiles: [syncin]
    image: collabora/code:latest
    container_name: syncin_collabora
    restart: unless-stopped
    environment:
      extra_params: >-
        --o:ssl.enable=false
        --o:ssl.termination=true
        --o:logging.disable_server_audit=true
        --o:admin_console.enable=false
    cap_drop: [ALL]
    cap_add: [SYS_CHROOT, SYS_ADMIN, FOWNER, CHOWN]
    networks: [syncin, newt]
    labels:
      pangolin.public-resources.syncin.targets[1].method: http
      pangolin.public-resources.syncin.targets[1].path-match: prefix
      pangolin.public-resources.syncin.targets[1].path: /browser
      pangolin.public-resources.syncin.targets[1].port: 9980
      pangolin.public-resources.syncin.targets[1].priority: 110

      pangolin.public-resources.syncin.targets[2].method: http
      pangolin.public-resources.syncin.targets[2].path-match: prefix
      pangolin.public-resources.syncin.targets[2].path: /hosting
      pangolin.public-resources.syncin.targets[2].port: 9980
      pangolin.public-resources.syncin.targets[2].priority: 120

      pangolin.public-resources.syncin.targets[3].method: http
      pangolin.public-resources.syncin.targets[3].path-match: prefix
      pangolin.public-resources.syncin.targets[3].path: /cool
      pangolin.public-resources.syncin.targets[3].port: 9980
      pangolin.public-resources.syncin.targets[3].priority: 130

networks:
  syncin:
