---
# was this a working collabora setup on a different domain than the file server?
# for oc.chenn.dev
services:
  opencloud_collabora:
    profiles: [opencloud]
    image: collabora/code:26.04.2.1.1
    container_name: opencloud_collabora
    restart: unless-stopped
    cap_add: [SYS_ADMIN, MKNOD]
    security_opt: [seccomp=unconfined, apparmor:unconfined]
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    environment:
      username: ${USER}
      password: ${PASS}
      server_name: collabora.chenn.dev
      aliasgroup1: https://wopi.chenn.dev
      DONT_GEN_SSL_CERT: YES
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=true \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=oc.chenn.dev \
        --o:net.lok_allow.host[14]=oc.chenn.dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9980/hosting/discovery']
      interval: 15s
      timeout: 10s
      retries: 5
    networks: [newt]
    labels:
      pangolin.public-resources.oc_collab.name: oc_collab
      pangolin.public-resources.oc_collab.full-domain: collabora.chenn.dev
      pangolin.public-resources.oc_collab.protocol: http
      pangolin.public-resources.oc_collab.ssl: true
      pangolin.public-resources.oc_collab.targets[0].method: http
      pangolin.public-resources.oc_collab.targets[0].port: 9980
      pangolin.public-resources.oc_collab.rules[0].action: pass
      pangolin.public-resources.oc_collab.rules[0].match: country
      pangolin.public-resources.oc_collab.rules[0].value: US
      pangolin.public-resources.oc_collab.rules[1].action: deny
      pangolin.public-resources.oc_collab.rules[1].match: country
      pangolin.public-resources.oc_collab.rules[1].value: ALL
