---
services:
  # dc run archive add --depth=1 'https://news.ycombinator.com'
  # dc run archive schedule --add --every=day --depth=1 'https://example.com/some/rss/feed.xml'
  # https://github.com/ArchiveBox/ArchiveBox/wiki/Chromium-Install#setting-up-a-chromium-user-profile
  archive:
    profiles: [archive]
    image: archivebox/archivebox:latest
    container_name: archive
    dns:
      - ${DNS_VIP}
    volumes:
      - $DATA/archive/data:/data
      # ./archive/profile:/data/personas/Default/chrome_profile/Default
    environment:
      ADMIN_USERNAME: ${USER}
      ADMIN_PASSWORD: ${PASS}
      LISTEN_HOST: archive.chenn.dev
      ALLOWED_HOSTS: archive.chenn.dev
      CSRF_TRUSTED_ORIGINS: https://archive.chenn.dev
      PUBLIC_INDEX: True
      PUBLIC_SNAPSHOTS: True
      PUBLIC_ADD_VIEW: False
      SEARCH_BACKEND_ENGINE: sonic
      SEARCH_BACKEND_HOST_NAME: 127.0.0.1
      SEARCH_BACKEND_PASSWORD: SomeSecretPassword
      USE_COLOR: True
      SHOW_PROGRESS: True
      CHECK_SSL_VALIDITY: False
    networks: [newt]
    labels:
      homepage.group: Media
      homepage.name: Archivebox
      homepage.icon: archivebox.png
      homepage.href: https://archive.chenn.dev
      homepage.description: Web Archiver

      pangolin.public-resources.archive.name: archive
      pangolin.public-resources.archive.full-domain: archive.chenn.dev
      pangolin.public-resources.archive.protocol: http
      pangolin.public-resources.archive.ssl: true
      pangolin.public-resources.archive.targets[0].method: http
      pangolin.public-resources.archive.targets[0].port: 8000
      pangolin.public-resources.archive.auth.sso-enabled: true
      pangolin.public-resources.archive.auth.sso-roles[0]: Member
      pangolin.public-resources.archive.rules[0].action: pass
      pangolin.public-resources.archive.rules[0].match: country
      pangolin.public-resources.archive.rules[0].value: US
      pangolin.public-resources.archive.rules[1].action: deny
      pangolin.public-resources.archive.rules[1].match: country
      pangolin.public-resources.archive.rules[1].value: ALL

  archive_vnc:
    profiles: [archive]
    image: theasp/novnc:latest
    container_name: archive_vnc
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      RUN_XTERM: no
    networks: [newt]
    labels:
      homepage.group: Media
      homepage.name: Archivebox VNC
      homepage.icon: archivebox.png
      homepage.href: https://archive_vnc.chenn.dev
      homepage.description: Archiver Browser Viewer

      pangolin.public-resources.archive_vnc.name: archive_vnc
      pangolin.public-resources.archive_vnc.full-domain: archive_vnc.chenn.dev
      pangolin.public-resources.archive_vnc.protocol: http
      pangolin.public-resources.archive_vnc.ssl: true
      pangolin.public-resources.archive_vnc.targets[0].method: http
      pangolin.public-resources.archive_vnc.targets[0].port: 8080
      pangolin.public-resources.archive_vnc.auth.sso-enabled: true
      pangolin.public-resources.archive_vnc.auth.sso-roles[0]: Member
      pangolin.public-resources.archive_vnc.rules[0].action: pass
      pangolin.public-resources.archive_vnc.rules[0].match: country
      pangolin.public-resources.archive_vnc.rules[0].value: US
      pangolin.public-resources.archive_vnc.rules[1].action: deny
      pangolin.public-resources.archive_vnc.rules[1].match: country
      pangolin.public-resources.archive_vnc.rules[1].value: ALL

  # https://github.com/dgtlmoon/changedetection.io
  archive_change:
    profiles: [archive]
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: archive_change
    volumes:
      - $DATA/archive/change:/datastore

  # https://github.com/webrecorder/pywb
  archive_pywb:
    profiles: [archive]
    image: webrecorder/pywb:latest
    container_name: archive_pywb
    entrypoint: /bin/sh -c '(wb-manager init default || test $$? -eq 2) && wb-manager add default /archivebox/archive/*/warc/*.warc.gz; wayback;'
    environment:
      INIT_COLLECTION: archivebox
    volumes:
      - $DATA/archive/archivebox:/archivebox
      - $DATA/archive/webarchive:/webarchive
    networks: [newt]
    labels:
      homepage.group: Media
      homepage.name: Archivebox PyWB
      homepage.icon: archivebox.png
      homepage.href: https://archive_pywb.chenn.dev
      homepage.description: Archiver Web Recorder

      pangolin.public-resources.archive_pywb.name: archive_pywb
      pangolin.public-resources.archive_pywb.full-domain: archive_pywb.chenn.dev
      pangolin.public-resources.archive_pywb.protocol: http
      pangolin.public-resources.archive_pywb.ssl: true
      pangolin.public-resources.archive_pywb.targets[0].method: http
      pangolin.public-resources.archive_pywb.targets[0].port: 8080
      pangolin.public-resources.archive_pywb.auth.sso-enabled: true
      pangolin.public-resources.archive_pywb.auth.sso-roles[0]: Member
      pangolin.public-resources.archive_pywb.rules[0].action: pass
      pangolin.public-resources.archive_pywb.rules[0].match: country
      pangolin.public-resources.archive_pywb.rules[0].value: US
      pangolin.public-resources.archive_pywb.rules[1].action: deny
      pangolin.public-resources.archive_pywb.rules[1].match: country
      pangolin.public-resources.archive_pywb.rules[1].value: ALL
