---
services:
  audiobookshelf:
    profiles: [audiobookshelf]
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - $MEDIA:/media
      - $DATA/audiobookshelf/config:/config
      - $DATA/audiobookshelf/metadata:/metadata
    networks: [newt]
    labels:
      homepage.group: Media
      homepage.name: AudioBookshelf
      homepage.icon: audiobookshelf.png
      homepage.href: https://audiobookshelf.chenn.dev
      homepage.description: AudioBook Server

      pangolin.public-resources.audiobookshelf.name: audiobookshelf
      pangolin.public-resources.audiobookshelf.full-domain: audiobookshelf.chenn.dev
      pangolin.public-resources.audiobookshelf.protocol: http
      pangolin.public-resources.audiobookshelf.ssl: true
      pangolin.public-resources.audiobookshelf.targets[0].method: http
      pangolin.public-resources.audiobookshelf.targets[0].port: 80
      pangolin.public-resources.audiobookshelf.auth.sso-enabled: true
      pangolin.public-resources.audiobookshelf.auth.sso-roles[0]: Member

      pangolin.public-resources.audiobookshelf.rules[0].action: pass
      pangolin.public-resources.audiobookshelf.rules[0].match: country
      pangolin.public-resources.audiobookshelf.rules[0].value: US
      pangolin.public-resources.audiobookshelf.rules[1].action: deny
      pangolin.public-resources.audiobookshelf.rules[1].match: country
      pangolin.public-resources.audiobookshelf.rules[1].value: ALL
