---
x-booklore_env: &booklore_env
  USER_ID: 1000
  GROUP_ID: 1000
  TZ: $TZ
  DATABASE_URL: jdbc:mariadb://booklore_db:3306/booklore
  SWAGGER_ENABLED: false
  FORCE_DISABLE_OIDC: false
  ALLOWED_ORIGINS: booklore.chenn.dev

  DATABASE_USERNAME: booklore
  DATABASE_PASSWORD: your_secure_password
  MYSQL_USER: booklore
  MYSQL_ROOT_PASSWORD: super_secure_password
  MYSQL_DATABASE: booklore
  MYSQL_PASSWORD: your_secure_password

services:
  booklore:
    profiles: [booklore]
    image: booklore/booklore:latest
    container_name: booklore
    restart: unless-stopped
    environment:
      <<: *booklore_env
    depends_on:
      booklore_db:
        condition: service_healthy
    volumes:
      - $DATA/booklore/data:/app/data
      - $DATA/booklore/books:/books
      - $DATA/booklore/bookdrop:/bookdrop
    healthcheck:
      test: wget -q -O - http://localhost:6060/api/v1/healthcheck
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    networks: [booklore, newt]
    labels:
      homepage.group: Media
      homepage.name: Booklore
      homepage.icon: booklore.png
      homepage.href: https://booklore.chenn.dev
      homepage.description: Book Server

      pangolin.public-resources.booklore.name: booklore
      pangolin.public-resources.booklore.full-domain: booklore.chenn.dev
      pangolin.public-resources.booklore.protocol: http
      pangolin.public-resources.booklore.ssl: true
      pangolin.public-resources.booklore.targets[0].method: http
      pangolin.public-resources.booklore.targets[0].port: 6060
      pangolin.public-resources.booklore.auth.sso-enabled: true
      pangolin.public-resources.booklore.auth.sso-roles[0]: Member
      pangolin.public-resources.booklore.rules[0].action: pass
      pangolin.public-resources.booklore.rules[0].match: country
      pangolin.public-resources.booklore.rules[0].value: US
      pangolin.public-resources.booklore.rules[0].priority: 0
      pangolin.public-resources.booklore.rules[1].action: deny
      pangolin.public-resources.booklore.rules[1].match: country
      pangolin.public-resources.booklore.rules[1].value: ALL
      pangolin.public-resources.booklore.rules[1].priority: 10

  booklore_db:
    profiles: [booklore]
    image: lscr.io/linuxserver/mariadb:11.4.8
    container_name: booklore_db
    restart: unless-stopped
    environment:
      <<: *booklore_env
    volumes:
      - $DATA/booklore/db:/config
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [booklore]

networks:
  booklore:
