---
services:
  navidrome:
    profiles: [navidrome]
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    volumes:
      - $DATA/navidrome:/data
      - $MEDIA/Music:/music:ro
    networks: [newt]
    labels:
      homepage.group: Media
      homepage.name: Navidrome
      homepage.icon: navidrome.png
      homepage.href: https://navidrome.chenn.dev
      homepage.description: Music Server

      pangolin.public-resources.navidrome.name: navidrome
      pangolin.public-resources.navidrome.full-domain: navidrome.chenn.dev
      pangolin.public-resources.navidrome.protocol: http
      pangolin.public-resources.navidrome.ssl: true
      pangolin.public-resources.navidrome.targets[0].method: http
      pangolin.public-resources.navidrome.targets[0].port: 4533
      pangolin.public-resources.navidrome.auth.sso-enabled: true
      pangolin.public-resources.navidrome.auth.sso-roles[0]: Member

      pangolin.public-resources.navidrome.rules[0].action: pass
      pangolin.public-resources.navidrome.rules[0].match: country
      pangolin.public-resources.navidrome.rules[0].value: US
      pangolin.public-resources.navidrome.rules[1].action: deny
      pangolin.public-resources.navidrome.rules[1].match: country
      pangolin.public-resources.navidrome.rules[1].value: ALL
