# runs sync on cron at midnight daily
# manual trigger:
# docker compose run --rm recyclarr sync
# docker compose exec -it recyclarr recyclarr sync
---
services:
  recyclarr:
    profiles: [recyclarr]
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - ./recyclarr:/config
    environment:
      TZ: $TZ
      RECYCLARR_CREATE_CONFIG: true
      RADARR_URL: $RADARR_URL
      RADARR_KEY: $RADARR_KEY
      SONARR_URL: $SONARR_URL
      SONARR_KEY: $SONARR_KEY
    networks: [traefik]
