---
services:
  audiobookshelf:
    profiles: [audiobookshelf]
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      TZ: $TZ
    volumes:
      - $MEDIA/Books:/media
      - $DATA/audiobookshelf/config:/config
      - $DATA/audiobookshelf/metadata:/metadata
    networks: [newt]
    labels:
      homepage.group: Books
      homepage.name: AudioBookshelf
      homepage.icon: audiobookshelf.png
      homepage.href: https://audiobookshelf.chenn.dev
      homepage.description: Audiobook Server

      pangolin.public-resources.audiobookshelf.name: audiobookshelf
      pangolin.public-resources.audiobookshelf.full-domain: audiobookshelf.chenn.dev
      pangolin.public-resources.audiobookshelf.mode: http
      pangolin.public-resources.audiobookshelf.targets[0].method: http
      pangolin.public-resources.audiobookshelf.targets[0].port: 80
      pangolin.public-resources.audiobookshelf.policy: member
