---
services:
  blocky:
    profiles: [blocky]
    image: ghcr.io/0xerr0r/blocky:latest
    container_name: blocky
    restart: unless-stopped
    hostname: blocky
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - ./blocky/config.yml:/app/config.yml
    ports:
      - '${SVC_IP}:53:53/tcp'
      - '${SVC_IP}:53:53/udp'
      - '${SVC_IP}:853:853/tcp'
      - '${SVC_IP}:853:853/udp'

      - '${DNS_VIP}:53:53/tcp'
      - '${DNS_VIP}:53:53/udp'
      - '${DNS_VIP}:853:853/tcp'
      - '${DNS_VIP}:853:853/udp'
