---
x-c2_env: &c2_env
  MYSQL_ROOT_PASSWORD: pass
  MYSQL_USER: c2
  MYSQL_PASSWORD: pass
  MYSQL_DATABASE: c2

  DB_HOST: localhost
  DB_USER: admin
  DB_PASS: changeme
  DB_NAME: c2

  APP_URL: http://localhost:3000
  CORS_ORIGIN:
  SMTP_HOST:
  SMTP_PORT: 587
  SMTP_USER:
  SMTP_PASS:
  SMTP_FROM:

services:
  c2_db:
    image: mysql:8
#    ports:
#      - 3306:3306
    environment:
      <<: *c2_env
    networks: [c2]
    volumes:
      - $DATA/c2/db:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  c2: