---
services:
  healthchecks:
    profiles: [healthchecks]
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SECRET_KEY: very_secret_site_key
      SITE_ROOT: https://healthchecks.chenn.dev
      SITE_NAME: Healthy Chicken
      SUPERUSER_EMAIL: ${EMAIL}
      SUPERUSER_PASSWORD: ${PASS}
      ALLOWED_HOSTS: healthchecks.chenn.dev,healthchecks.henn.dev
      APPRISE_ENABLED: False
      CSRF_TRUSTED_ORIGINS: '["healthchecks.chenn.dev", "healthchecks.henn.dev"]'
      DEBUG: True
      EMAIL_HOST: $SMTP_HOST
      EMAIL_PORT: 465
      EMAIL_HOST_USER: $SMTP_USER
      EMAIL_HOST_PASSWORD: $SMTP_TOKEN
      EMAIL_USE_TLS: True
      INTEGRATIONS_ALLOW_PRIVATE_IPS: False
      PING_EMAIL_DOMAIN: henn.dev
      SITE_LOGO_URL:
    volumes:
      - $DATA/healthchecks/config:/config
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.healthchecks.rule: Host(`healthchecks.henn.dev`)
      traefik.http.routers.healthchecks.entrypoints: websecure
      traefik.http.routers.healthchecks.tls.certresolver: cf
      traefik.http.services.healthchecks.loadbalancer.server.port: 8000
