# addresserror in the logs - no idea what it's from. not cooked yet
---
services:
  hoodik:
    profiles: [hoodik]
    image: hudik/hoodik:latest
    container_name: hoodik
    restart: unless-stopped
    environment:
      APP_URL: https://hoodik.chenn.dev
      HTTP_ADDRESS: 0.0.0.0
      HTTP_PORT: 5443
      SSL_DISABLED: true
      DATABASE_URL: postgresql://hoodik:hoodik@hoodik_pg:5432/hoodik
      DATA_DIR: /data
      MAILER_TYPE: smtp
      SMTP_ADDRESS: $SMTP_HOST
      SMTP_USERNAME: $SMTP_USER
      SMTP_PASSWORD: $SMTP_TOKEN
      SMTP_PORT: 465
    volumes:
      - $DATA/hoodik/data:/data
    networks: [newt, hoodik]
    labels:
      pangolin.public-resources.hoodik.name: hoodik
      pangolin.public-resources.hoodik.protocol: http
      pangolin.public-resources.hoodik.full-domain: hoodik.chenn.dev
      pangolin.public-resources.hoodik.ssl: true
      pangolin.public-resources.hoodik.targets[0].method: http
      pangolin.public-resources.hoodik.targets[0].port: 5443
      pangolin.public-resources.hoodik.auth.sso-enabled: true
      pangolin.public-resources.hoodik.auth.sso-users[0]: ${EMAIL}
      pangolin.public-resources.hoodik.rules[0].action: pass
      pangolin.public-resources.hoodik.rules[0].match: country
      pangolin.public-resources.hoodik.rules[0].value: US
      pangolin.public-resources.hoodik.rules[0].priority: 0
      pangolin.public-resources.hoodik.rules[1].action: deny
      pangolin.public-resources.hoodik.rules[1].match: country
      pangolin.public-resources.hoodik.rules[1].value: ALL
      pangolin.public-resources.hoodik.rules[1].priority: 10

  hoodik_pg:
    profiles: [hoodik]
    image: postgres:18-alpine
    container_name: hoodik_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: hoodik
      POSTGRES_DB: hoodik
      POSTGRES_PASSWORD: hoodik
    volumes:
      - $DATA/hoodik/pg:/var/lib/postgresql
    networks: [hoodik]

networks:
  hoodik:
