# OK folks this is a project from a very dark time in history - it needs some care and feeding. Just to get it standing
# up on the ol sea legs.
# With a bit of TLC we could fix up the packaging and config and shove this thing out the door - I'll have a looksee
# at some more modern offerings before I jump into that

# they use a bash script AND A PYTHON SCRIPT ALSO in a separate step to initialize the database.
# oh my god they didn't put a web server in the main container. They want you to mount the application files into the
# app container, then also mount them into the web server (nginx), then a THIRD container (nginx again) handles SSL
# termination
---
x-misago_env: &misago_env
  VIRTUAL_HOST: misago.chenn.dev,www.misago.chenn.dev
  MISAGO_ADDRESS: https://misago.chenn.dev/
  MISAGO_LANGUAGE_CODE: en-us
  MISAGO_SEARCH_CONFIG: english
  MISAGO_TIME_ZONE: $TZ
  SSL_POLICY: Mozilla-Modern
  VIRTUAL_PROTO: uwsgi
  MISAGO_SECRET_KEY: 3850237539626128d7ea6444c791c38b6b9084034c76b7576443dbba01af58de

  CELERY_BROKER_URL: redis://misago_redis/0
  CACHE_REDIS_URL: redis://misago_redis/1

  POSTGRES_HOST: misago_db
  POSTGRES_DB: misago
  POSTGRES_USER: misago
  POSTGRES_PASSWORD: misago

  MISAGO_EMAIL_PROVIDER: smtp
  MISAGO_EMAIL_HOST: $SMTP_HOST
  MISAGO_EMAIL_PORT: 465
  MISAGO_EMAIL_USER: $SMTP_USER
  MISAGO_EMAIL_PASSWORD: $SMTP_TOKEN
  MISAGO_EMAIL_USE_SSL: true
  MISAGO_EMAIL_USE_TLS: false
  MISAGO_DEFAULT_FROM_EMAIL: $SMTP_USER

  LETSENCRYPT_EMAIL: ${EMAIL}
  LETSENCRYPT_HOST: misago.chenn.dev,www.misago.chenn.dev

  MISAGO_DAILY_BACKUP: false
  MISAGO_DEBUG: false

services:
  misago:
    profiles: [misago]
    build: https://github.com/rafalp/misago_docker.git#v1:misago
    image: ${REGISTRY}/misago:latest
    container_name: misago
    restart: unless-stopped
    environment:
      <<: *misago_env
    volumes:
      - $DATA/misago/media:/misago/media:z
      - $DATA/misago/static:/misago/static:z
      - $DATA/misago/avatargallery:/misago/avatargallery:ro
      - $DATA/misago/theme:/misago/theme:ro
      - $DATA/misago/backups:/misago/backups:Z
      - $DATA/misago/logs:/misago/logs:z
    networks: [misago, newt]
    labels:
      pangolin.public-resources.misago.name: misago
      pangolin.public-resources.misago.full-domain: misago.chenn.dev
      pangolin.public-resources.misago.protocol: http
      pangolin.public-resources.misago.ssl: true
      pangolin.public-resources.misago.targets[0].method: http
      pangolin.public-resources.misago.targets[0].port: 80
      pangolin.public-resources.misago.auth.sso-enabled: true
      pangolin.public-resources.misago.auth.sso-roles[0]: Member
      pangolin.public-resources.misago.rules[0].action: pass
      pangolin.public-resources.misago.rules[0].match: country
      pangolin.public-resources.misago.rules[0].value: US
      pangolin.public-resources.misago.rules[1].action: deny
      pangolin.public-resources.misago.rules[1].match: country
      pangolin.public-resources.misago.rules[1].value: ALL

  misago_celery:
    profiles: [misago]
    build: https://github.com/rafalp/misago_docker.git#v1:misago
    image: ${REGISTRY}/misago:latest
    container_name: misago_celery
    restart: unless-stopped
    command: celery -A misagodocker worker --loglevel=info
    environment:
      <<: *misago_env
    volumes:
      - $DATA/misago/media:/misago/media:z
      - $DATA/misago/static:/misago/static:z
      - $DATA/misago/theme:/misago/theme:ro
      - $DATA/misago/logs:/misago/logs:z
    networks: [misago]

  misago_db:
    profiles: [misago]
    image: postgres:18-alpine
    container_name: misago_db
    restart: unless-stopped
    environment:
      <<: *misago_env
    volumes:
      - $DATA/misago/db:/var/lib/postgresql
    networks: [misago]

  misago_redis:
    profiles: [misago]
    image: redis:8-alpine
    container_name: misago_redis
    restart: unless-stopped
    volumes:
      - $DATA/misago/redis:/data
    networks: [misago]

networks:
  misago:
