---
services:
  onlyoffice:
    profiles: [onlyoffice]
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: unless-stopped
    environment:
      WOPI_ENABLED: true
      USE_UNAUTHORIZED_STORAGE: false
      JWT_ENABLED: true

      DB_TYPE: postgres
      DB_HOST: onlyoffice_db
      DB_PORT: 5432
      DB_NAME: onlyoffice
      DB_USER: onlyoffice
      AMQP_URI: amqp://guest:guest@onlyoffice_mq
      JWT_SECRET: secret
      JWT_HEADER: Authorization
      JWT_IN_BODY: true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/info/info.json']
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.office.rule: Host(`office.henn.dev`)
      traefik.http.routers.office.entrypoints: websecure
      traefik.http.routers.office.middlewares: hdrs@file
      traefik.http.routers.office.tls.certresolver: cf
      traefik.http.services.office.loadbalancer.server.port: 80

  onlyoffice_mq:
    profiles: [onlyoffice]
    image: rabbitmq:3-alpine
    container_name: onlyoffice_mq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics status
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks: [traefik]

  onlyoffice_db:
    profiles: [onlyoffice]
    image: postgres:18-alpine
    container_name: onlyoffice_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: onlyoffice
      POSTGRES_USER: onlyoffice
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - $DATA/onlyoffice/db:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U onlyoffice
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks: [traefik]
