# janky web frontend for docker registry; do not use
---
services:
  registry_ui:
    profiles: [registry]
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    restart: unless-stopped
    environment:
      DELETE_IMAGES: true
      REGISTRY_TITLE: Dancing Containers
      NGINX_PROXY_PASS_URL: http://registry:5000
      SINGLE_REGISTRY: true
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.registryui.rule: Host(`regui.henn.dev`)
      traefik.http.routers.registryui.entrypoints: websecure
      traefik.http.routers.registryui.tls.certresolver: cf
      traefik.http.services.registryui.loadbalancer.server.port: 80
