# working stoat rustfs
x-stoat_s3: &stoat_s3
  RUSTFS_ACCESS_KEY: minioautumn
  RUSTFS_SECRET_KEY: minioautumn
  RUSTFS_SERVER_DOMAINS: stoat-s3

services:
  stoat-s3:
    profiles: [stoat]
    image: rustfs/rustfs:latest
    container_name: stoat-s3
    restart: unless-stopped
    command: /data
    environment:
      <<: *stoat_s3
    volumes:
      - $DATA/stoat/s3:/data
    healthcheck:
      test: curl -f http://localhost:9000/health
      timeout: 5s
      retries: 10
      start_period: 15s
      interval: 5s
    depends_on:
      stoat-s3_perm:
        condition: service_completed_successfully
    networks:
      stoat:
        aliases:
          - revolt-uploads.stoat-s3

  stoat-s3_perm:
    profiles: [stoat]
    image: alpine
    container_name: stoat-s3_perm
    restart: no
    user: root
    volumes:
      - $DATA/stoat/s3:/data
    command: chown -R 10001:10001 /data

  stoat-s3_bucket:
    profiles: [stoat]
    image: minio/mc
    container_name: stoat-s3_bucket
    restart: no
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        until mc alias set rustfs http://stoat-s3:9000 minioautumn minioautumn; do
          echo 'waiting to connect to stoat-s3'
          sleep 2
        done
        mc mb rustfs/revolt-uploads --ignore-existing
    depends_on:
      stoat-s3:
        condition: service_healthy
    networks: [stoat]

---
# probably working plane rustfs
x-plane_env: &plane_env
  RUSTFS_ACCESS_KEY: ${PLANE_S3_ACCESS}
  RUSTFS_SECRET_KEY: ${PLANE_S3_SECRET}
  RUSTFS_VOLUMES: /data
  RUSTFS_ADDRESS: :9000
  RUSTFS_EXTERNAL_ADDRESS: :9000
  RUSTFS_CONSOLE_ENABLE: true
  RUSTFS_CONSOLE_ADDRESS: :9001
  RUSTFS_CORS_ALLOWED_ORIGINS: '*'
  RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: '*'

services:
  plane_s3_setup:
    profiles: [plane]
    image: minio/mc
    container_name: plane_s3_setup
    restart: no
    environment:
      <<: *plane_env
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        until mc alias set rustfs $${AWS_S3_ENDPOINT_URL} $${RUSTFS_ACCESS_KEY} $${RUSTFS_SECRET_KEY}; do
          echo 'waiting to connect to plane_s3'
          sleep 2
        done
        mc mb rustfs/$${AWS_S3_BUCKET_NAME} --ignore-existing
    depends_on:
      plane_s3:
        condition: service_healthy
    networks: [plane]

  plane_s3:
    profiles: [plane]
    image: rustfs/rustfs:latest
    container_name: plane_s3
    restart: unless-stopped
    command: /data
    environment:
      <<: *plane_env
    volumes:
      - $DATA/plane/s3:/data
    healthcheck:
      test: curl -f http://localhost:9000/health
      timeout: 5s
      retries: 10
      start_period: 15s
      interval: 5s
    depends_on:
      plane_perm:
        condition: service_completed_successfully
    networks: [plane, traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.plane_s3.rule: Host(`s3.plane.henn.dev`)
      traefik.http.routers.plane_s3.entrypoints: websecure
      traefik.http.routers.plane_s3.middlewares: hdrs@file
      traefik.http.routers.plane_s3.tls.certresolver: cf
      traefik.http.services.plane_s3.loadbalancer.server.port: 9001

  plane_perm:
    profiles: [plane]
    image: alpine
    container_name: plane_perm
    restart: no
    user: root
    volumes:
      - $DATA/plane/s3:/data/s3
      - $DATA/plane/search:/data/search
    command:
      - /bin/sh
      - -c
      - |
        set -x
        chown -R 10001:10001 /data/s3
        echo "set perms; exit: $?"
