---
configs:
  blocky_k:
    content: |
      vrrp_script check_blocky {
          script "/usr/bin/dig @${KEEPALIVE_BACKUP} -p 53 healthcheck.blocky +tcp +short"
          weight -50
          timeout 1
          interval 1
          fall 2
          rise 2
      }

      vrrp_instance VI_1 {
          state BACKUP
          interface ${RACK0_NIC}
          virtual_router_id 55
          priority 125
          advert_int 1

          track_script {
              check_blocky
          }
          authentication {
              auth_type PASS
              auth_pass ${KEEPALIVE_PASS}
          }
          unicast_src_ip ${KEEPALIVE_BACKUP}
          unicast_peer {
              ${KEEPALIVE_MASTER}
          }
          virtual_ipaddress {
              ${DNS_VIP_CIDR}
          }
      }

services:
  blocky_k:
    profiles: [blocky_k]
    image: ${REGISTRY}/keepalived:latest
    container_name: blocky_k
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      KEEPALIVED_CUSTOM_CONFIG: true
    configs:
      - source: blocky_k
        target: /etc/keepalived/keepalived.conf
    network_mode: host
    cap_add: [NET_ADMIN, NET_BROADCAST]
