---
networks:
  traefik:
    name: traefik
    driver: bridge

services:
  traefik:
    profiles: [traefik]
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $REPO_HOST/rack4/apps/infra/traefik/traefik.yml:/traefik.yml:ro
      - $REPO_HOST/rack4/apps/infra/traefik/cfg:/cfg:ro
      # CANNOT BE A CIFS MOUNT. Will work the first time, then fail after restarting container
      - $HOME_HOST/rack0_traefik/ssl:/ssl
      - $HOME_HOST/rack0_traefik/logs:/logs
    networks: [traefik]
    labels:
      traefik.enable: true
      traefik.http.routers.dash.rule: Host(`rack0-traefik.henn.dev`)
      traefik.http.routers.dash.entrypoints: websecure
      traefik.http.routers.dash.service: api@internal
      traefik.http.routers.dash.tls.certresolver: cf
    ports:
      - '${SVC_IP}:80:80'
      - '${SVC_IP}:443:443'
      - '${SVC_IP}:8080:8080'
      - '${TRAEFIK_VIP}:80:80'
      - '${TRAEFIK_VIP}:443:443'
      - '${TRAEFIK_VIP}:8080:8080'
