---
configs:
  traefik_k:
    content: |
      vrrp_script check_traefik {
          script "/usr/bin/curl --fail http://${KEEPALIVE_BACKUP}:8080/ping -t 1"
          weight -50
          timeout 1
          interval 1
          fall 2
          rise 2
      }

      vrrp_instance VI_2 {
          state BACKUP
          interface ${RACK0_NIC}
          virtual_router_id 56
          priority 125
          advert_int 1

          track_script {
              check_traefik
          }
          authentication {
              auth_type PASS
              auth_pass ${KEEPALIVE_PASS}
          }
          unicast_src_ip ${KEEPALIVE_BACKUP}
          unicast_peer {
              ${KEEPALIVE_MASTER}
          }
          virtual_ipaddress {
              ${TRAEFIK_VIP_CIDR}
          }
      }

services:
  traefik_k:
    profiles: [traefik_k]
    image: shawly/keepalived:latest
    container_name: traefik_k
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      KEEPALIVED_CUSTOM_CONFIG: 'true'
    configs:
      - source: traefik_k
        target: /etc/keepalived/keepalived.conf
    network_mode: host
    cap_add: [NET_ADMIN, NET_BROADCAST]
