TGT := "/mnt/h/backup/github"
BIN := "https://github.com/ChappIO/git-backup/releases/download/v1.6.1/git-backup-linux-x64"

run:
    #!/bin/bash

    # install 1password cli
    if ! grep -qF "https://downloads.1password.com/linux/alpinelinux/stable/" /etc/apk/repositories; then
        sudo sh -c 'echo https://downloads.1password.com/linux/alpinelinux/stable/ >> /etc/apk/repositories'
    fi
    if [ ! -f /etc/apk/keys/support@1password.com-61ddfc31.rsa.pub ]; then
        sudo wget https://downloads.1password.com/linux/keys/alpinelinux/support@1password.com-61ddfc31.rsa.pub -P /etc/apk/keys
        sudo apk update && sudo apk add 1password-cli
    fi

    # download the git-backup binary
    if [[ ! -f gitbackup ]]; then
        echo "downloading gitbackup binary"
        sudo curl -Lo gitbackup {{BIN}}
        sudo chmod +x gitbackup
    else
        echo "using existing gitbackup binary"
    fi

    op inject -i config.yml -o secrets.yml -f
    ./gitbackup -backup.path {{TGT}} -config.file secrets.yml -backup.fail-at-end
    rm secrets.yml
