# not read yet - qbittorrent client can't create category successfully - probably needs to bypass auth (blank user no worky)
# sudo chown -R 1000:1000 $DATA/mediamanager/images
---
services:
  mediamanager:
    profiles: [mm]
    container_name: mediamanager
    image: quay.io/maxdorninger/mediamanager:latest
    environment:
      MEDIAMANAGER_DATABASE__HOST: mediamanager_db

      CONFIG_DIR: /app/config
      MEDIAMANAGER_MISC__TV_DIRECTORY: /data/TV
      MEDIAMANAGER_MISC__MOVIE_DIRECTORY: /data/Movies
      MEDIAMANAGER_MISC__IMAGE_DIRECTORY: /data/images
      MEDIAMANAGER_MISC__TORRENT_DIRECTORY: /data/torrents

      MEDIAMANAGER_AUTH__OPENID_CONNECT__ENABLED: true
      MEDIAMANAGER_AUTH__OPENID_CONNECT__CLIENT_ID: ${MM_OIDC_CLIENT}
      MEDIAMANAGER_AUTH__OPENID_CONNECT__CLIENT_SECRET: ${MM_OIDC_SECRET}
      MEDIAMANAGER_AUTH__OPENID_CONNECT__CONFIGURATION_ENDPOINT: $OIDC/.well-known/openid-configuration
      MEDIAMANAGER_AUTH__OPENID_CONNECT__NAME: Pocket ID

      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__SMTP_HOST: $SMTP_HOST
      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__SMTP_PORT: 465
      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__SMTP_USER: $SMTP_USER
      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__SMTP_PASSWORD: $SMTP_TOKEN
      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__FROM_EMAIL: mediamanager@chenn.dev
      MEDIAMANAGER_NOTIFICATIONS__SMTP_CONFIG__USE_TLS: true

      MEDIAMANAGER_TORRENTS__QBITTORRENT__ENABLED: true
      MEDIAMANAGER_TORRENTS__QBITTORRENT__HOST: http://gluetun
      MEDIAMANAGER_TORRENTS__QBITTORRENT__PORT: 8080
      MEDIAMANAGER_TORRENTS__QBITTORRENT__USERNAME: ${USER}
      MEDIAMANAGER_TORRENTS__QBITTORRENT__PASSWORD: ${PASS}

      MEDIAMANAGER_TORRENTS__SABNZBD__ENABLED: true
      MEDIAMANAGER_TORRENTS__SABNZBD__HOST: http://sab
      MEDIAMANAGER_TORRENTS__SABNZBD__PORT: 8080
      MEDIAMANAGER_TORRENTS__SABNZBD__API_KEY: ${SAB_API_KEY}
      MEDIAMANAGER_TORRENTS__SABNZBD__BASE_PATH: /api

      MEDIAMANAGER_INDEXERS__PROWLARR__ENABLED: true
      MEDIAMANAGER_INDEXERS__PROWLARR__URL: http://prowlarr:9696
      MEDIAMANAGER_INDEXERS__PROWLARR__API_KEY: ${PROWLARR_API_KEY}
      MEDIAMANAGER_INDEXERS__PROWLARR__TIMEOUT_SECONDS: 60

    volumes:
      - $MEDIA/:/data/
      - ./mediamanager/:/app/config/
      - $DATA/mediamanager/images/:/data/images/
      - $DATA/qbit/downloads/:/data/torrents
    networks: [traefik, mm]
    labels:
      pangolin.public-resources.mm.name: mm
      pangolin.public-resources.mm.protocol: http
      pangolin.public-resources.mm.full-domain: mm.chenn.dev
      pangolin.public-resources.mm.ssl: true
      pangolin.public-resources.mm.targets[0].method: http
      pangolin.public-resources.mm.targets[0].port: 8000

      pangolin.public-resources.mm.auth.sso-enabled: true
      pangolin.public-resources.mm.auth.sso-roles[0]: Member
      pangolin.public-resources.mm.rules[0].action: pass
      pangolin.public-resources.mm.rules[0].match: country
      pangolin.public-resources.mm.rules[0].value: US
      pangolin.public-resources.mm.rules[0].priority: 0
      pangolin.public-resources.mm.rules[1].action: deny
      pangolin.public-resources.mm.rules[1].match: country
      pangolin.public-resources.mm.rules[1].value: ALL
      pangolin.public-resources.mm.rules[1].priority: 10

  mediamanager_db:
    profiles: [mm]
    container_name: mediamanager_db
    image: postgres:18
    restart: unless-stopped
    volumes:
      - $DATA/mediamanager/db:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: MediaManager
      POSTGRES_DB: MediaManager
      POSTGRES_PASSWORD: MediaManager
    networks: [mm]

networks:
  mm:
