---
services:
  8mb:
    profiles: [8mb]
    image: jms1717/8mblocal:latest
    container_name: 8mb
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    volumes:
      - $DATA/8mb/uploads:/app/uploads
      - $DATA/8mb/outputs:/app/outputs
    networks: [newt]
    labels:
      homepage.group: Converters
      homepage.name: 8MB
      homepage.icon: compreface.png
      homepage.href: https://8MB.chenn.dev
      homepage.description: Video Compressor

      pangolin.public-resources.8mb.name: 8mb
      pangolin.public-resources.8mb.full-domain: 8mb.chenn.dev
      pangolin.public-resources.8mb.mode: http
      pangolin.public-resources.8mb.targets[0].method: http
      pangolin.public-resources.8mb.targets[0].port: 8001
      pangolin.public-resources.8mb.policy: member
