---
services:
  convertx:
    profiles: [convertx]
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    restart: unless-stopped
    environment:
      ALLOW_UNAUTHENTICATED: false
      ACCOUNT_REGISTRATION: true
    volumes:
      - $DATA/convertx:/app/data
    networks: [newt]
    labels:
      homepage.group: File Converters
      homepage.name: Convertx
      homepage.icon: https://github.com/C4illin/ConvertX/raw/refs/heads/main/public/favicon.svg
      homepage.href: https://convertx.chenn.dev
      homepage.description: File Converter

      pangolin.public-resources.convertx.name: convertx
      pangolin.public-resources.convertx.full-domain: convertx.chenn.dev
      pangolin.public-resources.convertx.protocol: http
      pangolin.public-resources.convertx.ssl: true
      pangolin.public-resources.convertx.targets[0].method: http
      pangolin.public-resources.convertx.targets[0].port: 3000
      pangolin.public-resources.convertx.auth.sso-enabled: true
      pangolin.public-resources.convertx.auth.sso-roles[0]: Member

      pangolin.public-resources.convertx.rules[0].action: pass
      pangolin.public-resources.convertx.rules[0].match: country
      pangolin.public-resources.convertx.rules[0].value: US
      pangolin.public-resources.convertx.rules[1].action: deny
      pangolin.public-resources.convertx.rules[1].match: country
      pangolin.public-resources.convertx.rules[1].value: ALL
