---
services:
  mazanoke:
    profiles: [mazanoke]
    image: ghcr.io/civilblur/mazanoke:latest
    container_name: mazanoke
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: File Converters
      homepage.name: Mazanoke
      homepage.icon: mazanoke.png
      homepage.href: https://mazanoke.chenn.dev
      homepage.description: Image Converter

      pangolin.public-resources.mazanoke.name: mazanoke
      pangolin.public-resources.mazanoke.full-domain: mazanoke.chenn.dev
      pangolin.public-resources.mazanoke.protocol: http
      pangolin.public-resources.mazanoke.ssl: true
      pangolin.public-resources.mazanoke.targets[0].method: http
      pangolin.public-resources.mazanoke.targets[0].port: 80
      pangolin.public-resources.mazanoke.auth.sso-enabled: true
      pangolin.public-resources.mazanoke.auth.sso-roles[0]: Member
      pangolin.public-resources.mazanoke.rules[0].action: pass
      pangolin.public-resources.mazanoke.rules[0].match: country
      pangolin.public-resources.mazanoke.rules[0].value: US
      pangolin.public-resources.mazanoke.rules[0].priority: 0
      pangolin.public-resources.mazanoke.rules[1].action: deny
      pangolin.public-resources.mazanoke.rules[1].match: country
      pangolin.public-resources.mazanoke.rules[1].value: ALL
      pangolin.public-resources.mazanoke.rules[1].priority: 10
