---
services:
  omni:
    profiles: [omni]
    image: iib0011/omni-tools:latest
    container_name: omni
    restart: unless-stopped
    networks: [newt]
    labels:
      homepage.group: Converters
      homepage.name: Omni Converters
      homepage.icon: omni-tools.png
      homepage.href: https://omni.chenn.dev
      homepage.description: File Converters and Tools

      pangolin.public-resources.omni.name: omni
      pangolin.public-resources.omni.full-domain: omni.chenn.dev
      pangolin.public-resources.omni.mode: http
      pangolin.public-resources.omni.targets[0].method: http
      pangolin.public-resources.omni.targets[0].port: 80
      pangolin.public-resources.omni.policy: member
