# works better than opensign, but not as well as documenso
---
services:
  docuseal:
    profiles: [docuseal]
    image: docuseal/docuseal:latest
    container_name: docuseal
    volumes:
      - $DATA/docuseal/data:/data/docuseal
    environment:
      FORCE_SSL: docuseal.henn.dev
      DATABASE_URL: postgresql://postgres:postgres@docuseal_db:5432/docuseal
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_ADDRESS: ${SMTP_HOST}
      SMTP_PORT: 587
      SMTP_DOMAIN: ${SMTP_HOST}
      SMTP_PASSWORD: ${SMTP_TOKEN}
      SMTP_AUTHENTICATION: login
      SMTP_FROM: ${SMTP_USER}
      SMTP_ENABLE_STARTTLS: true
      SMTP_SSL_VERIFY: true
    networks: [traefik, docuseal]
    labels:
      traefik.enable: true
      traefik.http.routers.docuseal.rule: Host(`docuseal.henn.dev`)
      traefik.http.routers.docuseal.entrypoints: websecure
      traefik.http.routers.docuseal.middlewares: hdrs@file
      traefik.http.routers.docuseal.tls.certresolver: cf
      traefik.http.services.docuseal.loadbalancer.server.port: 3000

  docuseal_db:
    profiles: [docuseal]
    image: postgres:18
    container_name: docuseal_db
    volumes:
      - $DATA/docuseal/docuseal_db:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [docuseal]

networks:
  docuseal:
