---
services:
  ollama:
    profiles: [ollama]
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    environment:
      OLLAMA_CONTEXT_LENGTH: 32000
      OLLAMA_FLASH_ATTENTION: 1
    volumes:
      - $DATA/ollama:/root/.ollama
    networks: [ollama]

networks:
  ollama:
