---
services:
  lidarr:
    profiles: [arr]
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LIDARR__AUTH__METHOD: External
    volumes:
      - $DATA/lidarr:/config
      - $DATA/sab/downloads:/sab/downloads
      - $DATA/qbit/downloads:/qbit/downloads
      - $MEDIA:/media_library
    networks: [arr, newt]
    labels:
      homepage.group: Arr
      homepage.name: Lidarr
      homepage.icon: lidarr.png
      homepage.href: https://lidarr.chenn.dev
      homepage.description: Music Manager

      pangolin.public-resources.lidarr.name: lidarr
      pangolin.public-resources.lidarr.full-domain: lidarr.chenn.dev
      pangolin.public-resources.lidarr.mode: http
      pangolin.public-resources.lidarr.targets[0].method: http
      pangolin.public-resources.lidarr.targets[0].port: 8686
      pangolin.public-resources.lidarr.policy: arr
