---
services:
  mseerr:
    profiles: [arr]
    image: ghcr.io/habirabbu/musicseerr:latest
    container_name: mseerr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: $TZ
      PORT: 8688
    volumes:
      - $DATA/mseerr/config:/app/config
      - $DATA/mseerr/cache:/app/cache
      - $MEDIA/Music:/music:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8688/health']
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3
    networks: [arr, newt]
    labels:
      homepage.group: Arr
      homepage.name: Music Seerr
      homepage.icon: https://github.com/HabiRabbu/Musicseerr/blob/main/Images/logo_icon.png?raw=true
      homepage.href: https://mseerr.chenn.dev
      homepage.description: Music Discovery

      pangolin.public-resources.mseerr.name: mseerr
      pangolin.public-resources.mseerr.full-domain: mseerr.chenn.dev
      pangolin.public-resources.mseerr.mode: http
      pangolin.public-resources.mseerr.targets[0].method: http
      pangolin.public-resources.mseerr.targets[0].port: 8688
      pangolin.public-resources.mseerr.policy: arr
