---
services:
  navidrome:
    profiles: [navidrome]
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    volumes:
      - $DATA/navidrome:/data
      - $MEDIA/Music:/music:ro
    networks: [newt]
    labels:
      homepage.group: Music
      homepage.name: Navidrome
      homepage.icon: navidrome.png
      homepage.href: https://navidrome.chenn.dev
      homepage.description: Music Server

      pangolin.public-resources.navidrome.name: navidrome
      pangolin.public-resources.navidrome.full-domain: navidrome.chenn.dev
      pangolin.public-resources.navidrome.mode: http
      pangolin.public-resources.navidrome.targets[0].method: http
      pangolin.public-resources.navidrome.targets[0].port: 4533
      pangolin.public-resources.navidrome.policy: member
